// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.19.6
// source: api/aicook/v1/ai.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAIServiceCreateSession = "/aicook.v1.AIService/CreateSession"
const OperationAIServiceDeleteSession = "/aicook.v1.AIService/DeleteSession"
const OperationAIServiceListMessages = "/aicook.v1.AIService/ListMessages"
const OperationAIServiceListSessions = "/aicook.v1.AIService/ListSessions"
const OperationAIServiceSendMessage = "/aicook.v1.AIService/SendMessage"

type AIServiceHTTPServer interface {
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionReply, error)
	DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionReply, error)
	ListMessages(context.Context, *ListMessagesRequest) (*ListMessagesReply, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsReply, error)
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageReply, error)
}

func RegisterAIServiceHTTPServer(s *http.Server, srv AIServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/ai/sessions", _AIService_CreateSession0_HTTP_Handler(srv))
	r.POST("/api/v1/ai/sessions/{session_id}/messages", _AIService_SendMessage0_HTTP_Handler(srv))
	r.GET("/api/v1/ai/sessions", _AIService_ListSessions0_HTTP_Handler(srv))
	r.GET("/api/v1/ai/sessions/{session_id}/messages", _AIService_ListMessages0_HTTP_Handler(srv))
	r.DELETE("/api/v1/ai/sessions/{session_id}", _AIService_DeleteSession0_HTTP_Handler(srv))
}

func _AIService_CreateSession0_HTTP_Handler(srv AIServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateSessionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAIServiceCreateSession)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateSession(ctx, req.(*CreateSessionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateSessionReply)
		return ctx.Result(200, reply)
	}
}

func _AIService_SendMessage0_HTTP_Handler(srv AIServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SendMessageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAIServiceSendMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendMessage(ctx, req.(*SendMessageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SendMessageReply)
		return ctx.Result(200, reply)
	}
}

func _AIService_ListSessions0_HTTP_Handler(srv AIServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListSessionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAIServiceListSessions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListSessions(ctx, req.(*ListSessionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListSessionsReply)
		return ctx.Result(200, reply)
	}
}

func _AIService_ListMessages0_HTTP_Handler(srv AIServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListMessagesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAIServiceListMessages)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListMessages(ctx, req.(*ListMessagesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListMessagesReply)
		return ctx.Result(200, reply)
	}
}

func _AIService_DeleteSession0_HTTP_Handler(srv AIServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteSessionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAIServiceDeleteSession)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteSession(ctx, req.(*DeleteSessionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteSessionReply)
		return ctx.Result(200, reply)
	}
}

type AIServiceHTTPClient interface {
	CreateSession(ctx context.Context, req *CreateSessionRequest, opts ...http.CallOption) (rsp *CreateSessionReply, err error)
	DeleteSession(ctx context.Context, req *DeleteSessionRequest, opts ...http.CallOption) (rsp *DeleteSessionReply, err error)
	ListMessages(ctx context.Context, req *ListMessagesRequest, opts ...http.CallOption) (rsp *ListMessagesReply, err error)
	ListSessions(ctx context.Context, req *ListSessionsRequest, opts ...http.CallOption) (rsp *ListSessionsReply, err error)
	SendMessage(ctx context.Context, req *SendMessageRequest, opts ...http.CallOption) (rsp *SendMessageReply, err error)
}

type AIServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewAIServiceHTTPClient(client *http.Client) AIServiceHTTPClient {
	return &AIServiceHTTPClientImpl{client}
}

func (c *AIServiceHTTPClientImpl) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...http.CallOption) (*CreateSessionReply, error) {
	var out CreateSessionReply
	pattern := "/api/v1/ai/sessions"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAIServiceCreateSession))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AIServiceHTTPClientImpl) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...http.CallOption) (*DeleteSessionReply, error) {
	var out DeleteSessionReply
	pattern := "/api/v1/ai/sessions/{session_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAIServiceDeleteSession))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AIServiceHTTPClientImpl) ListMessages(ctx context.Context, in *ListMessagesRequest, opts ...http.CallOption) (*ListMessagesReply, error) {
	var out ListMessagesReply
	pattern := "/api/v1/ai/sessions/{session_id}/messages"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAIServiceListMessages))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AIServiceHTTPClientImpl) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...http.CallOption) (*ListSessionsReply, error) {
	var out ListSessionsReply
	pattern := "/api/v1/ai/sessions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAIServiceListSessions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *AIServiceHTTPClientImpl) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...http.CallOption) (*SendMessageReply, error) {
	var out SendMessageReply
	pattern := "/api/v1/ai/sessions/{session_id}/messages"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAIServiceSendMessage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
