// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/aicook/v1/cooking.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListActiveCookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveCookingRequest) Reset() {
	*x = ListActiveCookingRequest{}
	mi := &file_api_aicook_v1_cooking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveCookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveCookingRequest) ProtoMessage() {}

func (x *ListActiveCookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_cooking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveCookingRequest.ProtoReflect.Descriptor instead.
func (*ListActiveCookingRequest) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_cooking_proto_rawDescGZIP(), []int{0}
}

type ListActiveCookingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ActiveCooking       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActiveCookingReply) Reset() {
	*x = ListActiveCookingReply{}
	mi := &file_api_aicook_v1_cooking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActiveCookingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActiveCookingReply) ProtoMessage() {}

func (x *ListActiveCookingReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_cooking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActiveCookingReply.ProtoReflect.Descriptor instead.
func (*ListActiveCookingReply) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_cooking_proto_rawDescGZIP(), []int{1}
}

func (x *ListActiveCookingReply) GetItems() []*ActiveCooking {
	if x != nil {
		return x.Items
	}
	return nil
}

type ActiveCooking struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RecipeId          int64                  `protobuf:"varint,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	Title             string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	CoverImageUrl     string                 `protobuf:"bytes,3,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
	StepIndex         int32                  `protobuf:"varint,4,opt,name=step_index,json=stepIndex,proto3" json:"step_index,omitempty"`
	TotalSteps        int32                  `protobuf:"varint,5,opt,name=total_steps,json=totalSteps,proto3" json:"total_steps,omitempty"`
	TimerTotalSeconds int32                  `protobuf:"varint,6,opt,name=timer_total_seconds,json=timerTotalSeconds,proto3" json:"timer_total_seconds,omitempty"`
	RemainingSeconds  int32                  `protobuf:"varint,7,opt,name=remaining_seconds,json=remainingSeconds,proto3" json:"remaining_seconds,omitempty"`
	UpdatedAtMs       int64                  `protobuf:"varint,8,opt,name=updated_at_ms,json=updatedAtMs,proto3" json:"updated_at_ms,omitempty"`
	TimerRunning      bool                   `protobuf:"varint,9,opt,name=timer_running,json=timerRunning,proto3" json:"timer_running,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ActiveCooking) Reset() {
	*x = ActiveCooking{}
	mi := &file_api_aicook_v1_cooking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActiveCooking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveCooking) ProtoMessage() {}

func (x *ActiveCooking) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_cooking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveCooking.ProtoReflect.Descriptor instead.
func (*ActiveCooking) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_cooking_proto_rawDescGZIP(), []int{2}
}

func (x *ActiveCooking) GetRecipeId() int64 {
	if x != nil {
		return x.RecipeId
	}
	return 0
}

func (x *ActiveCooking) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ActiveCooking) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *ActiveCooking) GetStepIndex() int32 {
	if x != nil {
		return x.StepIndex
	}
	return 0
}

func (x *ActiveCooking) GetTotalSteps() int32 {
	if x != nil {
		return x.TotalSteps
	}
	return 0
}

func (x *ActiveCooking) GetTimerTotalSeconds() int32 {
	if x != nil {
		return x.TimerTotalSeconds
	}
	return 0
}

func (x *ActiveCooking) GetRemainingSeconds() int32 {
	if x != nil {
		return x.RemainingSeconds
	}
	return 0
}

func (x *ActiveCooking) GetUpdatedAtMs() int64 {
	if x != nil {
		return x.UpdatedAtMs
	}
	return 0
}

func (x *ActiveCooking) GetTimerRunning() bool {
	if x != nil {
		return x.TimerRunning
	}
	return false
}

type UpsertActiveCookingRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RecipeId          int64                  `protobuf:"varint,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	StepIndex         int32                  `protobuf:"varint,2,opt,name=step_index,json=stepIndex,proto3" json:"step_index,omitempty"`
	TotalSteps        int32                  `protobuf:"varint,3,opt,name=total_steps,json=totalSteps,proto3" json:"total_steps,omitempty"`
	TimerTotalSeconds int32                  `protobuf:"varint,4,opt,name=timer_total_seconds,json=timerTotalSeconds,proto3" json:"timer_total_seconds,omitempty"`
	TimerStartedAtMs  int64                  `protobuf:"varint,5,opt,name=timer_started_at_ms,json=timerStartedAtMs,proto3" json:"timer_started_at_ms,omitempty"`
	// When timer is paused (timer_started_at_ms == 0), seconds left for current step.
	TimerPausedRemaining int32 `protobuf:"varint,6,opt,name=timer_paused_remaining,json=timerPausedRemaining,proto3" json:"timer_paused_remaining,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpsertActiveCookingRequest) Reset() {
	*x = UpsertActiveCookingRequest{}
	mi := &file_api_aicook_v1_cooking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertActiveCookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertActiveCookingRequest) ProtoMessage() {}

func (x *UpsertActiveCookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_cooking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertActiveCookingRequest.ProtoReflect.Descriptor instead.
func (*UpsertActiveCookingRequest) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_cooking_proto_rawDescGZIP(), []int{3}
}

func (x *UpsertActiveCookingRequest) GetRecipeId() int64 {
	if x != nil {
		return x.RecipeId
	}
	return 0
}

func (x *UpsertActiveCookingRequest) GetStepIndex() int32 {
	if x != nil {
		return x.StepIndex
	}
	return 0
}

func (x *UpsertActiveCookingRequest) GetTotalSteps() int32 {
	if x != nil {
		return x.TotalSteps
	}
	return 0
}

func (x *UpsertActiveCookingRequest) GetTimerTotalSeconds() int32 {
	if x != nil {
		return x.TimerTotalSeconds
	}
	return 0
}

func (x *UpsertActiveCookingRequest) GetTimerStartedAtMs() int64 {
	if x != nil {
		return x.TimerStartedAtMs
	}
	return 0
}

func (x *UpsertActiveCookingRequest) GetTimerPausedRemaining() int32 {
	if x != nil {
		return x.TimerPausedRemaining
	}
	return 0
}

type UpsertActiveCookingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *ActiveCooking         `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertActiveCookingReply) Reset() {
	*x = UpsertActiveCookingReply{}
	mi := &file_api_aicook_v1_cooking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertActiveCookingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertActiveCookingReply) ProtoMessage() {}

func (x *UpsertActiveCookingReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_cooking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertActiveCookingReply.ProtoReflect.Descriptor instead.
func (*UpsertActiveCookingReply) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_cooking_proto_rawDescGZIP(), []int{4}
}

func (x *UpsertActiveCookingReply) GetItem() *ActiveCooking {
	if x != nil {
		return x.Item
	}
	return nil
}

type DeleteActiveCookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipeId      int64                  `protobuf:"varint,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteActiveCookingRequest) Reset() {
	*x = DeleteActiveCookingRequest{}
	mi := &file_api_aicook_v1_cooking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteActiveCookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteActiveCookingRequest) ProtoMessage() {}

func (x *DeleteActiveCookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_cooking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteActiveCookingRequest.ProtoReflect.Descriptor instead.
func (*DeleteActiveCookingRequest) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_cooking_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteActiveCookingRequest) GetRecipeId() int64 {
	if x != nil {
		return x.RecipeId
	}
	return 0
}

type DeleteActiveCookingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteActiveCookingReply) Reset() {
	*x = DeleteActiveCookingReply{}
	mi := &file_api_aicook_v1_cooking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteActiveCookingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteActiveCookingReply) ProtoMessage() {}

func (x *DeleteActiveCookingReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_cooking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteActiveCookingReply.ProtoReflect.Descriptor instead.
func (*DeleteActiveCookingReply) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_cooking_proto_rawDescGZIP(), []int{6}
}

var File_api_aicook_v1_cooking_proto protoreflect.FileDescriptor

const file_api_aicook_v1_cooking_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/aicook/v1/cooking.proto\x12\taicook.v1\x1a\x1cgoogle/api/annotations.proto\"\x1a\n" +
	"\x18ListActiveCookingRequest\"H\n" +
	"\x16ListActiveCookingReply\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.aicook.v1.ActiveCookingR\x05items\"\xd0\x02\n" +
	"\rActiveCooking\x12\x1b\n" +
	"\trecipe_id\x18\x01 \x01(\x03R\brecipeId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12&\n" +
	"\x0fcover_image_url\x18\x03 \x01(\tR\rcoverImageUrl\x12\x1d\n" +
	"\n" +
	"step_index\x18\x04 \x01(\x05R\tstepIndex\x12\x1f\n" +
	"\vtotal_steps\x18\x05 \x01(\x05R\n" +
	"totalSteps\x12.\n" +
	"\x13timer_total_seconds\x18\x06 \x01(\x05R\x11timerTotalSeconds\x12+\n" +
	"\x11remaining_seconds\x18\a \x01(\x05R\x10remainingSeconds\x12\"\n" +
	"\rupdated_at_ms\x18\b \x01(\x03R\vupdatedAtMs\x12#\n" +
	"\rtimer_running\x18\t \x01(\bR\ftimerRunning\"\x8e\x02\n" +
	"\x1aUpsertActiveCookingRequest\x12\x1b\n" +
	"\trecipe_id\x18\x01 \x01(\x03R\brecipeId\x12\x1d\n" +
	"\n" +
	"step_index\x18\x02 \x01(\x05R\tstepIndex\x12\x1f\n" +
	"\vtotal_steps\x18\x03 \x01(\x05R\n" +
	"totalSteps\x12.\n" +
	"\x13timer_total_seconds\x18\x04 \x01(\x05R\x11timerTotalSeconds\x12-\n" +
	"\x13timer_started_at_ms\x18\x05 \x01(\x03R\x10timerStartedAtMs\x124\n" +
	"\x16timer_paused_remaining\x18\x06 \x01(\x05R\x14timerPausedRemaining\"H\n" +
	"\x18UpsertActiveCookingReply\x12,\n" +
	"\x04item\x18\x01 \x01(\v2\x18.aicook.v1.ActiveCookingR\x04item\"9\n" +
	"\x1aDeleteActiveCookingRequest\x12\x1b\n" +
	"\trecipe_id\x18\x01 \x01(\x03R\brecipeId\"\x1a\n" +
	"\x18DeleteActiveCookingReply2\xb0\x03\n" +
	"\x0eCookingService\x12{\n" +
	"\x11ListActiveCooking\x12#.aicook.v1.ListActiveCookingRequest\x1a!.aicook.v1.ListActiveCookingReply\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/cooking/active\x12\x90\x01\n" +
	"\x13UpsertActiveCooking\x12%.aicook.v1.UpsertActiveCookingRequest\x1a#.aicook.v1.UpsertActiveCookingReply\"-\x82\xd3\xe4\x93\x02':\x01*\x1a\"/api/v1/cooking/active/{recipe_id}\x12\x8d\x01\n" +
	"\x13DeleteActiveCooking\x12%.aicook.v1.DeleteActiveCookingRequest\x1a#.aicook.v1.DeleteActiveCookingReply\"*\x82\xd3\xe4\x93\x02$*\"/api/v1/cooking/active/{recipe_id}B7Z5github.com/chengjiang/aicook/backend/api/aicook/v1;v1b\x06proto3"

var (
	file_api_aicook_v1_cooking_proto_rawDescOnce sync.Once
	file_api_aicook_v1_cooking_proto_rawDescData []byte
)

func file_api_aicook_v1_cooking_proto_rawDescGZIP() []byte {
	file_api_aicook_v1_cooking_proto_rawDescOnce.Do(func() {
		file_api_aicook_v1_cooking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_aicook_v1_cooking_proto_rawDesc), len(file_api_aicook_v1_cooking_proto_rawDesc)))
	})
	return file_api_aicook_v1_cooking_proto_rawDescData
}

var file_api_aicook_v1_cooking_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_aicook_v1_cooking_proto_goTypes = []any{
	(*ListActiveCookingRequest)(nil),   // 0: aicook.v1.ListActiveCookingRequest
	(*ListActiveCookingReply)(nil),     // 1: aicook.v1.ListActiveCookingReply
	(*ActiveCooking)(nil),              // 2: aicook.v1.ActiveCooking
	(*UpsertActiveCookingRequest)(nil), // 3: aicook.v1.UpsertActiveCookingRequest
	(*UpsertActiveCookingReply)(nil),   // 4: aicook.v1.UpsertActiveCookingReply
	(*DeleteActiveCookingRequest)(nil), // 5: aicook.v1.DeleteActiveCookingRequest
	(*DeleteActiveCookingReply)(nil),   // 6: aicook.v1.DeleteActiveCookingReply
}
var file_api_aicook_v1_cooking_proto_depIdxs = []int32{
	2, // 0: aicook.v1.ListActiveCookingReply.items:type_name -> aicook.v1.ActiveCooking
	2, // 1: aicook.v1.UpsertActiveCookingReply.item:type_name -> aicook.v1.ActiveCooking
	0, // 2: aicook.v1.CookingService.ListActiveCooking:input_type -> aicook.v1.ListActiveCookingRequest
	3, // 3: aicook.v1.CookingService.UpsertActiveCooking:input_type -> aicook.v1.UpsertActiveCookingRequest
	5, // 4: aicook.v1.CookingService.DeleteActiveCooking:input_type -> aicook.v1.DeleteActiveCookingRequest
	1, // 5: aicook.v1.CookingService.ListActiveCooking:output_type -> aicook.v1.ListActiveCookingReply
	4, // 6: aicook.v1.CookingService.UpsertActiveCooking:output_type -> aicook.v1.UpsertActiveCookingReply
	6, // 7: aicook.v1.CookingService.DeleteActiveCooking:output_type -> aicook.v1.DeleteActiveCookingReply
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_aicook_v1_cooking_proto_init() }
func file_api_aicook_v1_cooking_proto_init() {
	if File_api_aicook_v1_cooking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_aicook_v1_cooking_proto_rawDesc), len(file_api_aicook_v1_cooking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_aicook_v1_cooking_proto_goTypes,
		DependencyIndexes: file_api_aicook_v1_cooking_proto_depIdxs,
		MessageInfos:      file_api_aicook_v1_cooking_proto_msgTypes,
	}.Build()
	File_api_aicook_v1_cooking_proto = out.File
	file_api_aicook_v1_cooking_proto_goTypes = nil
	file_api_aicook_v1_cooking_proto_depIdxs = nil
}
