// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: api/aicook/v1/cooking.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CookingService_ListActiveCooking_FullMethodName   = "/aicook.v1.CookingService/ListActiveCooking"
	CookingService_UpsertActiveCooking_FullMethodName = "/aicook.v1.CookingService/UpsertActiveCooking"
	CookingService_DeleteActiveCooking_FullMethodName = "/aicook.v1.CookingService/DeleteActiveCooking"
)

// CookingServiceClient is the client API for CookingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CookingServiceClient interface {
	ListActiveCooking(ctx context.Context, in *ListActiveCookingRequest, opts ...grpc.CallOption) (*ListActiveCookingReply, error)
	UpsertActiveCooking(ctx context.Context, in *UpsertActiveCookingRequest, opts ...grpc.CallOption) (*UpsertActiveCookingReply, error)
	DeleteActiveCooking(ctx context.Context, in *DeleteActiveCookingRequest, opts ...grpc.CallOption) (*DeleteActiveCookingReply, error)
}

type cookingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCookingServiceClient(cc grpc.ClientConnInterface) CookingServiceClient {
	return &cookingServiceClient{cc}
}

func (c *cookingServiceClient) ListActiveCooking(ctx context.Context, in *ListActiveCookingRequest, opts ...grpc.CallOption) (*ListActiveCookingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListActiveCookingReply)
	err := c.cc.Invoke(ctx, CookingService_ListActiveCooking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cookingServiceClient) UpsertActiveCooking(ctx context.Context, in *UpsertActiveCookingRequest, opts ...grpc.CallOption) (*UpsertActiveCookingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertActiveCookingReply)
	err := c.cc.Invoke(ctx, CookingService_UpsertActiveCooking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cookingServiceClient) DeleteActiveCooking(ctx context.Context, in *DeleteActiveCookingRequest, opts ...grpc.CallOption) (*DeleteActiveCookingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteActiveCookingReply)
	err := c.cc.Invoke(ctx, CookingService_DeleteActiveCooking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CookingServiceServer is the server API for CookingService service.
// All implementations should embed UnimplementedCookingServiceServer
// for forward compatibility.
type CookingServiceServer interface {
	ListActiveCooking(context.Context, *ListActiveCookingRequest) (*ListActiveCookingReply, error)
	UpsertActiveCooking(context.Context, *UpsertActiveCookingRequest) (*UpsertActiveCookingReply, error)
	DeleteActiveCooking(context.Context, *DeleteActiveCookingRequest) (*DeleteActiveCookingReply, error)
}

// UnimplementedCookingServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCookingServiceServer struct{}

func (UnimplementedCookingServiceServer) ListActiveCooking(context.Context, *ListActiveCookingRequest) (*ListActiveCookingReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListActiveCooking not implemented")
}
func (UnimplementedCookingServiceServer) UpsertActiveCooking(context.Context, *UpsertActiveCookingRequest) (*UpsertActiveCookingReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertActiveCooking not implemented")
}
func (UnimplementedCookingServiceServer) DeleteActiveCooking(context.Context, *DeleteActiveCookingRequest) (*DeleteActiveCookingReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteActiveCooking not implemented")
}
func (UnimplementedCookingServiceServer) testEmbeddedByValue() {}

// UnsafeCookingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CookingServiceServer will
// result in compilation errors.
type UnsafeCookingServiceServer interface {
	mustEmbedUnimplementedCookingServiceServer()
}

func RegisterCookingServiceServer(s grpc.ServiceRegistrar, srv CookingServiceServer) {
	// If the following call panics, it indicates UnimplementedCookingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CookingService_ServiceDesc, srv)
}

func _CookingService_ListActiveCooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListActiveCookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CookingServiceServer).ListActiveCooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CookingService_ListActiveCooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CookingServiceServer).ListActiveCooking(ctx, req.(*ListActiveCookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CookingService_UpsertActiveCooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertActiveCookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CookingServiceServer).UpsertActiveCooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CookingService_UpsertActiveCooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CookingServiceServer).UpsertActiveCooking(ctx, req.(*UpsertActiveCookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CookingService_DeleteActiveCooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteActiveCookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CookingServiceServer).DeleteActiveCooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CookingService_DeleteActiveCooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CookingServiceServer).DeleteActiveCooking(ctx, req.(*DeleteActiveCookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CookingService_ServiceDesc is the grpc.ServiceDesc for CookingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CookingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aicook.v1.CookingService",
	HandlerType: (*CookingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListActiveCooking",
			Handler:    _CookingService_ListActiveCooking_Handler,
		},
		{
			MethodName: "UpsertActiveCooking",
			Handler:    _CookingService_UpsertActiveCooking_Handler,
		},
		{
			MethodName: "DeleteActiveCooking",
			Handler:    _CookingService_DeleteActiveCooking_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/aicook/v1/cooking.proto",
}
