// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             (unknown)
// source: api/aicook/v1/feedback.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationFeedbackServiceCreateFeedback = "/aicook.v1.FeedbackService/CreateFeedback"
const OperationFeedbackServiceListFeedbacks = "/aicook.v1.FeedbackService/ListFeedbacks"

type FeedbackServiceHTTPServer interface {
	// CreateFeedback CreateFeedback 提交一条反馈。
	CreateFeedback(context.Context, *CreateFeedbackRequest) (*CreateFeedbackReply, error)
	// ListFeedbacks ListFeedbacks 拉取当前用户自己的反馈列表，按 id 倒序游标分页。
	ListFeedbacks(context.Context, *ListFeedbacksRequest) (*ListFeedbacksReply, error)
}

func RegisterFeedbackServiceHTTPServer(s *http.Server, srv FeedbackServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/feedbacks", _FeedbackService_CreateFeedback0_HTTP_Handler(srv))
	r.GET("/api/v1/feedbacks", _FeedbackService_ListFeedbacks0_HTTP_Handler(srv))
}

func _FeedbackService_CreateFeedback0_HTTP_Handler(srv FeedbackServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateFeedbackRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFeedbackServiceCreateFeedback)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateFeedback(ctx, req.(*CreateFeedbackRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateFeedbackReply)
		return ctx.Result(200, reply)
	}
}

func _FeedbackService_ListFeedbacks0_HTTP_Handler(srv FeedbackServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListFeedbacksRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationFeedbackServiceListFeedbacks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListFeedbacks(ctx, req.(*ListFeedbacksRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListFeedbacksReply)
		return ctx.Result(200, reply)
	}
}

type FeedbackServiceHTTPClient interface {
	CreateFeedback(ctx context.Context, req *CreateFeedbackRequest, opts ...http.CallOption) (rsp *CreateFeedbackReply, err error)
	ListFeedbacks(ctx context.Context, req *ListFeedbacksRequest, opts ...http.CallOption) (rsp *ListFeedbacksReply, err error)
}

type FeedbackServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewFeedbackServiceHTTPClient(client *http.Client) FeedbackServiceHTTPClient {
	return &FeedbackServiceHTTPClientImpl{client}
}

func (c *FeedbackServiceHTTPClientImpl) CreateFeedback(ctx context.Context, in *CreateFeedbackRequest, opts ...http.CallOption) (*CreateFeedbackReply, error) {
	var out CreateFeedbackReply
	pattern := "/api/v1/feedbacks"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationFeedbackServiceCreateFeedback))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *FeedbackServiceHTTPClientImpl) ListFeedbacks(ctx context.Context, in *ListFeedbacksRequest, opts ...http.CallOption) (*ListFeedbacksReply, error) {
	var out ListFeedbacksReply
	pattern := "/api/v1/feedbacks"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationFeedbackServiceListFeedbacks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
