// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/aicook/v1/household.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HouseholdService_CreateHousehold_FullMethodName       = "/aicook.v1.HouseholdService/CreateHousehold"
	HouseholdService_CreateShareCode_FullMethodName       = "/aicook.v1.HouseholdService/CreateShareCode"
	HouseholdService_GetKitchenByShareCode_FullMethodName = "/aicook.v1.HouseholdService/GetKitchenByShareCode"
	HouseholdService_ImportSharedRecipes_FullMethodName   = "/aicook.v1.HouseholdService/ImportSharedRecipes"
	HouseholdService_ListKitchenTags_FullMethodName       = "/aicook.v1.HouseholdService/ListKitchenTags"
	HouseholdService_CreateKitchenTag_FullMethodName      = "/aicook.v1.HouseholdService/CreateKitchenTag"
)

// HouseholdServiceClient is the client API for HouseholdService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HouseholdServiceClient interface {
	CreateHousehold(ctx context.Context, in *CreateHouseholdRequest, opts ...grpc.CallOption) (*CreateHouseholdReply, error)
	CreateShareCode(ctx context.Context, in *CreateShareCodeRequest, opts ...grpc.CallOption) (*CreateShareCodeReply, error)
	GetKitchenByShareCode(ctx context.Context, in *GetKitchenByShareCodeRequest, opts ...grpc.CallOption) (*GetKitchenByShareCodeReply, error)
	ImportSharedRecipes(ctx context.Context, in *ImportSharedRecipesRequest, opts ...grpc.CallOption) (*ImportSharedRecipesReply, error)
	ListKitchenTags(ctx context.Context, in *ListKitchenTagsRequest, opts ...grpc.CallOption) (*ListKitchenTagsReply, error)
	CreateKitchenTag(ctx context.Context, in *CreateKitchenTagRequest, opts ...grpc.CallOption) (*CreateKitchenTagReply, error)
}

type householdServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHouseholdServiceClient(cc grpc.ClientConnInterface) HouseholdServiceClient {
	return &householdServiceClient{cc}
}

func (c *householdServiceClient) CreateHousehold(ctx context.Context, in *CreateHouseholdRequest, opts ...grpc.CallOption) (*CreateHouseholdReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateHouseholdReply)
	err := c.cc.Invoke(ctx, HouseholdService_CreateHousehold_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *householdServiceClient) CreateShareCode(ctx context.Context, in *CreateShareCodeRequest, opts ...grpc.CallOption) (*CreateShareCodeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateShareCodeReply)
	err := c.cc.Invoke(ctx, HouseholdService_CreateShareCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *householdServiceClient) GetKitchenByShareCode(ctx context.Context, in *GetKitchenByShareCodeRequest, opts ...grpc.CallOption) (*GetKitchenByShareCodeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKitchenByShareCodeReply)
	err := c.cc.Invoke(ctx, HouseholdService_GetKitchenByShareCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *householdServiceClient) ImportSharedRecipes(ctx context.Context, in *ImportSharedRecipesRequest, opts ...grpc.CallOption) (*ImportSharedRecipesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportSharedRecipesReply)
	err := c.cc.Invoke(ctx, HouseholdService_ImportSharedRecipes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *householdServiceClient) ListKitchenTags(ctx context.Context, in *ListKitchenTagsRequest, opts ...grpc.CallOption) (*ListKitchenTagsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListKitchenTagsReply)
	err := c.cc.Invoke(ctx, HouseholdService_ListKitchenTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *householdServiceClient) CreateKitchenTag(ctx context.Context, in *CreateKitchenTagRequest, opts ...grpc.CallOption) (*CreateKitchenTagReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateKitchenTagReply)
	err := c.cc.Invoke(ctx, HouseholdService_CreateKitchenTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HouseholdServiceServer is the server API for HouseholdService service.
// All implementations should embed UnimplementedHouseholdServiceServer
// for forward compatibility.
type HouseholdServiceServer interface {
	CreateHousehold(context.Context, *CreateHouseholdRequest) (*CreateHouseholdReply, error)
	CreateShareCode(context.Context, *CreateShareCodeRequest) (*CreateShareCodeReply, error)
	GetKitchenByShareCode(context.Context, *GetKitchenByShareCodeRequest) (*GetKitchenByShareCodeReply, error)
	ImportSharedRecipes(context.Context, *ImportSharedRecipesRequest) (*ImportSharedRecipesReply, error)
	ListKitchenTags(context.Context, *ListKitchenTagsRequest) (*ListKitchenTagsReply, error)
	CreateKitchenTag(context.Context, *CreateKitchenTagRequest) (*CreateKitchenTagReply, error)
}

// UnimplementedHouseholdServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHouseholdServiceServer struct{}

func (UnimplementedHouseholdServiceServer) CreateHousehold(context.Context, *CreateHouseholdRequest) (*CreateHouseholdReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateHousehold not implemented")
}
func (UnimplementedHouseholdServiceServer) CreateShareCode(context.Context, *CreateShareCodeRequest) (*CreateShareCodeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateShareCode not implemented")
}
func (UnimplementedHouseholdServiceServer) GetKitchenByShareCode(context.Context, *GetKitchenByShareCodeRequest) (*GetKitchenByShareCodeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKitchenByShareCode not implemented")
}
func (UnimplementedHouseholdServiceServer) ImportSharedRecipes(context.Context, *ImportSharedRecipesRequest) (*ImportSharedRecipesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportSharedRecipes not implemented")
}
func (UnimplementedHouseholdServiceServer) ListKitchenTags(context.Context, *ListKitchenTagsRequest) (*ListKitchenTagsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListKitchenTags not implemented")
}
func (UnimplementedHouseholdServiceServer) CreateKitchenTag(context.Context, *CreateKitchenTagRequest) (*CreateKitchenTagReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateKitchenTag not implemented")
}
func (UnimplementedHouseholdServiceServer) testEmbeddedByValue() {}

// UnsafeHouseholdServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HouseholdServiceServer will
// result in compilation errors.
type UnsafeHouseholdServiceServer interface {
	mustEmbedUnimplementedHouseholdServiceServer()
}

func RegisterHouseholdServiceServer(s grpc.ServiceRegistrar, srv HouseholdServiceServer) {
	// If the following call pancis, it indicates UnimplementedHouseholdServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HouseholdService_ServiceDesc, srv)
}

func _HouseholdService_CreateHousehold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHouseholdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HouseholdServiceServer).CreateHousehold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HouseholdService_CreateHousehold_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HouseholdServiceServer).CreateHousehold(ctx, req.(*CreateHouseholdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HouseholdService_CreateShareCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShareCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HouseholdServiceServer).CreateShareCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HouseholdService_CreateShareCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HouseholdServiceServer).CreateShareCode(ctx, req.(*CreateShareCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HouseholdService_GetKitchenByShareCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKitchenByShareCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HouseholdServiceServer).GetKitchenByShareCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HouseholdService_GetKitchenByShareCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HouseholdServiceServer).GetKitchenByShareCode(ctx, req.(*GetKitchenByShareCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HouseholdService_ImportSharedRecipes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportSharedRecipesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HouseholdServiceServer).ImportSharedRecipes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HouseholdService_ImportSharedRecipes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HouseholdServiceServer).ImportSharedRecipes(ctx, req.(*ImportSharedRecipesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HouseholdService_ListKitchenTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKitchenTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HouseholdServiceServer).ListKitchenTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HouseholdService_ListKitchenTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HouseholdServiceServer).ListKitchenTags(ctx, req.(*ListKitchenTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HouseholdService_CreateKitchenTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKitchenTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HouseholdServiceServer).CreateKitchenTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HouseholdService_CreateKitchenTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HouseholdServiceServer).CreateKitchenTag(ctx, req.(*CreateKitchenTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HouseholdService_ServiceDesc is the grpc.ServiceDesc for HouseholdService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HouseholdService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aicook.v1.HouseholdService",
	HandlerType: (*HouseholdServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateHousehold",
			Handler:    _HouseholdService_CreateHousehold_Handler,
		},
		{
			MethodName: "CreateShareCode",
			Handler:    _HouseholdService_CreateShareCode_Handler,
		},
		{
			MethodName: "GetKitchenByShareCode",
			Handler:    _HouseholdService_GetKitchenByShareCode_Handler,
		},
		{
			MethodName: "ImportSharedRecipes",
			Handler:    _HouseholdService_ImportSharedRecipes_Handler,
		},
		{
			MethodName: "ListKitchenTags",
			Handler:    _HouseholdService_ListKitchenTags_Handler,
		},
		{
			MethodName: "CreateKitchenTag",
			Handler:    _HouseholdService_CreateKitchenTag_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/aicook/v1/household.proto",
}
