// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: api/aicook/v1/household.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationHouseholdServiceAddHouseholdMember = "/aicook.v1.HouseholdService/AddHouseholdMember"
const OperationHouseholdServiceCreateHousehold = "/aicook.v1.HouseholdService/CreateHousehold"
const OperationHouseholdServiceCreateKitchenTag = "/aicook.v1.HouseholdService/CreateKitchenTag"
const OperationHouseholdServiceCreateShareCode = "/aicook.v1.HouseholdService/CreateShareCode"
const OperationHouseholdServiceDeleteKitchenTag = "/aicook.v1.HouseholdService/DeleteKitchenTag"
const OperationHouseholdServiceGetHouseholdPreferences = "/aicook.v1.HouseholdService/GetHouseholdPreferences"
const OperationHouseholdServiceGetKitchenByShareCode = "/aicook.v1.HouseholdService/GetKitchenByShareCode"
const OperationHouseholdServiceGetMemberPreferences = "/aicook.v1.HouseholdService/GetMemberPreferences"
const OperationHouseholdServiceImportSharedRecipes = "/aicook.v1.HouseholdService/ImportSharedRecipes"
const OperationHouseholdServiceListHouseholdMembers = "/aicook.v1.HouseholdService/ListHouseholdMembers"
const OperationHouseholdServiceListKitchenTags = "/aicook.v1.HouseholdService/ListKitchenTags"
const OperationHouseholdServiceRemoveHouseholdMember = "/aicook.v1.HouseholdService/RemoveHouseholdMember"
const OperationHouseholdServiceUpdateHouseholdPreferences = "/aicook.v1.HouseholdService/UpdateHouseholdPreferences"
const OperationHouseholdServiceUpdateKitchenTag = "/aicook.v1.HouseholdService/UpdateKitchenTag"
const OperationHouseholdServiceUpdateMemberPreferences = "/aicook.v1.HouseholdService/UpdateMemberPreferences"

type HouseholdServiceHTTPServer interface {
	// AddHouseholdMember AddHouseholdMember 新增「虚拟成员」（user_id=0），用于家庭里没微信账号的家人。
	// 权限：仅当前 actor 是 household owner。
	AddHouseholdMember(context.Context, *AddHouseholdMemberRequest) (*AddHouseholdMemberReply, error)
	CreateHousehold(context.Context, *CreateHouseholdRequest) (*CreateHouseholdReply, error)
	CreateKitchenTag(context.Context, *CreateKitchenTagRequest) (*CreateKitchenTagReply, error)
	CreateShareCode(context.Context, *CreateShareCodeRequest) (*CreateShareCodeReply, error)
	DeleteKitchenTag(context.Context, *DeleteKitchenTagRequest) (*DeleteKitchenTagReply, error)
	GetHouseholdPreferences(context.Context, *GetHouseholdPreferencesRequest) (*GetHouseholdPreferencesReply, error)
	GetKitchenByShareCode(context.Context, *GetKitchenByShareCodeRequest) (*GetKitchenByShareCodeReply, error)
	// GetMemberPreferences GetMemberPreferences 读单个成员的个人口味偏好。
	// 权限：任意家庭成员都可读（用于显示）。
	GetMemberPreferences(context.Context, *GetMemberPreferencesRequest) (*GetMemberPreferencesReply, error)
	ImportSharedRecipes(context.Context, *ImportSharedRecipesRequest) (*ImportSharedRecipesReply, error)
	// ListHouseholdMembers ListHouseholdMembers 返回指定家庭的成员列表（含基本信息 + 口味偏好）。
	ListHouseholdMembers(context.Context, *ListHouseholdMembersRequest) (*ListHouseholdMembersReply, error)
	ListKitchenTags(context.Context, *ListKitchenTagsRequest) (*ListKitchenTagsReply, error)
	// RemoveHouseholdMember RemoveHouseholdMember 从家庭里移除成员（软删）。
	// 权限：仅 owner；不允许移除 owner 本人。
	RemoveHouseholdMember(context.Context, *RemoveHouseholdMemberRequest) (*RemoveHouseholdMemberReply, error)
	UpdateHouseholdPreferences(context.Context, *UpdateHouseholdPreferencesRequest) (*UpdateHouseholdPreferencesReply, error)
	UpdateKitchenTag(context.Context, *UpdateKitchenTagRequest) (*UpdateKitchenTagReply, error)
	// UpdateMemberPreferences UpdateMemberPreferences 改单个成员的个人口味偏好。
	// 权限：owner 或本人（member.user_id == actor.user_id）。
	UpdateMemberPreferences(context.Context, *UpdateMemberPreferencesRequest) (*UpdateMemberPreferencesReply, error)
}

func RegisterHouseholdServiceHTTPServer(s *http.Server, srv HouseholdServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/households", _HouseholdService_CreateHousehold0_HTTP_Handler(srv))
	r.POST("/api/v1/households/share-code", _HouseholdService_CreateShareCode0_HTTP_Handler(srv))
	r.GET("/api/v1/households/share/{share_code}", _HouseholdService_GetKitchenByShareCode0_HTTP_Handler(srv))
	r.POST("/api/v1/households/share/{share_code}:import", _HouseholdService_ImportSharedRecipes0_HTTP_Handler(srv))
	r.GET("/api/v1/kitchen-tags", _HouseholdService_ListKitchenTags0_HTTP_Handler(srv))
	r.POST("/api/v1/kitchen-tags", _HouseholdService_CreateKitchenTag0_HTTP_Handler(srv))
	r.PATCH("/api/v1/kitchen-tags/{id}", _HouseholdService_UpdateKitchenTag0_HTTP_Handler(srv))
	r.DELETE("/api/v1/kitchen-tags/{id}", _HouseholdService_DeleteKitchenTag0_HTTP_Handler(srv))
	r.GET("/api/v1/households/current/preferences", _HouseholdService_GetHouseholdPreferences0_HTTP_Handler(srv))
	r.PUT("/api/v1/households/current/preferences", _HouseholdService_UpdateHouseholdPreferences0_HTTP_Handler(srv))
	r.GET("/api/v1/households/{household_id}/members", _HouseholdService_ListHouseholdMembers0_HTTP_Handler(srv))
	r.POST("/api/v1/households/{household_id}/members", _HouseholdService_AddHouseholdMember0_HTTP_Handler(srv))
	r.DELETE("/api/v1/households/members/{member_id}", _HouseholdService_RemoveHouseholdMember0_HTTP_Handler(srv))
	r.GET("/api/v1/households/members/{member_id}/preferences", _HouseholdService_GetMemberPreferences0_HTTP_Handler(srv))
	r.PUT("/api/v1/households/members/{member_id}/preferences", _HouseholdService_UpdateMemberPreferences0_HTTP_Handler(srv))
}

func _HouseholdService_CreateHousehold0_HTTP_Handler(srv HouseholdServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateHouseholdRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHouseholdServiceCreateHousehold)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateHousehold(ctx, req.(*CreateHouseholdRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateHouseholdReply)
		return ctx.Result(200, reply)
	}
}

func _HouseholdService_CreateShareCode0_HTTP_Handler(srv HouseholdServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateShareCodeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHouseholdServiceCreateShareCode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateShareCode(ctx, req.(*CreateShareCodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateShareCodeReply)
		return ctx.Result(200, reply)
	}
}

func _HouseholdService_GetKitchenByShareCode0_HTTP_Handler(srv HouseholdServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetKitchenByShareCodeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHouseholdServiceGetKitchenByShareCode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetKitchenByShareCode(ctx, req.(*GetKitchenByShareCodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetKitchenByShareCodeReply)
		return ctx.Result(200, reply)
	}
}

func _HouseholdService_ImportSharedRecipes0_HTTP_Handler(srv HouseholdServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ImportSharedRecipesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHouseholdServiceImportSharedRecipes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ImportSharedRecipes(ctx, req.(*ImportSharedRecipesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ImportSharedRecipesReply)
		return ctx.Result(200, reply)
	}
}

func _HouseholdService_ListKitchenTags0_HTTP_Handler(srv HouseholdServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListKitchenTagsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHouseholdServiceListKitchenTags)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListKitchenTags(ctx, req.(*ListKitchenTagsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListKitchenTagsReply)
		return ctx.Result(200, reply)
	}
}

func _HouseholdService_CreateKitchenTag0_HTTP_Handler(srv HouseholdServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateKitchenTagRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHouseholdServiceCreateKitchenTag)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateKitchenTag(ctx, req.(*CreateKitchenTagRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateKitchenTagReply)
		return ctx.Result(200, reply)
	}
}

func _HouseholdService_UpdateKitchenTag0_HTTP_Handler(srv HouseholdServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateKitchenTagRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHouseholdServiceUpdateKitchenTag)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateKitchenTag(ctx, req.(*UpdateKitchenTagRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateKitchenTagReply)
		return ctx.Result(200, reply)
	}
}

func _HouseholdService_DeleteKitchenTag0_HTTP_Handler(srv HouseholdServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteKitchenTagRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHouseholdServiceDeleteKitchenTag)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteKitchenTag(ctx, req.(*DeleteKitchenTagRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteKitchenTagReply)
		return ctx.Result(200, reply)
	}
}

func _HouseholdService_GetHouseholdPreferences0_HTTP_Handler(srv HouseholdServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetHouseholdPreferencesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHouseholdServiceGetHouseholdPreferences)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetHouseholdPreferences(ctx, req.(*GetHouseholdPreferencesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetHouseholdPreferencesReply)
		return ctx.Result(200, reply)
	}
}

func _HouseholdService_UpdateHouseholdPreferences0_HTTP_Handler(srv HouseholdServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateHouseholdPreferencesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHouseholdServiceUpdateHouseholdPreferences)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateHouseholdPreferences(ctx, req.(*UpdateHouseholdPreferencesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateHouseholdPreferencesReply)
		return ctx.Result(200, reply)
	}
}

func _HouseholdService_ListHouseholdMembers0_HTTP_Handler(srv HouseholdServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListHouseholdMembersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHouseholdServiceListHouseholdMembers)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListHouseholdMembers(ctx, req.(*ListHouseholdMembersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListHouseholdMembersReply)
		return ctx.Result(200, reply)
	}
}

func _HouseholdService_AddHouseholdMember0_HTTP_Handler(srv HouseholdServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddHouseholdMemberRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHouseholdServiceAddHouseholdMember)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddHouseholdMember(ctx, req.(*AddHouseholdMemberRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddHouseholdMemberReply)
		return ctx.Result(200, reply)
	}
}

func _HouseholdService_RemoveHouseholdMember0_HTTP_Handler(srv HouseholdServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RemoveHouseholdMemberRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHouseholdServiceRemoveHouseholdMember)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RemoveHouseholdMember(ctx, req.(*RemoveHouseholdMemberRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RemoveHouseholdMemberReply)
		return ctx.Result(200, reply)
	}
}

func _HouseholdService_GetMemberPreferences0_HTTP_Handler(srv HouseholdServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMemberPreferencesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHouseholdServiceGetMemberPreferences)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMemberPreferences(ctx, req.(*GetMemberPreferencesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMemberPreferencesReply)
		return ctx.Result(200, reply)
	}
}

func _HouseholdService_UpdateMemberPreferences0_HTTP_Handler(srv HouseholdServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateMemberPreferencesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHouseholdServiceUpdateMemberPreferences)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateMemberPreferences(ctx, req.(*UpdateMemberPreferencesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateMemberPreferencesReply)
		return ctx.Result(200, reply)
	}
}

type HouseholdServiceHTTPClient interface {
	// AddHouseholdMember AddHouseholdMember 新增「虚拟成员」（user_id=0），用于家庭里没微信账号的家人。
	// 权限：仅当前 actor 是 household owner。
	AddHouseholdMember(ctx context.Context, req *AddHouseholdMemberRequest, opts ...http.CallOption) (rsp *AddHouseholdMemberReply, err error)
	CreateHousehold(ctx context.Context, req *CreateHouseholdRequest, opts ...http.CallOption) (rsp *CreateHouseholdReply, err error)
	CreateKitchenTag(ctx context.Context, req *CreateKitchenTagRequest, opts ...http.CallOption) (rsp *CreateKitchenTagReply, err error)
	CreateShareCode(ctx context.Context, req *CreateShareCodeRequest, opts ...http.CallOption) (rsp *CreateShareCodeReply, err error)
	DeleteKitchenTag(ctx context.Context, req *DeleteKitchenTagRequest, opts ...http.CallOption) (rsp *DeleteKitchenTagReply, err error)
	GetHouseholdPreferences(ctx context.Context, req *GetHouseholdPreferencesRequest, opts ...http.CallOption) (rsp *GetHouseholdPreferencesReply, err error)
	GetKitchenByShareCode(ctx context.Context, req *GetKitchenByShareCodeRequest, opts ...http.CallOption) (rsp *GetKitchenByShareCodeReply, err error)
	// GetMemberPreferences GetMemberPreferences 读单个成员的个人口味偏好。
	// 权限：任意家庭成员都可读（用于显示）。
	GetMemberPreferences(ctx context.Context, req *GetMemberPreferencesRequest, opts ...http.CallOption) (rsp *GetMemberPreferencesReply, err error)
	ImportSharedRecipes(ctx context.Context, req *ImportSharedRecipesRequest, opts ...http.CallOption) (rsp *ImportSharedRecipesReply, err error)
	// ListHouseholdMembers ListHouseholdMembers 返回指定家庭的成员列表（含基本信息 + 口味偏好）。
	ListHouseholdMembers(ctx context.Context, req *ListHouseholdMembersRequest, opts ...http.CallOption) (rsp *ListHouseholdMembersReply, err error)
	ListKitchenTags(ctx context.Context, req *ListKitchenTagsRequest, opts ...http.CallOption) (rsp *ListKitchenTagsReply, err error)
	// RemoveHouseholdMember RemoveHouseholdMember 从家庭里移除成员（软删）。
	// 权限：仅 owner；不允许移除 owner 本人。
	RemoveHouseholdMember(ctx context.Context, req *RemoveHouseholdMemberRequest, opts ...http.CallOption) (rsp *RemoveHouseholdMemberReply, err error)
	UpdateHouseholdPreferences(ctx context.Context, req *UpdateHouseholdPreferencesRequest, opts ...http.CallOption) (rsp *UpdateHouseholdPreferencesReply, err error)
	UpdateKitchenTag(ctx context.Context, req *UpdateKitchenTagRequest, opts ...http.CallOption) (rsp *UpdateKitchenTagReply, err error)
	// UpdateMemberPreferences UpdateMemberPreferences 改单个成员的个人口味偏好。
	// 权限：owner 或本人（member.user_id == actor.user_id）。
	UpdateMemberPreferences(ctx context.Context, req *UpdateMemberPreferencesRequest, opts ...http.CallOption) (rsp *UpdateMemberPreferencesReply, err error)
}

type HouseholdServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewHouseholdServiceHTTPClient(client *http.Client) HouseholdServiceHTTPClient {
	return &HouseholdServiceHTTPClientImpl{client}
}

// AddHouseholdMember AddHouseholdMember 新增「虚拟成员」（user_id=0），用于家庭里没微信账号的家人。
// 权限：仅当前 actor 是 household owner。
func (c *HouseholdServiceHTTPClientImpl) AddHouseholdMember(ctx context.Context, in *AddHouseholdMemberRequest, opts ...http.CallOption) (*AddHouseholdMemberReply, error) {
	var out AddHouseholdMemberReply
	pattern := "/api/v1/households/{household_id}/members"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHouseholdServiceAddHouseholdMember))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HouseholdServiceHTTPClientImpl) CreateHousehold(ctx context.Context, in *CreateHouseholdRequest, opts ...http.CallOption) (*CreateHouseholdReply, error) {
	var out CreateHouseholdReply
	pattern := "/api/v1/households"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHouseholdServiceCreateHousehold))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HouseholdServiceHTTPClientImpl) CreateKitchenTag(ctx context.Context, in *CreateKitchenTagRequest, opts ...http.CallOption) (*CreateKitchenTagReply, error) {
	var out CreateKitchenTagReply
	pattern := "/api/v1/kitchen-tags"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHouseholdServiceCreateKitchenTag))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HouseholdServiceHTTPClientImpl) CreateShareCode(ctx context.Context, in *CreateShareCodeRequest, opts ...http.CallOption) (*CreateShareCodeReply, error) {
	var out CreateShareCodeReply
	pattern := "/api/v1/households/share-code"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHouseholdServiceCreateShareCode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HouseholdServiceHTTPClientImpl) DeleteKitchenTag(ctx context.Context, in *DeleteKitchenTagRequest, opts ...http.CallOption) (*DeleteKitchenTagReply, error) {
	var out DeleteKitchenTagReply
	pattern := "/api/v1/kitchen-tags/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHouseholdServiceDeleteKitchenTag))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HouseholdServiceHTTPClientImpl) GetHouseholdPreferences(ctx context.Context, in *GetHouseholdPreferencesRequest, opts ...http.CallOption) (*GetHouseholdPreferencesReply, error) {
	var out GetHouseholdPreferencesReply
	pattern := "/api/v1/households/current/preferences"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHouseholdServiceGetHouseholdPreferences))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HouseholdServiceHTTPClientImpl) GetKitchenByShareCode(ctx context.Context, in *GetKitchenByShareCodeRequest, opts ...http.CallOption) (*GetKitchenByShareCodeReply, error) {
	var out GetKitchenByShareCodeReply
	pattern := "/api/v1/households/share/{share_code}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHouseholdServiceGetKitchenByShareCode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetMemberPreferences GetMemberPreferences 读单个成员的个人口味偏好。
// 权限：任意家庭成员都可读（用于显示）。
func (c *HouseholdServiceHTTPClientImpl) GetMemberPreferences(ctx context.Context, in *GetMemberPreferencesRequest, opts ...http.CallOption) (*GetMemberPreferencesReply, error) {
	var out GetMemberPreferencesReply
	pattern := "/api/v1/households/members/{member_id}/preferences"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHouseholdServiceGetMemberPreferences))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HouseholdServiceHTTPClientImpl) ImportSharedRecipes(ctx context.Context, in *ImportSharedRecipesRequest, opts ...http.CallOption) (*ImportSharedRecipesReply, error) {
	var out ImportSharedRecipesReply
	pattern := "/api/v1/households/share/{share_code}:import"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHouseholdServiceImportSharedRecipes))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListHouseholdMembers ListHouseholdMembers 返回指定家庭的成员列表（含基本信息 + 口味偏好）。
func (c *HouseholdServiceHTTPClientImpl) ListHouseholdMembers(ctx context.Context, in *ListHouseholdMembersRequest, opts ...http.CallOption) (*ListHouseholdMembersReply, error) {
	var out ListHouseholdMembersReply
	pattern := "/api/v1/households/{household_id}/members"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHouseholdServiceListHouseholdMembers))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HouseholdServiceHTTPClientImpl) ListKitchenTags(ctx context.Context, in *ListKitchenTagsRequest, opts ...http.CallOption) (*ListKitchenTagsReply, error) {
	var out ListKitchenTagsReply
	pattern := "/api/v1/kitchen-tags"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHouseholdServiceListKitchenTags))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RemoveHouseholdMember RemoveHouseholdMember 从家庭里移除成员（软删）。
// 权限：仅 owner；不允许移除 owner 本人。
func (c *HouseholdServiceHTTPClientImpl) RemoveHouseholdMember(ctx context.Context, in *RemoveHouseholdMemberRequest, opts ...http.CallOption) (*RemoveHouseholdMemberReply, error) {
	var out RemoveHouseholdMemberReply
	pattern := "/api/v1/households/members/{member_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHouseholdServiceRemoveHouseholdMember))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HouseholdServiceHTTPClientImpl) UpdateHouseholdPreferences(ctx context.Context, in *UpdateHouseholdPreferencesRequest, opts ...http.CallOption) (*UpdateHouseholdPreferencesReply, error) {
	var out UpdateHouseholdPreferencesReply
	pattern := "/api/v1/households/current/preferences"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHouseholdServiceUpdateHouseholdPreferences))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *HouseholdServiceHTTPClientImpl) UpdateKitchenTag(ctx context.Context, in *UpdateKitchenTagRequest, opts ...http.CallOption) (*UpdateKitchenTagReply, error) {
	var out UpdateKitchenTagReply
	pattern := "/api/v1/kitchen-tags/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHouseholdServiceUpdateKitchenTag))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateMemberPreferences UpdateMemberPreferences 改单个成员的个人口味偏好。
// 权限：owner 或本人（member.user_id == actor.user_id）。
func (c *HouseholdServiceHTTPClientImpl) UpdateMemberPreferences(ctx context.Context, in *UpdateMemberPreferencesRequest, opts ...http.CallOption) (*UpdateMemberPreferencesReply, error) {
	var out UpdateMemberPreferencesReply
	pattern := "/api/v1/households/members/{member_id}/preferences"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHouseholdServiceUpdateMemberPreferences))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
