// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/aicook/v1/import.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateImageRecipeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaAssetIds []int64                `protobuf:"varint,1,rep,packed,name=media_asset_ids,json=mediaAssetIds,proto3" json:"media_asset_ids,omitempty"`
	TitleHint     string                 `protobuf:"bytes,2,opt,name=title_hint,json=titleHint,proto3" json:"title_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateImageRecipeRequest) Reset() {
	*x = CreateImageRecipeRequest{}
	mi := &file_api_aicook_v1_import_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateImageRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateImageRecipeRequest) ProtoMessage() {}

func (x *CreateImageRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_import_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateImageRecipeRequest.ProtoReflect.Descriptor instead.
func (*CreateImageRecipeRequest) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_import_proto_rawDescGZIP(), []int{0}
}

func (x *CreateImageRecipeRequest) GetMediaAssetIds() []int64 {
	if x != nil {
		return x.MediaAssetIds
	}
	return nil
}

func (x *CreateImageRecipeRequest) GetTitleHint() string {
	if x != nil {
		return x.TitleHint
	}
	return ""
}

type CreateImageRecipeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *ImportJob             `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateImageRecipeReply) Reset() {
	*x = CreateImageRecipeReply{}
	mi := &file_api_aicook_v1_import_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateImageRecipeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateImageRecipeReply) ProtoMessage() {}

func (x *CreateImageRecipeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_import_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateImageRecipeReply.ProtoReflect.Descriptor instead.
func (*CreateImageRecipeReply) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_import_proto_rawDescGZIP(), []int{1}
}

func (x *CreateImageRecipeReply) GetJob() *ImportJob {
	if x != nil {
		return x.Job
	}
	return nil
}

type GetImportJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImportJobRequest) Reset() {
	*x = GetImportJobRequest{}
	mi := &file_api_aicook_v1_import_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImportJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImportJobRequest) ProtoMessage() {}

func (x *GetImportJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_import_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImportJobRequest.ProtoReflect.Descriptor instead.
func (*GetImportJobRequest) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_import_proto_rawDescGZIP(), []int{2}
}

func (x *GetImportJobRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetImportJobReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *ImportJob             `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImportJobReply) Reset() {
	*x = GetImportJobReply{}
	mi := &file_api_aicook_v1_import_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImportJobReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImportJobReply) ProtoMessage() {}

func (x *GetImportJobReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_import_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImportJobReply.ProtoReflect.Descriptor instead.
func (*GetImportJobReply) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_import_proto_rawDescGZIP(), []int{3}
}

func (x *GetImportJobReply) GetJob() *ImportJob {
	if x != nil {
		return x.Job
	}
	return nil
}

var File_api_aicook_v1_import_proto protoreflect.FileDescriptor

const file_api_aicook_v1_import_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/aicook/v1/import.proto\x12\taicook.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1aapi/aicook/v1/common.proto\"a\n" +
	"\x18CreateImageRecipeRequest\x12&\n" +
	"\x0fmedia_asset_ids\x18\x01 \x03(\x03R\rmediaAssetIds\x12\x1d\n" +
	"\n" +
	"title_hint\x18\x02 \x01(\tR\ttitleHint\"@\n" +
	"\x16CreateImageRecipeReply\x12&\n" +
	"\x03job\x18\x01 \x01(\v2\x14.aicook.v1.ImportJobR\x03job\"%\n" +
	"\x13GetImportJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\";\n" +
	"\x11GetImportJobReply\x12&\n" +
	"\x03job\x18\x01 \x01(\v2\x14.aicook.v1.ImportJobR\x03job2\x83\x02\n" +
	"\rImportService\x12\x85\x01\n" +
	"\x11CreateImageRecipe\x12#.aicook.v1.CreateImageRecipeRequest\x1a!.aicook.v1.CreateImageRecipeReply\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/imports/image-recipes\x12j\n" +
	"\fGetImportJob\x12\x1e.aicook.v1.GetImportJobRequest\x1a\x1c.aicook.v1.GetImportJobReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/imports/{id}B7Z5github.com/chengjiang/aicook/backend/api/aicook/v1;v1b\x06proto3"

var (
	file_api_aicook_v1_import_proto_rawDescOnce sync.Once
	file_api_aicook_v1_import_proto_rawDescData []byte
)

func file_api_aicook_v1_import_proto_rawDescGZIP() []byte {
	file_api_aicook_v1_import_proto_rawDescOnce.Do(func() {
		file_api_aicook_v1_import_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_aicook_v1_import_proto_rawDesc), len(file_api_aicook_v1_import_proto_rawDesc)))
	})
	return file_api_aicook_v1_import_proto_rawDescData
}

var file_api_aicook_v1_import_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_aicook_v1_import_proto_goTypes = []any{
	(*CreateImageRecipeRequest)(nil), // 0: aicook.v1.CreateImageRecipeRequest
	(*CreateImageRecipeReply)(nil),   // 1: aicook.v1.CreateImageRecipeReply
	(*GetImportJobRequest)(nil),      // 2: aicook.v1.GetImportJobRequest
	(*GetImportJobReply)(nil),        // 3: aicook.v1.GetImportJobReply
	(*ImportJob)(nil),                // 4: aicook.v1.ImportJob
}
var file_api_aicook_v1_import_proto_depIdxs = []int32{
	4, // 0: aicook.v1.CreateImageRecipeReply.job:type_name -> aicook.v1.ImportJob
	4, // 1: aicook.v1.GetImportJobReply.job:type_name -> aicook.v1.ImportJob
	0, // 2: aicook.v1.ImportService.CreateImageRecipe:input_type -> aicook.v1.CreateImageRecipeRequest
	2, // 3: aicook.v1.ImportService.GetImportJob:input_type -> aicook.v1.GetImportJobRequest
	1, // 4: aicook.v1.ImportService.CreateImageRecipe:output_type -> aicook.v1.CreateImageRecipeReply
	3, // 5: aicook.v1.ImportService.GetImportJob:output_type -> aicook.v1.GetImportJobReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_aicook_v1_import_proto_init() }
func file_api_aicook_v1_import_proto_init() {
	if File_api_aicook_v1_import_proto != nil {
		return
	}
	file_api_aicook_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_aicook_v1_import_proto_rawDesc), len(file_api_aicook_v1_import_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_aicook_v1_import_proto_goTypes,
		DependencyIndexes: file_api_aicook_v1_import_proto_depIdxs,
		MessageInfos:      file_api_aicook_v1_import_proto_msgTypes,
	}.Build()
	File_api_aicook_v1_import_proto = out.File
	file_api_aicook_v1_import_proto_goTypes = nil
	file_api_aicook_v1_import_proto_depIdxs = nil
}
