// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: api/aicook/v1/import.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationImportServiceCreateImageRecipe = "/aicook.v1.ImportService/CreateImageRecipe"
const OperationImportServiceGetImportJob = "/aicook.v1.ImportService/GetImportJob"

type ImportServiceHTTPServer interface {
	CreateImageRecipe(context.Context, *CreateImageRecipeRequest) (*CreateImageRecipeReply, error)
	GetImportJob(context.Context, *GetImportJobRequest) (*GetImportJobReply, error)
}

func RegisterImportServiceHTTPServer(s *http.Server, srv ImportServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/imports/image-recipes", _ImportService_CreateImageRecipe0_HTTP_Handler(srv))
	r.GET("/api/v1/imports/{id}", _ImportService_GetImportJob0_HTTP_Handler(srv))
}

func _ImportService_CreateImageRecipe0_HTTP_Handler(srv ImportServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateImageRecipeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationImportServiceCreateImageRecipe)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateImageRecipe(ctx, req.(*CreateImageRecipeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateImageRecipeReply)
		return ctx.Result(200, reply)
	}
}

func _ImportService_GetImportJob0_HTTP_Handler(srv ImportServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetImportJobRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationImportServiceGetImportJob)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetImportJob(ctx, req.(*GetImportJobRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetImportJobReply)
		return ctx.Result(200, reply)
	}
}

type ImportServiceHTTPClient interface {
	CreateImageRecipe(ctx context.Context, req *CreateImageRecipeRequest, opts ...http.CallOption) (rsp *CreateImageRecipeReply, err error)
	GetImportJob(ctx context.Context, req *GetImportJobRequest, opts ...http.CallOption) (rsp *GetImportJobReply, err error)
}

type ImportServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewImportServiceHTTPClient(client *http.Client) ImportServiceHTTPClient {
	return &ImportServiceHTTPClientImpl{client}
}

func (c *ImportServiceHTTPClientImpl) CreateImageRecipe(ctx context.Context, in *CreateImageRecipeRequest, opts ...http.CallOption) (*CreateImageRecipeReply, error) {
	var out CreateImageRecipeReply
	pattern := "/api/v1/imports/image-recipes"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationImportServiceCreateImageRecipe))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *ImportServiceHTTPClientImpl) GetImportJob(ctx context.Context, in *GetImportJobRequest, opts ...http.CallOption) (*GetImportJobReply, error) {
	var out GetImportJobReply
	pattern := "/api/v1/imports/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationImportServiceGetImportJob))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
