// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: api/aicook/v1/import.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ImportService_CreateImageRecipe_FullMethodName = "/aicook.v1.ImportService/CreateImageRecipe"
	ImportService_GetImportJob_FullMethodName      = "/aicook.v1.ImportService/GetImportJob"
)

// ImportServiceClient is the client API for ImportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImportServiceClient interface {
	CreateImageRecipe(ctx context.Context, in *CreateImageRecipeRequest, opts ...grpc.CallOption) (*CreateImageRecipeReply, error)
	GetImportJob(ctx context.Context, in *GetImportJobRequest, opts ...grpc.CallOption) (*GetImportJobReply, error)
}

type importServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImportServiceClient(cc grpc.ClientConnInterface) ImportServiceClient {
	return &importServiceClient{cc}
}

func (c *importServiceClient) CreateImageRecipe(ctx context.Context, in *CreateImageRecipeRequest, opts ...grpc.CallOption) (*CreateImageRecipeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateImageRecipeReply)
	err := c.cc.Invoke(ctx, ImportService_CreateImageRecipe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *importServiceClient) GetImportJob(ctx context.Context, in *GetImportJobRequest, opts ...grpc.CallOption) (*GetImportJobReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetImportJobReply)
	err := c.cc.Invoke(ctx, ImportService_GetImportJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImportServiceServer is the server API for ImportService service.
// All implementations should embed UnimplementedImportServiceServer
// for forward compatibility.
type ImportServiceServer interface {
	CreateImageRecipe(context.Context, *CreateImageRecipeRequest) (*CreateImageRecipeReply, error)
	GetImportJob(context.Context, *GetImportJobRequest) (*GetImportJobReply, error)
}

// UnimplementedImportServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImportServiceServer struct{}

func (UnimplementedImportServiceServer) CreateImageRecipe(context.Context, *CreateImageRecipeRequest) (*CreateImageRecipeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateImageRecipe not implemented")
}
func (UnimplementedImportServiceServer) GetImportJob(context.Context, *GetImportJobRequest) (*GetImportJobReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetImportJob not implemented")
}
func (UnimplementedImportServiceServer) testEmbeddedByValue() {}

// UnsafeImportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImportServiceServer will
// result in compilation errors.
type UnsafeImportServiceServer interface {
	mustEmbedUnimplementedImportServiceServer()
}

func RegisterImportServiceServer(s grpc.ServiceRegistrar, srv ImportServiceServer) {
	// If the following call panics, it indicates UnimplementedImportServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImportService_ServiceDesc, srv)
}

func _ImportService_CreateImageRecipe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateImageRecipeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportServiceServer).CreateImageRecipe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportService_CreateImageRecipe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportServiceServer).CreateImageRecipe(ctx, req.(*CreateImageRecipeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImportService_GetImportJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImportJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImportServiceServer).GetImportJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImportService_GetImportJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImportServiceServer).GetImportJob(ctx, req.(*GetImportJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImportService_ServiceDesc is the grpc.ServiceDesc for ImportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aicook.v1.ImportService",
	HandlerType: (*ImportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateImageRecipe",
			Handler:    _ImportService_CreateImageRecipe_Handler,
		},
		{
			MethodName: "GetImportJob",
			Handler:    _ImportService_GetImportJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/aicook/v1/import.proto",
}
