// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: api/aicook/v1/kitchen.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationKitchenServiceCompleteShoppingList = "/aicook.v1.KitchenService/CompleteShoppingList"
const OperationKitchenServiceCreateCookingHistory = "/aicook.v1.KitchenService/CreateCookingHistory"
const OperationKitchenServiceCreateRecipeShare = "/aicook.v1.KitchenService/CreateRecipeShare"
const OperationKitchenServiceGenerateCurrentMealPlan = "/aicook.v1.KitchenService/GenerateCurrentMealPlan"
const OperationKitchenServiceGenerateShoppingList = "/aicook.v1.KitchenService/GenerateShoppingList"
const OperationKitchenServiceGetCurrentMealPlan = "/aicook.v1.KitchenService/GetCurrentMealPlan"
const OperationKitchenServiceGetCurrentShoppingList = "/aicook.v1.KitchenService/GetCurrentShoppingList"
const OperationKitchenServiceImportRecipeShare = "/aicook.v1.KitchenService/ImportRecipeShare"
const OperationKitchenServiceListCookingHistory = "/aicook.v1.KitchenService/ListCookingHistory"
const OperationKitchenServiceListInventoryItems = "/aicook.v1.KitchenService/ListInventoryItems"
const OperationKitchenServiceListInventoryRecommendations = "/aicook.v1.KitchenService/ListInventoryRecommendations"
const OperationKitchenServiceListRecentCookingHistory = "/aicook.v1.KitchenService/ListRecentCookingHistory"
const OperationKitchenServicePatchInventoryItem = "/aicook.v1.KitchenService/PatchInventoryItem"
const OperationKitchenServicePatchShoppingListItem = "/aicook.v1.KitchenService/PatchShoppingListItem"
const OperationKitchenServicePreviewRecipeShare = "/aicook.v1.KitchenService/PreviewRecipeShare"
const OperationKitchenServiceSaveCurrentMealPlan = "/aicook.v1.KitchenService/SaveCurrentMealPlan"
const OperationKitchenServiceUpsertInventoryItems = "/aicook.v1.KitchenService/UpsertInventoryItems"

type KitchenServiceHTTPServer interface {
	CompleteShoppingList(context.Context, *CompleteShoppingListRequest) (*CompleteShoppingListReply, error)
	// CreateCookingHistory CreateCookingHistory 在烹饪流程结束时落库一条历史记录。
	CreateCookingHistory(context.Context, *CreateCookingHistoryRequest) (*CreateCookingHistoryReply, error)
	CreateRecipeShare(context.Context, *CreateRecipeShareRequest) (*CreateRecipeShareReply, error)
	GenerateCurrentMealPlan(context.Context, *GenerateCurrentMealPlanRequest) (*GenerateCurrentMealPlanReply, error)
	GenerateShoppingList(context.Context, *GenerateShoppingListRequest) (*GenerateShoppingListReply, error)
	GetCurrentMealPlan(context.Context, *GetCurrentMealPlanRequest) (*GetCurrentMealPlanReply, error)
	GetCurrentShoppingList(context.Context, *GetCurrentShoppingListRequest) (*GetCurrentShoppingListReply, error)
	ImportRecipeShare(context.Context, *ImportRecipeShareRequest) (*ImportRecipeShareReply, error)
	// ListCookingHistory ListCookingHistory 分页拉取当前用户的历史记录（"我的"页面使用）。
	ListCookingHistory(context.Context, *ListCookingHistoryRequest) (*ListCookingHistoryReply, error)
	ListInventoryItems(context.Context, *ListInventoryItemsRequest) (*ListInventoryItemsReply, error)
	ListInventoryRecommendations(context.Context, *ListInventoryRecommendationsRequest) (*ListInventoryRecommendationsReply, error)
	// ListRecentCookingHistory ListRecentCookingHistory 取最近 N 条历史，供首页"最近做过"模块使用，独立路径以便缓存。
	ListRecentCookingHistory(context.Context, *ListRecentCookingHistoryRequest) (*ListRecentCookingHistoryReply, error)
	PatchInventoryItem(context.Context, *PatchInventoryItemRequest) (*PatchInventoryItemReply, error)
	PatchShoppingListItem(context.Context, *PatchShoppingListItemRequest) (*PatchShoppingListItemReply, error)
	PreviewRecipeShare(context.Context, *PreviewRecipeShareRequest) (*PreviewRecipeShareReply, error)
	SaveCurrentMealPlan(context.Context, *SaveCurrentMealPlanRequest) (*SaveCurrentMealPlanReply, error)
	UpsertInventoryItems(context.Context, *UpsertInventoryItemsRequest) (*UpsertInventoryItemsReply, error)
}

func RegisterKitchenServiceHTTPServer(s *http.Server, srv KitchenServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/api/v1/meal-plans/current", _KitchenService_GetCurrentMealPlan0_HTTP_Handler(srv))
	r.PUT("/api/v1/meal-plans/current", _KitchenService_SaveCurrentMealPlan0_HTTP_Handler(srv))
	r.POST("/api/v1/meal-plans/current:generate", _KitchenService_GenerateCurrentMealPlan0_HTTP_Handler(srv))
	r.GET("/api/v1/shopping-lists/current", _KitchenService_GetCurrentShoppingList0_HTTP_Handler(srv))
	r.POST("/api/v1/shopping-lists:generate", _KitchenService_GenerateShoppingList0_HTTP_Handler(srv))
	r.PATCH("/api/v1/shopping-lists/{list_id}/items/{item_id}", _KitchenService_PatchShoppingListItem0_HTTP_Handler(srv))
	r.POST("/api/v1/shopping-lists/{list_id}:complete", _KitchenService_CompleteShoppingList0_HTTP_Handler(srv))
	r.GET("/api/v1/inventory-items", _KitchenService_ListInventoryItems0_HTTP_Handler(srv))
	r.POST("/api/v1/inventory-items:upsert", _KitchenService_UpsertInventoryItems0_HTTP_Handler(srv))
	r.PATCH("/api/v1/inventory-items/{item_id}", _KitchenService_PatchInventoryItem0_HTTP_Handler(srv))
	r.GET("/api/v1/inventory-items/recommendations", _KitchenService_ListInventoryRecommendations0_HTTP_Handler(srv))
	r.POST("/api/v1/recipes/{id}/share", _KitchenService_CreateRecipeShare0_HTTP_Handler(srv))
	r.GET("/api/v1/recipe-shares/{share_code}", _KitchenService_PreviewRecipeShare0_HTTP_Handler(srv))
	r.POST("/api/v1/recipe-shares/{share_code}:import", _KitchenService_ImportRecipeShare0_HTTP_Handler(srv))
	r.POST("/api/v1/cooking-history", _KitchenService_CreateCookingHistory0_HTTP_Handler(srv))
	r.GET("/api/v1/cooking-history", _KitchenService_ListCookingHistory0_HTTP_Handler(srv))
	r.GET("/api/v1/cooking-history/recent", _KitchenService_ListRecentCookingHistory0_HTTP_Handler(srv))
}

func _KitchenService_GetCurrentMealPlan0_HTTP_Handler(srv KitchenServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCurrentMealPlanRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKitchenServiceGetCurrentMealPlan)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCurrentMealPlan(ctx, req.(*GetCurrentMealPlanRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCurrentMealPlanReply)
		return ctx.Result(200, reply)
	}
}

func _KitchenService_SaveCurrentMealPlan0_HTTP_Handler(srv KitchenServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SaveCurrentMealPlanRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKitchenServiceSaveCurrentMealPlan)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SaveCurrentMealPlan(ctx, req.(*SaveCurrentMealPlanRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SaveCurrentMealPlanReply)
		return ctx.Result(200, reply)
	}
}

func _KitchenService_GenerateCurrentMealPlan0_HTTP_Handler(srv KitchenServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GenerateCurrentMealPlanRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKitchenServiceGenerateCurrentMealPlan)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GenerateCurrentMealPlan(ctx, req.(*GenerateCurrentMealPlanRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GenerateCurrentMealPlanReply)
		return ctx.Result(200, reply)
	}
}

func _KitchenService_GetCurrentShoppingList0_HTTP_Handler(srv KitchenServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCurrentShoppingListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKitchenServiceGetCurrentShoppingList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCurrentShoppingList(ctx, req.(*GetCurrentShoppingListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCurrentShoppingListReply)
		return ctx.Result(200, reply)
	}
}

func _KitchenService_GenerateShoppingList0_HTTP_Handler(srv KitchenServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GenerateShoppingListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKitchenServiceGenerateShoppingList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GenerateShoppingList(ctx, req.(*GenerateShoppingListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GenerateShoppingListReply)
		return ctx.Result(200, reply)
	}
}

func _KitchenService_PatchShoppingListItem0_HTTP_Handler(srv KitchenServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PatchShoppingListItemRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKitchenServicePatchShoppingListItem)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PatchShoppingListItem(ctx, req.(*PatchShoppingListItemRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PatchShoppingListItemReply)
		return ctx.Result(200, reply)
	}
}

func _KitchenService_CompleteShoppingList0_HTTP_Handler(srv KitchenServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CompleteShoppingListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKitchenServiceCompleteShoppingList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CompleteShoppingList(ctx, req.(*CompleteShoppingListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CompleteShoppingListReply)
		return ctx.Result(200, reply)
	}
}

func _KitchenService_ListInventoryItems0_HTTP_Handler(srv KitchenServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListInventoryItemsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKitchenServiceListInventoryItems)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListInventoryItems(ctx, req.(*ListInventoryItemsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListInventoryItemsReply)
		return ctx.Result(200, reply)
	}
}

func _KitchenService_UpsertInventoryItems0_HTTP_Handler(srv KitchenServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpsertInventoryItemsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKitchenServiceUpsertInventoryItems)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpsertInventoryItems(ctx, req.(*UpsertInventoryItemsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpsertInventoryItemsReply)
		return ctx.Result(200, reply)
	}
}

func _KitchenService_PatchInventoryItem0_HTTP_Handler(srv KitchenServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PatchInventoryItemRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKitchenServicePatchInventoryItem)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PatchInventoryItem(ctx, req.(*PatchInventoryItemRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PatchInventoryItemReply)
		return ctx.Result(200, reply)
	}
}

func _KitchenService_ListInventoryRecommendations0_HTTP_Handler(srv KitchenServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListInventoryRecommendationsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKitchenServiceListInventoryRecommendations)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListInventoryRecommendations(ctx, req.(*ListInventoryRecommendationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListInventoryRecommendationsReply)
		return ctx.Result(200, reply)
	}
}

func _KitchenService_CreateRecipeShare0_HTTP_Handler(srv KitchenServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateRecipeShareRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKitchenServiceCreateRecipeShare)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateRecipeShare(ctx, req.(*CreateRecipeShareRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateRecipeShareReply)
		return ctx.Result(200, reply)
	}
}

func _KitchenService_PreviewRecipeShare0_HTTP_Handler(srv KitchenServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PreviewRecipeShareRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKitchenServicePreviewRecipeShare)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PreviewRecipeShare(ctx, req.(*PreviewRecipeShareRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PreviewRecipeShareReply)
		return ctx.Result(200, reply)
	}
}

func _KitchenService_ImportRecipeShare0_HTTP_Handler(srv KitchenServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ImportRecipeShareRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKitchenServiceImportRecipeShare)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ImportRecipeShare(ctx, req.(*ImportRecipeShareRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ImportRecipeShareReply)
		return ctx.Result(200, reply)
	}
}

func _KitchenService_CreateCookingHistory0_HTTP_Handler(srv KitchenServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateCookingHistoryRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKitchenServiceCreateCookingHistory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateCookingHistory(ctx, req.(*CreateCookingHistoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateCookingHistoryReply)
		return ctx.Result(200, reply)
	}
}

func _KitchenService_ListCookingHistory0_HTTP_Handler(srv KitchenServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCookingHistoryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKitchenServiceListCookingHistory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCookingHistory(ctx, req.(*ListCookingHistoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCookingHistoryReply)
		return ctx.Result(200, reply)
	}
}

func _KitchenService_ListRecentCookingHistory0_HTTP_Handler(srv KitchenServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRecentCookingHistoryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationKitchenServiceListRecentCookingHistory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRecentCookingHistory(ctx, req.(*ListRecentCookingHistoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRecentCookingHistoryReply)
		return ctx.Result(200, reply)
	}
}

type KitchenServiceHTTPClient interface {
	CompleteShoppingList(ctx context.Context, req *CompleteShoppingListRequest, opts ...http.CallOption) (rsp *CompleteShoppingListReply, err error)
	// CreateCookingHistory CreateCookingHistory 在烹饪流程结束时落库一条历史记录。
	CreateCookingHistory(ctx context.Context, req *CreateCookingHistoryRequest, opts ...http.CallOption) (rsp *CreateCookingHistoryReply, err error)
	CreateRecipeShare(ctx context.Context, req *CreateRecipeShareRequest, opts ...http.CallOption) (rsp *CreateRecipeShareReply, err error)
	GenerateCurrentMealPlan(ctx context.Context, req *GenerateCurrentMealPlanRequest, opts ...http.CallOption) (rsp *GenerateCurrentMealPlanReply, err error)
	GenerateShoppingList(ctx context.Context, req *GenerateShoppingListRequest, opts ...http.CallOption) (rsp *GenerateShoppingListReply, err error)
	GetCurrentMealPlan(ctx context.Context, req *GetCurrentMealPlanRequest, opts ...http.CallOption) (rsp *GetCurrentMealPlanReply, err error)
	GetCurrentShoppingList(ctx context.Context, req *GetCurrentShoppingListRequest, opts ...http.CallOption) (rsp *GetCurrentShoppingListReply, err error)
	ImportRecipeShare(ctx context.Context, req *ImportRecipeShareRequest, opts ...http.CallOption) (rsp *ImportRecipeShareReply, err error)
	// ListCookingHistory ListCookingHistory 分页拉取当前用户的历史记录（"我的"页面使用）。
	ListCookingHistory(ctx context.Context, req *ListCookingHistoryRequest, opts ...http.CallOption) (rsp *ListCookingHistoryReply, err error)
	ListInventoryItems(ctx context.Context, req *ListInventoryItemsRequest, opts ...http.CallOption) (rsp *ListInventoryItemsReply, err error)
	ListInventoryRecommendations(ctx context.Context, req *ListInventoryRecommendationsRequest, opts ...http.CallOption) (rsp *ListInventoryRecommendationsReply, err error)
	// ListRecentCookingHistory ListRecentCookingHistory 取最近 N 条历史，供首页"最近做过"模块使用，独立路径以便缓存。
	ListRecentCookingHistory(ctx context.Context, req *ListRecentCookingHistoryRequest, opts ...http.CallOption) (rsp *ListRecentCookingHistoryReply, err error)
	PatchInventoryItem(ctx context.Context, req *PatchInventoryItemRequest, opts ...http.CallOption) (rsp *PatchInventoryItemReply, err error)
	PatchShoppingListItem(ctx context.Context, req *PatchShoppingListItemRequest, opts ...http.CallOption) (rsp *PatchShoppingListItemReply, err error)
	PreviewRecipeShare(ctx context.Context, req *PreviewRecipeShareRequest, opts ...http.CallOption) (rsp *PreviewRecipeShareReply, err error)
	SaveCurrentMealPlan(ctx context.Context, req *SaveCurrentMealPlanRequest, opts ...http.CallOption) (rsp *SaveCurrentMealPlanReply, err error)
	UpsertInventoryItems(ctx context.Context, req *UpsertInventoryItemsRequest, opts ...http.CallOption) (rsp *UpsertInventoryItemsReply, err error)
}

type KitchenServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewKitchenServiceHTTPClient(client *http.Client) KitchenServiceHTTPClient {
	return &KitchenServiceHTTPClientImpl{client}
}

func (c *KitchenServiceHTTPClientImpl) CompleteShoppingList(ctx context.Context, in *CompleteShoppingListRequest, opts ...http.CallOption) (*CompleteShoppingListReply, error) {
	var out CompleteShoppingListReply
	pattern := "/api/v1/shopping-lists/{list_id}:complete"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKitchenServiceCompleteShoppingList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateCookingHistory CreateCookingHistory 在烹饪流程结束时落库一条历史记录。
func (c *KitchenServiceHTTPClientImpl) CreateCookingHistory(ctx context.Context, in *CreateCookingHistoryRequest, opts ...http.CallOption) (*CreateCookingHistoryReply, error) {
	var out CreateCookingHistoryReply
	pattern := "/api/v1/cooking-history"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationKitchenServiceCreateCookingHistory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KitchenServiceHTTPClientImpl) CreateRecipeShare(ctx context.Context, in *CreateRecipeShareRequest, opts ...http.CallOption) (*CreateRecipeShareReply, error) {
	var out CreateRecipeShareReply
	pattern := "/api/v1/recipes/{id}/share"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKitchenServiceCreateRecipeShare))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KitchenServiceHTTPClientImpl) GenerateCurrentMealPlan(ctx context.Context, in *GenerateCurrentMealPlanRequest, opts ...http.CallOption) (*GenerateCurrentMealPlanReply, error) {
	var out GenerateCurrentMealPlanReply
	pattern := "/api/v1/meal-plans/current:generate"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKitchenServiceGenerateCurrentMealPlan))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KitchenServiceHTTPClientImpl) GenerateShoppingList(ctx context.Context, in *GenerateShoppingListRequest, opts ...http.CallOption) (*GenerateShoppingListReply, error) {
	var out GenerateShoppingListReply
	pattern := "/api/v1/shopping-lists:generate"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKitchenServiceGenerateShoppingList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KitchenServiceHTTPClientImpl) GetCurrentMealPlan(ctx context.Context, in *GetCurrentMealPlanRequest, opts ...http.CallOption) (*GetCurrentMealPlanReply, error) {
	var out GetCurrentMealPlanReply
	pattern := "/api/v1/meal-plans/current"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKitchenServiceGetCurrentMealPlan))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KitchenServiceHTTPClientImpl) GetCurrentShoppingList(ctx context.Context, in *GetCurrentShoppingListRequest, opts ...http.CallOption) (*GetCurrentShoppingListReply, error) {
	var out GetCurrentShoppingListReply
	pattern := "/api/v1/shopping-lists/current"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKitchenServiceGetCurrentShoppingList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KitchenServiceHTTPClientImpl) ImportRecipeShare(ctx context.Context, in *ImportRecipeShareRequest, opts ...http.CallOption) (*ImportRecipeShareReply, error) {
	var out ImportRecipeShareReply
	pattern := "/api/v1/recipe-shares/{share_code}:import"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKitchenServiceImportRecipeShare))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListCookingHistory ListCookingHistory 分页拉取当前用户的历史记录（"我的"页面使用）。
func (c *KitchenServiceHTTPClientImpl) ListCookingHistory(ctx context.Context, in *ListCookingHistoryRequest, opts ...http.CallOption) (*ListCookingHistoryReply, error) {
	var out ListCookingHistoryReply
	pattern := "/api/v1/cooking-history"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKitchenServiceListCookingHistory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KitchenServiceHTTPClientImpl) ListInventoryItems(ctx context.Context, in *ListInventoryItemsRequest, opts ...http.CallOption) (*ListInventoryItemsReply, error) {
	var out ListInventoryItemsReply
	pattern := "/api/v1/inventory-items"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKitchenServiceListInventoryItems))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KitchenServiceHTTPClientImpl) ListInventoryRecommendations(ctx context.Context, in *ListInventoryRecommendationsRequest, opts ...http.CallOption) (*ListInventoryRecommendationsReply, error) {
	var out ListInventoryRecommendationsReply
	pattern := "/api/v1/inventory-items/recommendations"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKitchenServiceListInventoryRecommendations))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListRecentCookingHistory ListRecentCookingHistory 取最近 N 条历史，供首页"最近做过"模块使用，独立路径以便缓存。
func (c *KitchenServiceHTTPClientImpl) ListRecentCookingHistory(ctx context.Context, in *ListRecentCookingHistoryRequest, opts ...http.CallOption) (*ListRecentCookingHistoryReply, error) {
	var out ListRecentCookingHistoryReply
	pattern := "/api/v1/cooking-history/recent"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKitchenServiceListRecentCookingHistory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KitchenServiceHTTPClientImpl) PatchInventoryItem(ctx context.Context, in *PatchInventoryItemRequest, opts ...http.CallOption) (*PatchInventoryItemReply, error) {
	var out PatchInventoryItemReply
	pattern := "/api/v1/inventory-items/{item_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationKitchenServicePatchInventoryItem))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KitchenServiceHTTPClientImpl) PatchShoppingListItem(ctx context.Context, in *PatchShoppingListItemRequest, opts ...http.CallOption) (*PatchShoppingListItemReply, error) {
	var out PatchShoppingListItemReply
	pattern := "/api/v1/shopping-lists/{list_id}/items/{item_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationKitchenServicePatchShoppingListItem))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PATCH", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KitchenServiceHTTPClientImpl) PreviewRecipeShare(ctx context.Context, in *PreviewRecipeShareRequest, opts ...http.CallOption) (*PreviewRecipeShareReply, error) {
	var out PreviewRecipeShareReply
	pattern := "/api/v1/recipe-shares/{share_code}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationKitchenServicePreviewRecipeShare))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KitchenServiceHTTPClientImpl) SaveCurrentMealPlan(ctx context.Context, in *SaveCurrentMealPlanRequest, opts ...http.CallOption) (*SaveCurrentMealPlanReply, error) {
	var out SaveCurrentMealPlanReply
	pattern := "/api/v1/meal-plans/current"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationKitchenServiceSaveCurrentMealPlan))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *KitchenServiceHTTPClientImpl) UpsertInventoryItems(ctx context.Context, in *UpsertInventoryItemsRequest, opts ...http.CallOption) (*UpsertInventoryItemsReply, error) {
	var out UpsertInventoryItemsReply
	pattern := "/api/v1/inventory-items:upsert"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationKitchenServiceUpsertInventoryItems))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
