// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/aicook/v1/kitchen.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KitchenService_GetCurrentMealPlan_FullMethodName           = "/aicook.v1.KitchenService/GetCurrentMealPlan"
	KitchenService_SaveCurrentMealPlan_FullMethodName          = "/aicook.v1.KitchenService/SaveCurrentMealPlan"
	KitchenService_GenerateCurrentMealPlan_FullMethodName      = "/aicook.v1.KitchenService/GenerateCurrentMealPlan"
	KitchenService_GetCurrentShoppingList_FullMethodName       = "/aicook.v1.KitchenService/GetCurrentShoppingList"
	KitchenService_GenerateShoppingList_FullMethodName         = "/aicook.v1.KitchenService/GenerateShoppingList"
	KitchenService_PatchShoppingListItem_FullMethodName        = "/aicook.v1.KitchenService/PatchShoppingListItem"
	KitchenService_CompleteShoppingList_FullMethodName         = "/aicook.v1.KitchenService/CompleteShoppingList"
	KitchenService_ListInventoryItems_FullMethodName           = "/aicook.v1.KitchenService/ListInventoryItems"
	KitchenService_UpsertInventoryItems_FullMethodName         = "/aicook.v1.KitchenService/UpsertInventoryItems"
	KitchenService_PatchInventoryItem_FullMethodName           = "/aicook.v1.KitchenService/PatchInventoryItem"
	KitchenService_ListInventoryRecommendations_FullMethodName = "/aicook.v1.KitchenService/ListInventoryRecommendations"
	KitchenService_CreateRecipeShare_FullMethodName            = "/aicook.v1.KitchenService/CreateRecipeShare"
	KitchenService_PreviewRecipeShare_FullMethodName           = "/aicook.v1.KitchenService/PreviewRecipeShare"
	KitchenService_ImportRecipeShare_FullMethodName            = "/aicook.v1.KitchenService/ImportRecipeShare"
)

// KitchenServiceClient is the client API for KitchenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Kitchen 厨房核心：周计划、购物清单、库存、菜谱分享等（与前端 client.ts 对齐）。
type KitchenServiceClient interface {
	GetCurrentMealPlan(ctx context.Context, in *GetCurrentMealPlanRequest, opts ...grpc.CallOption) (*GetCurrentMealPlanReply, error)
	SaveCurrentMealPlan(ctx context.Context, in *SaveCurrentMealPlanRequest, opts ...grpc.CallOption) (*SaveCurrentMealPlanReply, error)
	GenerateCurrentMealPlan(ctx context.Context, in *GenerateCurrentMealPlanRequest, opts ...grpc.CallOption) (*GenerateCurrentMealPlanReply, error)
	GetCurrentShoppingList(ctx context.Context, in *GetCurrentShoppingListRequest, opts ...grpc.CallOption) (*GetCurrentShoppingListReply, error)
	GenerateShoppingList(ctx context.Context, in *GenerateShoppingListRequest, opts ...grpc.CallOption) (*GenerateShoppingListReply, error)
	PatchShoppingListItem(ctx context.Context, in *PatchShoppingListItemRequest, opts ...grpc.CallOption) (*PatchShoppingListItemReply, error)
	CompleteShoppingList(ctx context.Context, in *CompleteShoppingListRequest, opts ...grpc.CallOption) (*CompleteShoppingListReply, error)
	ListInventoryItems(ctx context.Context, in *ListInventoryItemsRequest, opts ...grpc.CallOption) (*ListInventoryItemsReply, error)
	UpsertInventoryItems(ctx context.Context, in *UpsertInventoryItemsRequest, opts ...grpc.CallOption) (*UpsertInventoryItemsReply, error)
	PatchInventoryItem(ctx context.Context, in *PatchInventoryItemRequest, opts ...grpc.CallOption) (*PatchInventoryItemReply, error)
	ListInventoryRecommendations(ctx context.Context, in *ListInventoryRecommendationsRequest, opts ...grpc.CallOption) (*ListInventoryRecommendationsReply, error)
	CreateRecipeShare(ctx context.Context, in *CreateRecipeShareRequest, opts ...grpc.CallOption) (*CreateRecipeShareReply, error)
	PreviewRecipeShare(ctx context.Context, in *PreviewRecipeShareRequest, opts ...grpc.CallOption) (*PreviewRecipeShareReply, error)
	ImportRecipeShare(ctx context.Context, in *ImportRecipeShareRequest, opts ...grpc.CallOption) (*ImportRecipeShareReply, error)
}

type kitchenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKitchenServiceClient(cc grpc.ClientConnInterface) KitchenServiceClient {
	return &kitchenServiceClient{cc}
}

func (c *kitchenServiceClient) GetCurrentMealPlan(ctx context.Context, in *GetCurrentMealPlanRequest, opts ...grpc.CallOption) (*GetCurrentMealPlanReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrentMealPlanReply)
	err := c.cc.Invoke(ctx, KitchenService_GetCurrentMealPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kitchenServiceClient) SaveCurrentMealPlan(ctx context.Context, in *SaveCurrentMealPlanRequest, opts ...grpc.CallOption) (*SaveCurrentMealPlanReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveCurrentMealPlanReply)
	err := c.cc.Invoke(ctx, KitchenService_SaveCurrentMealPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kitchenServiceClient) GenerateCurrentMealPlan(ctx context.Context, in *GenerateCurrentMealPlanRequest, opts ...grpc.CallOption) (*GenerateCurrentMealPlanReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateCurrentMealPlanReply)
	err := c.cc.Invoke(ctx, KitchenService_GenerateCurrentMealPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kitchenServiceClient) GetCurrentShoppingList(ctx context.Context, in *GetCurrentShoppingListRequest, opts ...grpc.CallOption) (*GetCurrentShoppingListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrentShoppingListReply)
	err := c.cc.Invoke(ctx, KitchenService_GetCurrentShoppingList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kitchenServiceClient) GenerateShoppingList(ctx context.Context, in *GenerateShoppingListRequest, opts ...grpc.CallOption) (*GenerateShoppingListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateShoppingListReply)
	err := c.cc.Invoke(ctx, KitchenService_GenerateShoppingList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kitchenServiceClient) PatchShoppingListItem(ctx context.Context, in *PatchShoppingListItemRequest, opts ...grpc.CallOption) (*PatchShoppingListItemReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatchShoppingListItemReply)
	err := c.cc.Invoke(ctx, KitchenService_PatchShoppingListItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kitchenServiceClient) CompleteShoppingList(ctx context.Context, in *CompleteShoppingListRequest, opts ...grpc.CallOption) (*CompleteShoppingListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteShoppingListReply)
	err := c.cc.Invoke(ctx, KitchenService_CompleteShoppingList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kitchenServiceClient) ListInventoryItems(ctx context.Context, in *ListInventoryItemsRequest, opts ...grpc.CallOption) (*ListInventoryItemsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInventoryItemsReply)
	err := c.cc.Invoke(ctx, KitchenService_ListInventoryItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kitchenServiceClient) UpsertInventoryItems(ctx context.Context, in *UpsertInventoryItemsRequest, opts ...grpc.CallOption) (*UpsertInventoryItemsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertInventoryItemsReply)
	err := c.cc.Invoke(ctx, KitchenService_UpsertInventoryItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kitchenServiceClient) PatchInventoryItem(ctx context.Context, in *PatchInventoryItemRequest, opts ...grpc.CallOption) (*PatchInventoryItemReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatchInventoryItemReply)
	err := c.cc.Invoke(ctx, KitchenService_PatchInventoryItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kitchenServiceClient) ListInventoryRecommendations(ctx context.Context, in *ListInventoryRecommendationsRequest, opts ...grpc.CallOption) (*ListInventoryRecommendationsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInventoryRecommendationsReply)
	err := c.cc.Invoke(ctx, KitchenService_ListInventoryRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kitchenServiceClient) CreateRecipeShare(ctx context.Context, in *CreateRecipeShareRequest, opts ...grpc.CallOption) (*CreateRecipeShareReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRecipeShareReply)
	err := c.cc.Invoke(ctx, KitchenService_CreateRecipeShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kitchenServiceClient) PreviewRecipeShare(ctx context.Context, in *PreviewRecipeShareRequest, opts ...grpc.CallOption) (*PreviewRecipeShareReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreviewRecipeShareReply)
	err := c.cc.Invoke(ctx, KitchenService_PreviewRecipeShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kitchenServiceClient) ImportRecipeShare(ctx context.Context, in *ImportRecipeShareRequest, opts ...grpc.CallOption) (*ImportRecipeShareReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportRecipeShareReply)
	err := c.cc.Invoke(ctx, KitchenService_ImportRecipeShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KitchenServiceServer is the server API for KitchenService service.
// All implementations should embed UnimplementedKitchenServiceServer
// for forward compatibility.
//
// Kitchen 厨房核心：周计划、购物清单、库存、菜谱分享等（与前端 client.ts 对齐）。
type KitchenServiceServer interface {
	GetCurrentMealPlan(context.Context, *GetCurrentMealPlanRequest) (*GetCurrentMealPlanReply, error)
	SaveCurrentMealPlan(context.Context, *SaveCurrentMealPlanRequest) (*SaveCurrentMealPlanReply, error)
	GenerateCurrentMealPlan(context.Context, *GenerateCurrentMealPlanRequest) (*GenerateCurrentMealPlanReply, error)
	GetCurrentShoppingList(context.Context, *GetCurrentShoppingListRequest) (*GetCurrentShoppingListReply, error)
	GenerateShoppingList(context.Context, *GenerateShoppingListRequest) (*GenerateShoppingListReply, error)
	PatchShoppingListItem(context.Context, *PatchShoppingListItemRequest) (*PatchShoppingListItemReply, error)
	CompleteShoppingList(context.Context, *CompleteShoppingListRequest) (*CompleteShoppingListReply, error)
	ListInventoryItems(context.Context, *ListInventoryItemsRequest) (*ListInventoryItemsReply, error)
	UpsertInventoryItems(context.Context, *UpsertInventoryItemsRequest) (*UpsertInventoryItemsReply, error)
	PatchInventoryItem(context.Context, *PatchInventoryItemRequest) (*PatchInventoryItemReply, error)
	ListInventoryRecommendations(context.Context, *ListInventoryRecommendationsRequest) (*ListInventoryRecommendationsReply, error)
	CreateRecipeShare(context.Context, *CreateRecipeShareRequest) (*CreateRecipeShareReply, error)
	PreviewRecipeShare(context.Context, *PreviewRecipeShareRequest) (*PreviewRecipeShareReply, error)
	ImportRecipeShare(context.Context, *ImportRecipeShareRequest) (*ImportRecipeShareReply, error)
}

// UnimplementedKitchenServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKitchenServiceServer struct{}

func (UnimplementedKitchenServiceServer) GetCurrentMealPlan(context.Context, *GetCurrentMealPlanRequest) (*GetCurrentMealPlanReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentMealPlan not implemented")
}
func (UnimplementedKitchenServiceServer) SaveCurrentMealPlan(context.Context, *SaveCurrentMealPlanRequest) (*SaveCurrentMealPlanReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveCurrentMealPlan not implemented")
}
func (UnimplementedKitchenServiceServer) GenerateCurrentMealPlan(context.Context, *GenerateCurrentMealPlanRequest) (*GenerateCurrentMealPlanReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateCurrentMealPlan not implemented")
}
func (UnimplementedKitchenServiceServer) GetCurrentShoppingList(context.Context, *GetCurrentShoppingListRequest) (*GetCurrentShoppingListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentShoppingList not implemented")
}
func (UnimplementedKitchenServiceServer) GenerateShoppingList(context.Context, *GenerateShoppingListRequest) (*GenerateShoppingListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateShoppingList not implemented")
}
func (UnimplementedKitchenServiceServer) PatchShoppingListItem(context.Context, *PatchShoppingListItemRequest) (*PatchShoppingListItemReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchShoppingListItem not implemented")
}
func (UnimplementedKitchenServiceServer) CompleteShoppingList(context.Context, *CompleteShoppingListRequest) (*CompleteShoppingListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteShoppingList not implemented")
}
func (UnimplementedKitchenServiceServer) ListInventoryItems(context.Context, *ListInventoryItemsRequest) (*ListInventoryItemsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInventoryItems not implemented")
}
func (UnimplementedKitchenServiceServer) UpsertInventoryItems(context.Context, *UpsertInventoryItemsRequest) (*UpsertInventoryItemsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertInventoryItems not implemented")
}
func (UnimplementedKitchenServiceServer) PatchInventoryItem(context.Context, *PatchInventoryItemRequest) (*PatchInventoryItemReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchInventoryItem not implemented")
}
func (UnimplementedKitchenServiceServer) ListInventoryRecommendations(context.Context, *ListInventoryRecommendationsRequest) (*ListInventoryRecommendationsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInventoryRecommendations not implemented")
}
func (UnimplementedKitchenServiceServer) CreateRecipeShare(context.Context, *CreateRecipeShareRequest) (*CreateRecipeShareReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRecipeShare not implemented")
}
func (UnimplementedKitchenServiceServer) PreviewRecipeShare(context.Context, *PreviewRecipeShareRequest) (*PreviewRecipeShareReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PreviewRecipeShare not implemented")
}
func (UnimplementedKitchenServiceServer) ImportRecipeShare(context.Context, *ImportRecipeShareRequest) (*ImportRecipeShareReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportRecipeShare not implemented")
}
func (UnimplementedKitchenServiceServer) testEmbeddedByValue() {}

// UnsafeKitchenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KitchenServiceServer will
// result in compilation errors.
type UnsafeKitchenServiceServer interface {
	mustEmbedUnimplementedKitchenServiceServer()
}

func RegisterKitchenServiceServer(s grpc.ServiceRegistrar, srv KitchenServiceServer) {
	// If the following call pancis, it indicates UnimplementedKitchenServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KitchenService_ServiceDesc, srv)
}

func _KitchenService_GetCurrentMealPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentMealPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KitchenServiceServer).GetCurrentMealPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KitchenService_GetCurrentMealPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KitchenServiceServer).GetCurrentMealPlan(ctx, req.(*GetCurrentMealPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KitchenService_SaveCurrentMealPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveCurrentMealPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KitchenServiceServer).SaveCurrentMealPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KitchenService_SaveCurrentMealPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KitchenServiceServer).SaveCurrentMealPlan(ctx, req.(*SaveCurrentMealPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KitchenService_GenerateCurrentMealPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateCurrentMealPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KitchenServiceServer).GenerateCurrentMealPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KitchenService_GenerateCurrentMealPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KitchenServiceServer).GenerateCurrentMealPlan(ctx, req.(*GenerateCurrentMealPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KitchenService_GetCurrentShoppingList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentShoppingListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KitchenServiceServer).GetCurrentShoppingList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KitchenService_GetCurrentShoppingList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KitchenServiceServer).GetCurrentShoppingList(ctx, req.(*GetCurrentShoppingListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KitchenService_GenerateShoppingList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateShoppingListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KitchenServiceServer).GenerateShoppingList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KitchenService_GenerateShoppingList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KitchenServiceServer).GenerateShoppingList(ctx, req.(*GenerateShoppingListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KitchenService_PatchShoppingListItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchShoppingListItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KitchenServiceServer).PatchShoppingListItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KitchenService_PatchShoppingListItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KitchenServiceServer).PatchShoppingListItem(ctx, req.(*PatchShoppingListItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KitchenService_CompleteShoppingList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteShoppingListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KitchenServiceServer).CompleteShoppingList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KitchenService_CompleteShoppingList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KitchenServiceServer).CompleteShoppingList(ctx, req.(*CompleteShoppingListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KitchenService_ListInventoryItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInventoryItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KitchenServiceServer).ListInventoryItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KitchenService_ListInventoryItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KitchenServiceServer).ListInventoryItems(ctx, req.(*ListInventoryItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KitchenService_UpsertInventoryItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertInventoryItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KitchenServiceServer).UpsertInventoryItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KitchenService_UpsertInventoryItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KitchenServiceServer).UpsertInventoryItems(ctx, req.(*UpsertInventoryItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KitchenService_PatchInventoryItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchInventoryItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KitchenServiceServer).PatchInventoryItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KitchenService_PatchInventoryItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KitchenServiceServer).PatchInventoryItem(ctx, req.(*PatchInventoryItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KitchenService_ListInventoryRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInventoryRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KitchenServiceServer).ListInventoryRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KitchenService_ListInventoryRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KitchenServiceServer).ListInventoryRecommendations(ctx, req.(*ListInventoryRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KitchenService_CreateRecipeShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRecipeShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KitchenServiceServer).CreateRecipeShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KitchenService_CreateRecipeShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KitchenServiceServer).CreateRecipeShare(ctx, req.(*CreateRecipeShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KitchenService_PreviewRecipeShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreviewRecipeShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KitchenServiceServer).PreviewRecipeShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KitchenService_PreviewRecipeShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KitchenServiceServer).PreviewRecipeShare(ctx, req.(*PreviewRecipeShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KitchenService_ImportRecipeShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportRecipeShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KitchenServiceServer).ImportRecipeShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KitchenService_ImportRecipeShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KitchenServiceServer).ImportRecipeShare(ctx, req.(*ImportRecipeShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KitchenService_ServiceDesc is the grpc.ServiceDesc for KitchenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KitchenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aicook.v1.KitchenService",
	HandlerType: (*KitchenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrentMealPlan",
			Handler:    _KitchenService_GetCurrentMealPlan_Handler,
		},
		{
			MethodName: "SaveCurrentMealPlan",
			Handler:    _KitchenService_SaveCurrentMealPlan_Handler,
		},
		{
			MethodName: "GenerateCurrentMealPlan",
			Handler:    _KitchenService_GenerateCurrentMealPlan_Handler,
		},
		{
			MethodName: "GetCurrentShoppingList",
			Handler:    _KitchenService_GetCurrentShoppingList_Handler,
		},
		{
			MethodName: "GenerateShoppingList",
			Handler:    _KitchenService_GenerateShoppingList_Handler,
		},
		{
			MethodName: "PatchShoppingListItem",
			Handler:    _KitchenService_PatchShoppingListItem_Handler,
		},
		{
			MethodName: "CompleteShoppingList",
			Handler:    _KitchenService_CompleteShoppingList_Handler,
		},
		{
			MethodName: "ListInventoryItems",
			Handler:    _KitchenService_ListInventoryItems_Handler,
		},
		{
			MethodName: "UpsertInventoryItems",
			Handler:    _KitchenService_UpsertInventoryItems_Handler,
		},
		{
			MethodName: "PatchInventoryItem",
			Handler:    _KitchenService_PatchInventoryItem_Handler,
		},
		{
			MethodName: "ListInventoryRecommendations",
			Handler:    _KitchenService_ListInventoryRecommendations_Handler,
		},
		{
			MethodName: "CreateRecipeShare",
			Handler:    _KitchenService_CreateRecipeShare_Handler,
		},
		{
			MethodName: "PreviewRecipeShare",
			Handler:    _KitchenService_PreviewRecipeShare_Handler,
		},
		{
			MethodName: "ImportRecipeShare",
			Handler:    _KitchenService_ImportRecipeShare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/aicook/v1/kitchen.proto",
}
