// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/aicook/v1/knowledge.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateKnowledgeBaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKnowledgeBaseRequest) Reset() {
	*x = CreateKnowledgeBaseRequest{}
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKnowledgeBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKnowledgeBaseRequest) ProtoMessage() {}

func (x *CreateKnowledgeBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKnowledgeBaseRequest.ProtoReflect.Descriptor instead.
func (*CreateKnowledgeBaseRequest) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_knowledge_proto_rawDescGZIP(), []int{0}
}

func (x *CreateKnowledgeBaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateKnowledgeBaseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateKnowledgeBaseReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *KnowledgeBase         `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKnowledgeBaseReply) Reset() {
	*x = CreateKnowledgeBaseReply{}
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKnowledgeBaseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKnowledgeBaseReply) ProtoMessage() {}

func (x *CreateKnowledgeBaseReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKnowledgeBaseReply.ProtoReflect.Descriptor instead.
func (*CreateKnowledgeBaseReply) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_knowledge_proto_rawDescGZIP(), []int{1}
}

func (x *CreateKnowledgeBaseReply) GetBase() *KnowledgeBase {
	if x != nil {
		return x.Base
	}
	return nil
}

type ListKnowledgeBasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKnowledgeBasesRequest) Reset() {
	*x = ListKnowledgeBasesRequest{}
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKnowledgeBasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKnowledgeBasesRequest) ProtoMessage() {}

func (x *ListKnowledgeBasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKnowledgeBasesRequest.ProtoReflect.Descriptor instead.
func (*ListKnowledgeBasesRequest) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_knowledge_proto_rawDescGZIP(), []int{2}
}

type ListKnowledgeBasesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bases         []*KnowledgeBase       `protobuf:"bytes,1,rep,name=bases,proto3" json:"bases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKnowledgeBasesReply) Reset() {
	*x = ListKnowledgeBasesReply{}
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKnowledgeBasesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKnowledgeBasesReply) ProtoMessage() {}

func (x *ListKnowledgeBasesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKnowledgeBasesReply.ProtoReflect.Descriptor instead.
func (*ListKnowledgeBasesReply) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_knowledge_proto_rawDescGZIP(), []int{3}
}

func (x *ListKnowledgeBasesReply) GetBases() []*KnowledgeBase {
	if x != nil {
		return x.Bases
	}
	return nil
}

type CreateKnowledgeDocumentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	KnowledgeBaseId int64                  `protobuf:"varint,1,opt,name=knowledge_base_id,json=knowledgeBaseId,proto3" json:"knowledge_base_id,omitempty"`
	MediaAssetId    int64                  `protobuf:"varint,2,opt,name=media_asset_id,json=mediaAssetId,proto3" json:"media_asset_id,omitempty"`
	Title           string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateKnowledgeDocumentRequest) Reset() {
	*x = CreateKnowledgeDocumentRequest{}
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKnowledgeDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKnowledgeDocumentRequest) ProtoMessage() {}

func (x *CreateKnowledgeDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKnowledgeDocumentRequest.ProtoReflect.Descriptor instead.
func (*CreateKnowledgeDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_knowledge_proto_rawDescGZIP(), []int{4}
}

func (x *CreateKnowledgeDocumentRequest) GetKnowledgeBaseId() int64 {
	if x != nil {
		return x.KnowledgeBaseId
	}
	return 0
}

func (x *CreateKnowledgeDocumentRequest) GetMediaAssetId() int64 {
	if x != nil {
		return x.MediaAssetId
	}
	return 0
}

func (x *CreateKnowledgeDocumentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CreateKnowledgeDocumentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *KnowledgeDocument     `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKnowledgeDocumentReply) Reset() {
	*x = CreateKnowledgeDocumentReply{}
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKnowledgeDocumentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKnowledgeDocumentReply) ProtoMessage() {}

func (x *CreateKnowledgeDocumentReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKnowledgeDocumentReply.ProtoReflect.Descriptor instead.
func (*CreateKnowledgeDocumentReply) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_knowledge_proto_rawDescGZIP(), []int{5}
}

func (x *CreateKnowledgeDocumentReply) GetDocument() *KnowledgeDocument {
	if x != nil {
		return x.Document
	}
	return nil
}

type ListKnowledgeDocumentsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	KnowledgeBaseId int64                  `protobuf:"varint,1,opt,name=knowledge_base_id,json=knowledgeBaseId,proto3" json:"knowledge_base_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListKnowledgeDocumentsRequest) Reset() {
	*x = ListKnowledgeDocumentsRequest{}
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKnowledgeDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKnowledgeDocumentsRequest) ProtoMessage() {}

func (x *ListKnowledgeDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKnowledgeDocumentsRequest.ProtoReflect.Descriptor instead.
func (*ListKnowledgeDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_knowledge_proto_rawDescGZIP(), []int{6}
}

func (x *ListKnowledgeDocumentsRequest) GetKnowledgeBaseId() int64 {
	if x != nil {
		return x.KnowledgeBaseId
	}
	return 0
}

type ListKnowledgeDocumentsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*KnowledgeDocument   `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKnowledgeDocumentsReply) Reset() {
	*x = ListKnowledgeDocumentsReply{}
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKnowledgeDocumentsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKnowledgeDocumentsReply) ProtoMessage() {}

func (x *ListKnowledgeDocumentsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKnowledgeDocumentsReply.ProtoReflect.Descriptor instead.
func (*ListKnowledgeDocumentsReply) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_knowledge_proto_rawDescGZIP(), []int{7}
}

func (x *ListKnowledgeDocumentsReply) GetDocuments() []*KnowledgeDocument {
	if x != nil {
		return x.Documents
	}
	return nil
}

type ReindexKnowledgeBaseRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	KnowledgeBaseId int64                  `protobuf:"varint,1,opt,name=knowledge_base_id,json=knowledgeBaseId,proto3" json:"knowledge_base_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReindexKnowledgeBaseRequest) Reset() {
	*x = ReindexKnowledgeBaseRequest{}
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReindexKnowledgeBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReindexKnowledgeBaseRequest) ProtoMessage() {}

func (x *ReindexKnowledgeBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReindexKnowledgeBaseRequest.ProtoReflect.Descriptor instead.
func (*ReindexKnowledgeBaseRequest) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_knowledge_proto_rawDescGZIP(), []int{8}
}

func (x *ReindexKnowledgeBaseRequest) GetKnowledgeBaseId() int64 {
	if x != nil {
		return x.KnowledgeBaseId
	}
	return 0
}

type ReindexKnowledgeBaseReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReindexKnowledgeBaseReply) Reset() {
	*x = ReindexKnowledgeBaseReply{}
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReindexKnowledgeBaseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReindexKnowledgeBaseReply) ProtoMessage() {}

func (x *ReindexKnowledgeBaseReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReindexKnowledgeBaseReply.ProtoReflect.Descriptor instead.
func (*ReindexKnowledgeBaseReply) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_knowledge_proto_rawDescGZIP(), []int{9}
}

func (x *ReindexKnowledgeBaseReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type QueryKnowledgeBaseRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	KnowledgeBaseId int64                  `protobuf:"varint,1,opt,name=knowledge_base_id,json=knowledgeBaseId,proto3" json:"knowledge_base_id,omitempty"`
	Question        string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryKnowledgeBaseRequest) Reset() {
	*x = QueryKnowledgeBaseRequest{}
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryKnowledgeBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryKnowledgeBaseRequest) ProtoMessage() {}

func (x *QueryKnowledgeBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryKnowledgeBaseRequest.ProtoReflect.Descriptor instead.
func (*QueryKnowledgeBaseRequest) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_knowledge_proto_rawDescGZIP(), []int{10}
}

func (x *QueryKnowledgeBaseRequest) GetKnowledgeBaseId() int64 {
	if x != nil {
		return x.KnowledgeBaseId
	}
	return 0
}

func (x *QueryKnowledgeBaseRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type QueryKnowledgeBaseReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	Sources       []*Source              `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryKnowledgeBaseReply) Reset() {
	*x = QueryKnowledgeBaseReply{}
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryKnowledgeBaseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryKnowledgeBaseReply) ProtoMessage() {}

func (x *QueryKnowledgeBaseReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryKnowledgeBaseReply.ProtoReflect.Descriptor instead.
func (*QueryKnowledgeBaseReply) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_knowledge_proto_rawDescGZIP(), []int{11}
}

func (x *QueryKnowledgeBaseReply) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *QueryKnowledgeBaseReply) GetSources() []*Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *QueryKnowledgeBaseReply) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type ListHouseholdAIMemoriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 默认服务端按 80 条处理；0 表示使用默认上限。
	Limit         int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHouseholdAIMemoriesRequest) Reset() {
	*x = ListHouseholdAIMemoriesRequest{}
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHouseholdAIMemoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHouseholdAIMemoriesRequest) ProtoMessage() {}

func (x *ListHouseholdAIMemoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHouseholdAIMemoriesRequest.ProtoReflect.Descriptor instead.
func (*ListHouseholdAIMemoriesRequest) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_knowledge_proto_rawDescGZIP(), []int{12}
}

func (x *ListHouseholdAIMemoriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListHouseholdAIMemoriesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memories      []*HouseholdAIMemory   `protobuf:"bytes,1,rep,name=memories,proto3" json:"memories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHouseholdAIMemoriesReply) Reset() {
	*x = ListHouseholdAIMemoriesReply{}
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHouseholdAIMemoriesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHouseholdAIMemoriesReply) ProtoMessage() {}

func (x *ListHouseholdAIMemoriesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHouseholdAIMemoriesReply.ProtoReflect.Descriptor instead.
func (*ListHouseholdAIMemoriesReply) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_knowledge_proto_rawDescGZIP(), []int{13}
}

func (x *ListHouseholdAIMemoriesReply) GetMemories() []*HouseholdAIMemory {
	if x != nil {
		return x.Memories
	}
	return nil
}

type HouseholdAIMemory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	UserId        *int64                 `protobuf:"varint,5,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HouseholdAIMemory) Reset() {
	*x = HouseholdAIMemory{}
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HouseholdAIMemory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HouseholdAIMemory) ProtoMessage() {}

func (x *HouseholdAIMemory) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HouseholdAIMemory.ProtoReflect.Descriptor instead.
func (*HouseholdAIMemory) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_knowledge_proto_rawDescGZIP(), []int{14}
}

func (x *HouseholdAIMemory) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HouseholdAIMemory) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *HouseholdAIMemory) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *HouseholdAIMemory) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *HouseholdAIMemory) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *HouseholdAIMemory) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *HouseholdAIMemory) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateHouseholdAIMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHouseholdAIMemoryRequest) Reset() {
	*x = CreateHouseholdAIMemoryRequest{}
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHouseholdAIMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHouseholdAIMemoryRequest) ProtoMessage() {}

func (x *CreateHouseholdAIMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHouseholdAIMemoryRequest.ProtoReflect.Descriptor instead.
func (*CreateHouseholdAIMemoryRequest) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_knowledge_proto_rawDescGZIP(), []int{15}
}

func (x *CreateHouseholdAIMemoryRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateHouseholdAIMemoryRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type CreateHouseholdAIMemoryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHouseholdAIMemoryReply) Reset() {
	*x = CreateHouseholdAIMemoryReply{}
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHouseholdAIMemoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHouseholdAIMemoryReply) ProtoMessage() {}

func (x *CreateHouseholdAIMemoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHouseholdAIMemoryReply.ProtoReflect.Descriptor instead.
func (*CreateHouseholdAIMemoryReply) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_knowledge_proto_rawDescGZIP(), []int{16}
}

func (x *CreateHouseholdAIMemoryReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetKnowledgeIngestStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 上传图片/文件返回的 media asset id
	AssetId       int64 `protobuf:"varint,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKnowledgeIngestStatusRequest) Reset() {
	*x = GetKnowledgeIngestStatusRequest{}
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKnowledgeIngestStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnowledgeIngestStatusRequest) ProtoMessage() {}

func (x *GetKnowledgeIngestStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnowledgeIngestStatusRequest.ProtoReflect.Descriptor instead.
func (*GetKnowledgeIngestStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_knowledge_proto_rawDescGZIP(), []int{17}
}

func (x *GetKnowledgeIngestStatusRequest) GetAssetId() int64 {
	if x != nil {
		return x.AssetId
	}
	return 0
}

// 入库状态视图，对齐 biz/knowledge.go KnowledgeIngestStatusView。
// pending=true 表示文档尚未创建（排队中）；settled=true 表示无需继续轮询。
type GetKnowledgeIngestStatusReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Pending         bool                   `protobuf:"varint,1,opt,name=pending,proto3" json:"pending,omitempty"`
	Settled         bool                   `protobuf:"varint,2,opt,name=settled,proto3" json:"settled,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ProcessingStage string                 `protobuf:"bytes,4,opt,name=processing_stage,json=processingStage,proto3" json:"processing_stage,omitempty"`
	// 人类可读的进度文案（如「正在切分文本…」）
	StageLabel string `protobuf:"bytes,5,opt,name=stage_label,json=stageLabel,proto3" json:"stage_label,omitempty"`
	// 用 string 而不是 int64，避免前端 JSON 大数精度丢失（与原 JSON 协议对齐）
	DocumentId      string `protobuf:"bytes,6,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	MediaAssetId    string `protobuf:"bytes,7,opt,name=media_asset_id,json=mediaAssetId,proto3" json:"media_asset_id,omitempty"`
	Title           string `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	ChunkCount      int32  `protobuf:"varint,9,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	Retryable       bool   `protobuf:"varint,10,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Partial         bool   `protobuf:"varint,11,opt,name=partial,proto3" json:"partial,omitempty"`
	FailureReason   string `protobuf:"bytes,12,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	Summary         string `protobuf:"bytes,13,opt,name=summary,proto3" json:"summary,omitempty"`
	LastErrorKind   string `protobuf:"bytes,14,opt,name=last_error_kind,json=lastErrorKind,proto3" json:"last_error_kind,omitempty"`
	LastErrorDetail string `protobuf:"bytes,15,opt,name=last_error_detail,json=lastErrorDetail,proto3" json:"last_error_detail,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetKnowledgeIngestStatusReply) Reset() {
	*x = GetKnowledgeIngestStatusReply{}
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKnowledgeIngestStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnowledgeIngestStatusReply) ProtoMessage() {}

func (x *GetKnowledgeIngestStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnowledgeIngestStatusReply.ProtoReflect.Descriptor instead.
func (*GetKnowledgeIngestStatusReply) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_knowledge_proto_rawDescGZIP(), []int{18}
}

func (x *GetKnowledgeIngestStatusReply) GetPending() bool {
	if x != nil {
		return x.Pending
	}
	return false
}

func (x *GetKnowledgeIngestStatusReply) GetSettled() bool {
	if x != nil {
		return x.Settled
	}
	return false
}

func (x *GetKnowledgeIngestStatusReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetKnowledgeIngestStatusReply) GetProcessingStage() string {
	if x != nil {
		return x.ProcessingStage
	}
	return ""
}

func (x *GetKnowledgeIngestStatusReply) GetStageLabel() string {
	if x != nil {
		return x.StageLabel
	}
	return ""
}

func (x *GetKnowledgeIngestStatusReply) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *GetKnowledgeIngestStatusReply) GetMediaAssetId() string {
	if x != nil {
		return x.MediaAssetId
	}
	return ""
}

func (x *GetKnowledgeIngestStatusReply) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetKnowledgeIngestStatusReply) GetChunkCount() int32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

func (x *GetKnowledgeIngestStatusReply) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *GetKnowledgeIngestStatusReply) GetPartial() bool {
	if x != nil {
		return x.Partial
	}
	return false
}

func (x *GetKnowledgeIngestStatusReply) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *GetKnowledgeIngestStatusReply) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *GetKnowledgeIngestStatusReply) GetLastErrorKind() string {
	if x != nil {
		return x.LastErrorKind
	}
	return ""
}

func (x *GetKnowledgeIngestStatusReply) GetLastErrorDetail() string {
	if x != nil {
		return x.LastErrorDetail
	}
	return ""
}

type RetryKnowledgeDocumentRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	DocumentId int64                  `protobuf:"varint,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	// 可选：触发该文档原属的 AI session 上下文（用于通知绑定）
	SessionId     *int64 `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3,oneof" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryKnowledgeDocumentRequest) Reset() {
	*x = RetryKnowledgeDocumentRequest{}
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryKnowledgeDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryKnowledgeDocumentRequest) ProtoMessage() {}

func (x *RetryKnowledgeDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryKnowledgeDocumentRequest.ProtoReflect.Descriptor instead.
func (*RetryKnowledgeDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_knowledge_proto_rawDescGZIP(), []int{19}
}

func (x *RetryKnowledgeDocumentRequest) GetDocumentId() int64 {
	if x != nil {
		return x.DocumentId
	}
	return 0
}

func (x *RetryKnowledgeDocumentRequest) GetSessionId() int64 {
	if x != nil && x.SessionId != nil {
		return *x.SessionId
	}
	return 0
}

type RetryKnowledgeDocumentReply struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Accepted bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// 用 string ID 避免前端大数精度丢失（与原 JSON 协议对齐）
	DocumentId      string `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	MediaAssetId    string `protobuf:"bytes,3,opt,name=media_asset_id,json=mediaAssetId,proto3" json:"media_asset_id,omitempty"`
	Title           string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	ProcessingStage string `protobuf:"bytes,5,opt,name=processing_stage,json=processingStage,proto3" json:"processing_stage,omitempty"`
	Status          string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	StageLabel      string `protobuf:"bytes,7,opt,name=stage_label,json=stageLabel,proto3" json:"stage_label,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RetryKnowledgeDocumentReply) Reset() {
	*x = RetryKnowledgeDocumentReply{}
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryKnowledgeDocumentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryKnowledgeDocumentReply) ProtoMessage() {}

func (x *RetryKnowledgeDocumentReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_knowledge_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryKnowledgeDocumentReply.ProtoReflect.Descriptor instead.
func (*RetryKnowledgeDocumentReply) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_knowledge_proto_rawDescGZIP(), []int{20}
}

func (x *RetryKnowledgeDocumentReply) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RetryKnowledgeDocumentReply) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *RetryKnowledgeDocumentReply) GetMediaAssetId() string {
	if x != nil {
		return x.MediaAssetId
	}
	return ""
}

func (x *RetryKnowledgeDocumentReply) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RetryKnowledgeDocumentReply) GetProcessingStage() string {
	if x != nil {
		return x.ProcessingStage
	}
	return ""
}

func (x *RetryKnowledgeDocumentReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RetryKnowledgeDocumentReply) GetStageLabel() string {
	if x != nil {
		return x.StageLabel
	}
	return ""
}

var File_api_aicook_v1_knowledge_proto protoreflect.FileDescriptor

const file_api_aicook_v1_knowledge_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/aicook/v1/knowledge.proto\x12\taicook.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1aapi/aicook/v1/common.proto\"R\n" +
	"\x1aCreateKnowledgeBaseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"H\n" +
	"\x18CreateKnowledgeBaseReply\x12,\n" +
	"\x04base\x18\x01 \x01(\v2\x18.aicook.v1.KnowledgeBaseR\x04base\"\x1b\n" +
	"\x19ListKnowledgeBasesRequest\"I\n" +
	"\x17ListKnowledgeBasesReply\x12.\n" +
	"\x05bases\x18\x01 \x03(\v2\x18.aicook.v1.KnowledgeBaseR\x05bases\"\x88\x01\n" +
	"\x1eCreateKnowledgeDocumentRequest\x12*\n" +
	"\x11knowledge_base_id\x18\x01 \x01(\x03R\x0fknowledgeBaseId\x12$\n" +
	"\x0emedia_asset_id\x18\x02 \x01(\x03R\fmediaAssetId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\"X\n" +
	"\x1cCreateKnowledgeDocumentReply\x128\n" +
	"\bdocument\x18\x01 \x01(\v2\x1c.aicook.v1.KnowledgeDocumentR\bdocument\"K\n" +
	"\x1dListKnowledgeDocumentsRequest\x12*\n" +
	"\x11knowledge_base_id\x18\x01 \x01(\x03R\x0fknowledgeBaseId\"Y\n" +
	"\x1bListKnowledgeDocumentsReply\x12:\n" +
	"\tdocuments\x18\x01 \x03(\v2\x1c.aicook.v1.KnowledgeDocumentR\tdocuments\"I\n" +
	"\x1bReindexKnowledgeBaseRequest\x12*\n" +
	"\x11knowledge_base_id\x18\x01 \x01(\x03R\x0fknowledgeBaseId\"3\n" +
	"\x19ReindexKnowledgeBaseReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"c\n" +
	"\x19QueryKnowledgeBaseRequest\x12*\n" +
	"\x11knowledge_base_id\x18\x01 \x01(\x03R\x0fknowledgeBaseId\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\"r\n" +
	"\x17QueryKnowledgeBaseReply\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x12+\n" +
	"\asources\x18\x02 \x03(\v2\x11.aicook.v1.SourceR\asources\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\"6\n" +
	"\x1eListHouseholdAIMemoriesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"X\n" +
	"\x1cListHouseholdAIMemoriesReply\x128\n" +
	"\bmemories\x18\x01 \x03(\v2\x1c.aicook.v1.HouseholdAIMemoryR\bmemories\"\x8b\x02\n" +
	"\x11HouseholdAIMemory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x1c\n" +
	"\auser_id\x18\x05 \x01(\x03H\x00R\x06userId\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\n" +
	"\n" +
	"\b_user_id\"P\n" +
	"\x1eCreateHouseholdAIMemoryRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\".\n" +
	"\x1cCreateHouseholdAIMemoryReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"<\n" +
	"\x1fGetKnowledgeIngestStatusRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\x03R\aassetId\"\x82\x04\n" +
	"\x1dGetKnowledgeIngestStatusReply\x12\x18\n" +
	"\apending\x18\x01 \x01(\bR\apending\x12\x18\n" +
	"\asettled\x18\x02 \x01(\bR\asettled\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12)\n" +
	"\x10processing_stage\x18\x04 \x01(\tR\x0fprocessingStage\x12\x1f\n" +
	"\vstage_label\x18\x05 \x01(\tR\n" +
	"stageLabel\x12\x1f\n" +
	"\vdocument_id\x18\x06 \x01(\tR\n" +
	"documentId\x12$\n" +
	"\x0emedia_asset_id\x18\a \x01(\tR\fmediaAssetId\x12\x14\n" +
	"\x05title\x18\b \x01(\tR\x05title\x12\x1f\n" +
	"\vchunk_count\x18\t \x01(\x05R\n" +
	"chunkCount\x12\x1c\n" +
	"\tretryable\x18\n" +
	" \x01(\bR\tretryable\x12\x18\n" +
	"\apartial\x18\v \x01(\bR\apartial\x12%\n" +
	"\x0efailure_reason\x18\f \x01(\tR\rfailureReason\x12\x18\n" +
	"\asummary\x18\r \x01(\tR\asummary\x12&\n" +
	"\x0flast_error_kind\x18\x0e \x01(\tR\rlastErrorKind\x12*\n" +
	"\x11last_error_detail\x18\x0f \x01(\tR\x0flastErrorDetail\"s\n" +
	"\x1dRetryKnowledgeDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\x03R\n" +
	"documentId\x12\"\n" +
	"\n" +
	"session_id\x18\x02 \x01(\x03H\x00R\tsessionId\x88\x01\x01B\r\n" +
	"\v_session_id\"\xfa\x01\n" +
	"\x1bRetryKnowledgeDocumentReply\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12$\n" +
	"\x0emedia_asset_id\x18\x03 \x01(\tR\fmediaAssetId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12)\n" +
	"\x10processing_stage\x18\x05 \x01(\tR\x0fprocessingStage\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1f\n" +
	"\vstage_label\x18\a \x01(\tR\n" +
	"stageLabel2\xb5\f\n" +
	"\x10KnowledgeService\x12\x85\x01\n" +
	"\x13CreateKnowledgeBase\x12%.aicook.v1.CreateKnowledgeBaseRequest\x1a#.aicook.v1.CreateKnowledgeBaseReply\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v1/knowledge-bases\x12\x7f\n" +
	"\x12ListKnowledgeBases\x12$.aicook.v1.ListKnowledgeBasesRequest\x1a\".aicook.v1.ListKnowledgeBasesReply\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/knowledge-bases\x12\xaf\x01\n" +
	"\x17CreateKnowledgeDocument\x12).aicook.v1.CreateKnowledgeDocumentRequest\x1a'.aicook.v1.CreateKnowledgeDocumentReply\"@\x82\xd3\xe4\x93\x02::\x01*\"5/api/v1/knowledge-bases/{knowledge_base_id}/documents\x12\xa9\x01\n" +
	"\x16ListKnowledgeDocuments\x12(.aicook.v1.ListKnowledgeDocumentsRequest\x1a&.aicook.v1.ListKnowledgeDocumentsReply\"=\x82\xd3\xe4\x93\x027\x125/api/v1/knowledge-bases/{knowledge_base_id}/documents\x12\xa4\x01\n" +
	"\x14ReindexKnowledgeBase\x12&.aicook.v1.ReindexKnowledgeBaseRequest\x1a$.aicook.v1.ReindexKnowledgeBaseReply\">\x82\xd3\xe4\x93\x028:\x01*\"3/api/v1/knowledge-bases/{knowledge_base_id}/reindex\x12\x9c\x01\n" +
	"\x12QueryKnowledgeBase\x12$.aicook.v1.QueryKnowledgeBaseRequest\x1a\".aicook.v1.QueryKnowledgeBaseReply\"<\x82\xd3\xe4\x93\x026:\x01*\"1/api/v1/knowledge-bases/{knowledge_base_id}/query\x12\x94\x01\n" +
	"\x17ListHouseholdAIMemories\x12).aicook.v1.ListHouseholdAIMemoriesRequest\x1a'.aicook.v1.ListHouseholdAIMemoriesReply\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/household-ai-memories\x12\x97\x01\n" +
	"\x17CreateHouseholdAIMemory\x12).aicook.v1.CreateHouseholdAIMemoryRequest\x1a'.aicook.v1.CreateHouseholdAIMemoryReply\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/household-ai-memories\x12\x99\x01\n" +
	"\x18GetKnowledgeIngestStatus\x12*.aicook.v1.GetKnowledgeIngestStatusRequest\x1a(.aicook.v1.GetKnowledgeIngestStatusReply\"'\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/knowledge/ingest-status\x12\xa6\x01\n" +
	"\x16RetryKnowledgeDocument\x12(.aicook.v1.RetryKnowledgeDocumentRequest\x1a&.aicook.v1.RetryKnowledgeDocumentReply\":\x82\xd3\xe4\x93\x024:\x01*\"//api/v1/knowledge/documents/{document_id}/retryB7Z5github.com/chengjiang/aicook/backend/api/aicook/v1;v1b\x06proto3"

var (
	file_api_aicook_v1_knowledge_proto_rawDescOnce sync.Once
	file_api_aicook_v1_knowledge_proto_rawDescData []byte
)

func file_api_aicook_v1_knowledge_proto_rawDescGZIP() []byte {
	file_api_aicook_v1_knowledge_proto_rawDescOnce.Do(func() {
		file_api_aicook_v1_knowledge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_aicook_v1_knowledge_proto_rawDesc), len(file_api_aicook_v1_knowledge_proto_rawDesc)))
	})
	return file_api_aicook_v1_knowledge_proto_rawDescData
}

var file_api_aicook_v1_knowledge_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_aicook_v1_knowledge_proto_goTypes = []any{
	(*CreateKnowledgeBaseRequest)(nil),      // 0: aicook.v1.CreateKnowledgeBaseRequest
	(*CreateKnowledgeBaseReply)(nil),        // 1: aicook.v1.CreateKnowledgeBaseReply
	(*ListKnowledgeBasesRequest)(nil),       // 2: aicook.v1.ListKnowledgeBasesRequest
	(*ListKnowledgeBasesReply)(nil),         // 3: aicook.v1.ListKnowledgeBasesReply
	(*CreateKnowledgeDocumentRequest)(nil),  // 4: aicook.v1.CreateKnowledgeDocumentRequest
	(*CreateKnowledgeDocumentReply)(nil),    // 5: aicook.v1.CreateKnowledgeDocumentReply
	(*ListKnowledgeDocumentsRequest)(nil),   // 6: aicook.v1.ListKnowledgeDocumentsRequest
	(*ListKnowledgeDocumentsReply)(nil),     // 7: aicook.v1.ListKnowledgeDocumentsReply
	(*ReindexKnowledgeBaseRequest)(nil),     // 8: aicook.v1.ReindexKnowledgeBaseRequest
	(*ReindexKnowledgeBaseReply)(nil),       // 9: aicook.v1.ReindexKnowledgeBaseReply
	(*QueryKnowledgeBaseRequest)(nil),       // 10: aicook.v1.QueryKnowledgeBaseRequest
	(*QueryKnowledgeBaseReply)(nil),         // 11: aicook.v1.QueryKnowledgeBaseReply
	(*ListHouseholdAIMemoriesRequest)(nil),  // 12: aicook.v1.ListHouseholdAIMemoriesRequest
	(*ListHouseholdAIMemoriesReply)(nil),    // 13: aicook.v1.ListHouseholdAIMemoriesReply
	(*HouseholdAIMemory)(nil),               // 14: aicook.v1.HouseholdAIMemory
	(*CreateHouseholdAIMemoryRequest)(nil),  // 15: aicook.v1.CreateHouseholdAIMemoryRequest
	(*CreateHouseholdAIMemoryReply)(nil),    // 16: aicook.v1.CreateHouseholdAIMemoryReply
	(*GetKnowledgeIngestStatusRequest)(nil), // 17: aicook.v1.GetKnowledgeIngestStatusRequest
	(*GetKnowledgeIngestStatusReply)(nil),   // 18: aicook.v1.GetKnowledgeIngestStatusReply
	(*RetryKnowledgeDocumentRequest)(nil),   // 19: aicook.v1.RetryKnowledgeDocumentRequest
	(*RetryKnowledgeDocumentReply)(nil),     // 20: aicook.v1.RetryKnowledgeDocumentReply
	(*KnowledgeBase)(nil),                   // 21: aicook.v1.KnowledgeBase
	(*KnowledgeDocument)(nil),               // 22: aicook.v1.KnowledgeDocument
	(*Source)(nil),                          // 23: aicook.v1.Source
	(*timestamppb.Timestamp)(nil),           // 24: google.protobuf.Timestamp
}
var file_api_aicook_v1_knowledge_proto_depIdxs = []int32{
	21, // 0: aicook.v1.CreateKnowledgeBaseReply.base:type_name -> aicook.v1.KnowledgeBase
	21, // 1: aicook.v1.ListKnowledgeBasesReply.bases:type_name -> aicook.v1.KnowledgeBase
	22, // 2: aicook.v1.CreateKnowledgeDocumentReply.document:type_name -> aicook.v1.KnowledgeDocument
	22, // 3: aicook.v1.ListKnowledgeDocumentsReply.documents:type_name -> aicook.v1.KnowledgeDocument
	23, // 4: aicook.v1.QueryKnowledgeBaseReply.sources:type_name -> aicook.v1.Source
	14, // 5: aicook.v1.ListHouseholdAIMemoriesReply.memories:type_name -> aicook.v1.HouseholdAIMemory
	24, // 6: aicook.v1.HouseholdAIMemory.created_at:type_name -> google.protobuf.Timestamp
	24, // 7: aicook.v1.HouseholdAIMemory.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 8: aicook.v1.KnowledgeService.CreateKnowledgeBase:input_type -> aicook.v1.CreateKnowledgeBaseRequest
	2,  // 9: aicook.v1.KnowledgeService.ListKnowledgeBases:input_type -> aicook.v1.ListKnowledgeBasesRequest
	4,  // 10: aicook.v1.KnowledgeService.CreateKnowledgeDocument:input_type -> aicook.v1.CreateKnowledgeDocumentRequest
	6,  // 11: aicook.v1.KnowledgeService.ListKnowledgeDocuments:input_type -> aicook.v1.ListKnowledgeDocumentsRequest
	8,  // 12: aicook.v1.KnowledgeService.ReindexKnowledgeBase:input_type -> aicook.v1.ReindexKnowledgeBaseRequest
	10, // 13: aicook.v1.KnowledgeService.QueryKnowledgeBase:input_type -> aicook.v1.QueryKnowledgeBaseRequest
	12, // 14: aicook.v1.KnowledgeService.ListHouseholdAIMemories:input_type -> aicook.v1.ListHouseholdAIMemoriesRequest
	15, // 15: aicook.v1.KnowledgeService.CreateHouseholdAIMemory:input_type -> aicook.v1.CreateHouseholdAIMemoryRequest
	17, // 16: aicook.v1.KnowledgeService.GetKnowledgeIngestStatus:input_type -> aicook.v1.GetKnowledgeIngestStatusRequest
	19, // 17: aicook.v1.KnowledgeService.RetryKnowledgeDocument:input_type -> aicook.v1.RetryKnowledgeDocumentRequest
	1,  // 18: aicook.v1.KnowledgeService.CreateKnowledgeBase:output_type -> aicook.v1.CreateKnowledgeBaseReply
	3,  // 19: aicook.v1.KnowledgeService.ListKnowledgeBases:output_type -> aicook.v1.ListKnowledgeBasesReply
	5,  // 20: aicook.v1.KnowledgeService.CreateKnowledgeDocument:output_type -> aicook.v1.CreateKnowledgeDocumentReply
	7,  // 21: aicook.v1.KnowledgeService.ListKnowledgeDocuments:output_type -> aicook.v1.ListKnowledgeDocumentsReply
	9,  // 22: aicook.v1.KnowledgeService.ReindexKnowledgeBase:output_type -> aicook.v1.ReindexKnowledgeBaseReply
	11, // 23: aicook.v1.KnowledgeService.QueryKnowledgeBase:output_type -> aicook.v1.QueryKnowledgeBaseReply
	13, // 24: aicook.v1.KnowledgeService.ListHouseholdAIMemories:output_type -> aicook.v1.ListHouseholdAIMemoriesReply
	16, // 25: aicook.v1.KnowledgeService.CreateHouseholdAIMemory:output_type -> aicook.v1.CreateHouseholdAIMemoryReply
	18, // 26: aicook.v1.KnowledgeService.GetKnowledgeIngestStatus:output_type -> aicook.v1.GetKnowledgeIngestStatusReply
	20, // 27: aicook.v1.KnowledgeService.RetryKnowledgeDocument:output_type -> aicook.v1.RetryKnowledgeDocumentReply
	18, // [18:28] is the sub-list for method output_type
	8,  // [8:18] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_api_aicook_v1_knowledge_proto_init() }
func file_api_aicook_v1_knowledge_proto_init() {
	if File_api_aicook_v1_knowledge_proto != nil {
		return
	}
	file_api_aicook_v1_common_proto_init()
	file_api_aicook_v1_knowledge_proto_msgTypes[14].OneofWrappers = []any{}
	file_api_aicook_v1_knowledge_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_aicook_v1_knowledge_proto_rawDesc), len(file_api_aicook_v1_knowledge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_aicook_v1_knowledge_proto_goTypes,
		DependencyIndexes: file_api_aicook_v1_knowledge_proto_depIdxs,
		MessageInfos:      file_api_aicook_v1_knowledge_proto_msgTypes,
	}.Build()
	File_api_aicook_v1_knowledge_proto = out.File
	file_api_aicook_v1_knowledge_proto_goTypes = nil
	file_api_aicook_v1_knowledge_proto_depIdxs = nil
}
