// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: api/aicook/v1/knowledge.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KnowledgeService_CreateKnowledgeBase_FullMethodName      = "/aicook.v1.KnowledgeService/CreateKnowledgeBase"
	KnowledgeService_ListKnowledgeBases_FullMethodName       = "/aicook.v1.KnowledgeService/ListKnowledgeBases"
	KnowledgeService_CreateKnowledgeDocument_FullMethodName  = "/aicook.v1.KnowledgeService/CreateKnowledgeDocument"
	KnowledgeService_ListKnowledgeDocuments_FullMethodName   = "/aicook.v1.KnowledgeService/ListKnowledgeDocuments"
	KnowledgeService_ReindexKnowledgeBase_FullMethodName     = "/aicook.v1.KnowledgeService/ReindexKnowledgeBase"
	KnowledgeService_QueryKnowledgeBase_FullMethodName       = "/aicook.v1.KnowledgeService/QueryKnowledgeBase"
	KnowledgeService_ListHouseholdAIMemories_FullMethodName  = "/aicook.v1.KnowledgeService/ListHouseholdAIMemories"
	KnowledgeService_CreateHouseholdAIMemory_FullMethodName  = "/aicook.v1.KnowledgeService/CreateHouseholdAIMemory"
	KnowledgeService_GetKnowledgeIngestStatus_FullMethodName = "/aicook.v1.KnowledgeService/GetKnowledgeIngestStatus"
	KnowledgeService_RetryKnowledgeDocument_FullMethodName   = "/aicook.v1.KnowledgeService/RetryKnowledgeDocument"
)

// KnowledgeServiceClient is the client API for KnowledgeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KnowledgeServiceClient interface {
	CreateKnowledgeBase(ctx context.Context, in *CreateKnowledgeBaseRequest, opts ...grpc.CallOption) (*CreateKnowledgeBaseReply, error)
	ListKnowledgeBases(ctx context.Context, in *ListKnowledgeBasesRequest, opts ...grpc.CallOption) (*ListKnowledgeBasesReply, error)
	CreateKnowledgeDocument(ctx context.Context, in *CreateKnowledgeDocumentRequest, opts ...grpc.CallOption) (*CreateKnowledgeDocumentReply, error)
	ListKnowledgeDocuments(ctx context.Context, in *ListKnowledgeDocumentsRequest, opts ...grpc.CallOption) (*ListKnowledgeDocumentsReply, error)
	ReindexKnowledgeBase(ctx context.Context, in *ReindexKnowledgeBaseRequest, opts ...grpc.CallOption) (*ReindexKnowledgeBaseReply, error)
	QueryKnowledgeBase(ctx context.Context, in *QueryKnowledgeBaseRequest, opts ...grpc.CallOption) (*QueryKnowledgeBaseReply, error)
	ListHouseholdAIMemories(ctx context.Context, in *ListHouseholdAIMemoriesRequest, opts ...grpc.CallOption) (*ListHouseholdAIMemoriesReply, error)
	CreateHouseholdAIMemory(ctx context.Context, in *CreateHouseholdAIMemoryRequest, opts ...grpc.CallOption) (*CreateHouseholdAIMemoryReply, error)
	// 查询某次上传 media_asset 对应的知识入库（chunk 化、索引化）状态。
	// 用于厨艺 AI 聊天附件入库进度轮询。
	GetKnowledgeIngestStatus(ctx context.Context, in *GetKnowledgeIngestStatusRequest, opts ...grpc.CallOption) (*GetKnowledgeIngestStatusReply, error)
	// 失败/部分失败时手工触发某文档的重新入库。
	RetryKnowledgeDocument(ctx context.Context, in *RetryKnowledgeDocumentRequest, opts ...grpc.CallOption) (*RetryKnowledgeDocumentReply, error)
}

type knowledgeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKnowledgeServiceClient(cc grpc.ClientConnInterface) KnowledgeServiceClient {
	return &knowledgeServiceClient{cc}
}

func (c *knowledgeServiceClient) CreateKnowledgeBase(ctx context.Context, in *CreateKnowledgeBaseRequest, opts ...grpc.CallOption) (*CreateKnowledgeBaseReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateKnowledgeBaseReply)
	err := c.cc.Invoke(ctx, KnowledgeService_CreateKnowledgeBase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) ListKnowledgeBases(ctx context.Context, in *ListKnowledgeBasesRequest, opts ...grpc.CallOption) (*ListKnowledgeBasesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListKnowledgeBasesReply)
	err := c.cc.Invoke(ctx, KnowledgeService_ListKnowledgeBases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) CreateKnowledgeDocument(ctx context.Context, in *CreateKnowledgeDocumentRequest, opts ...grpc.CallOption) (*CreateKnowledgeDocumentReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateKnowledgeDocumentReply)
	err := c.cc.Invoke(ctx, KnowledgeService_CreateKnowledgeDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) ListKnowledgeDocuments(ctx context.Context, in *ListKnowledgeDocumentsRequest, opts ...grpc.CallOption) (*ListKnowledgeDocumentsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListKnowledgeDocumentsReply)
	err := c.cc.Invoke(ctx, KnowledgeService_ListKnowledgeDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) ReindexKnowledgeBase(ctx context.Context, in *ReindexKnowledgeBaseRequest, opts ...grpc.CallOption) (*ReindexKnowledgeBaseReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReindexKnowledgeBaseReply)
	err := c.cc.Invoke(ctx, KnowledgeService_ReindexKnowledgeBase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) QueryKnowledgeBase(ctx context.Context, in *QueryKnowledgeBaseRequest, opts ...grpc.CallOption) (*QueryKnowledgeBaseReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryKnowledgeBaseReply)
	err := c.cc.Invoke(ctx, KnowledgeService_QueryKnowledgeBase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) ListHouseholdAIMemories(ctx context.Context, in *ListHouseholdAIMemoriesRequest, opts ...grpc.CallOption) (*ListHouseholdAIMemoriesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHouseholdAIMemoriesReply)
	err := c.cc.Invoke(ctx, KnowledgeService_ListHouseholdAIMemories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) CreateHouseholdAIMemory(ctx context.Context, in *CreateHouseholdAIMemoryRequest, opts ...grpc.CallOption) (*CreateHouseholdAIMemoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateHouseholdAIMemoryReply)
	err := c.cc.Invoke(ctx, KnowledgeService_CreateHouseholdAIMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) GetKnowledgeIngestStatus(ctx context.Context, in *GetKnowledgeIngestStatusRequest, opts ...grpc.CallOption) (*GetKnowledgeIngestStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKnowledgeIngestStatusReply)
	err := c.cc.Invoke(ctx, KnowledgeService_GetKnowledgeIngestStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeServiceClient) RetryKnowledgeDocument(ctx context.Context, in *RetryKnowledgeDocumentRequest, opts ...grpc.CallOption) (*RetryKnowledgeDocumentReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryKnowledgeDocumentReply)
	err := c.cc.Invoke(ctx, KnowledgeService_RetryKnowledgeDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KnowledgeServiceServer is the server API for KnowledgeService service.
// All implementations should embed UnimplementedKnowledgeServiceServer
// for forward compatibility.
type KnowledgeServiceServer interface {
	CreateKnowledgeBase(context.Context, *CreateKnowledgeBaseRequest) (*CreateKnowledgeBaseReply, error)
	ListKnowledgeBases(context.Context, *ListKnowledgeBasesRequest) (*ListKnowledgeBasesReply, error)
	CreateKnowledgeDocument(context.Context, *CreateKnowledgeDocumentRequest) (*CreateKnowledgeDocumentReply, error)
	ListKnowledgeDocuments(context.Context, *ListKnowledgeDocumentsRequest) (*ListKnowledgeDocumentsReply, error)
	ReindexKnowledgeBase(context.Context, *ReindexKnowledgeBaseRequest) (*ReindexKnowledgeBaseReply, error)
	QueryKnowledgeBase(context.Context, *QueryKnowledgeBaseRequest) (*QueryKnowledgeBaseReply, error)
	ListHouseholdAIMemories(context.Context, *ListHouseholdAIMemoriesRequest) (*ListHouseholdAIMemoriesReply, error)
	CreateHouseholdAIMemory(context.Context, *CreateHouseholdAIMemoryRequest) (*CreateHouseholdAIMemoryReply, error)
	// 查询某次上传 media_asset 对应的知识入库（chunk 化、索引化）状态。
	// 用于厨艺 AI 聊天附件入库进度轮询。
	GetKnowledgeIngestStatus(context.Context, *GetKnowledgeIngestStatusRequest) (*GetKnowledgeIngestStatusReply, error)
	// 失败/部分失败时手工触发某文档的重新入库。
	RetryKnowledgeDocument(context.Context, *RetryKnowledgeDocumentRequest) (*RetryKnowledgeDocumentReply, error)
}

// UnimplementedKnowledgeServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKnowledgeServiceServer struct{}

func (UnimplementedKnowledgeServiceServer) CreateKnowledgeBase(context.Context, *CreateKnowledgeBaseRequest) (*CreateKnowledgeBaseReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateKnowledgeBase not implemented")
}
func (UnimplementedKnowledgeServiceServer) ListKnowledgeBases(context.Context, *ListKnowledgeBasesRequest) (*ListKnowledgeBasesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListKnowledgeBases not implemented")
}
func (UnimplementedKnowledgeServiceServer) CreateKnowledgeDocument(context.Context, *CreateKnowledgeDocumentRequest) (*CreateKnowledgeDocumentReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateKnowledgeDocument not implemented")
}
func (UnimplementedKnowledgeServiceServer) ListKnowledgeDocuments(context.Context, *ListKnowledgeDocumentsRequest) (*ListKnowledgeDocumentsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListKnowledgeDocuments not implemented")
}
func (UnimplementedKnowledgeServiceServer) ReindexKnowledgeBase(context.Context, *ReindexKnowledgeBaseRequest) (*ReindexKnowledgeBaseReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ReindexKnowledgeBase not implemented")
}
func (UnimplementedKnowledgeServiceServer) QueryKnowledgeBase(context.Context, *QueryKnowledgeBaseRequest) (*QueryKnowledgeBaseReply, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryKnowledgeBase not implemented")
}
func (UnimplementedKnowledgeServiceServer) ListHouseholdAIMemories(context.Context, *ListHouseholdAIMemoriesRequest) (*ListHouseholdAIMemoriesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHouseholdAIMemories not implemented")
}
func (UnimplementedKnowledgeServiceServer) CreateHouseholdAIMemory(context.Context, *CreateHouseholdAIMemoryRequest) (*CreateHouseholdAIMemoryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateHouseholdAIMemory not implemented")
}
func (UnimplementedKnowledgeServiceServer) GetKnowledgeIngestStatus(context.Context, *GetKnowledgeIngestStatusRequest) (*GetKnowledgeIngestStatusReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKnowledgeIngestStatus not implemented")
}
func (UnimplementedKnowledgeServiceServer) RetryKnowledgeDocument(context.Context, *RetryKnowledgeDocumentRequest) (*RetryKnowledgeDocumentReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryKnowledgeDocument not implemented")
}
func (UnimplementedKnowledgeServiceServer) testEmbeddedByValue() {}

// UnsafeKnowledgeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KnowledgeServiceServer will
// result in compilation errors.
type UnsafeKnowledgeServiceServer interface {
	mustEmbedUnimplementedKnowledgeServiceServer()
}

func RegisterKnowledgeServiceServer(s grpc.ServiceRegistrar, srv KnowledgeServiceServer) {
	// If the following call panics, it indicates UnimplementedKnowledgeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KnowledgeService_ServiceDesc, srv)
}

func _KnowledgeService_CreateKnowledgeBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKnowledgeBaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).CreateKnowledgeBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_CreateKnowledgeBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).CreateKnowledgeBase(ctx, req.(*CreateKnowledgeBaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_ListKnowledgeBases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKnowledgeBasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).ListKnowledgeBases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_ListKnowledgeBases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).ListKnowledgeBases(ctx, req.(*ListKnowledgeBasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_CreateKnowledgeDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKnowledgeDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).CreateKnowledgeDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_CreateKnowledgeDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).CreateKnowledgeDocument(ctx, req.(*CreateKnowledgeDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_ListKnowledgeDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKnowledgeDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).ListKnowledgeDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_ListKnowledgeDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).ListKnowledgeDocuments(ctx, req.(*ListKnowledgeDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_ReindexKnowledgeBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReindexKnowledgeBaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).ReindexKnowledgeBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_ReindexKnowledgeBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).ReindexKnowledgeBase(ctx, req.(*ReindexKnowledgeBaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_QueryKnowledgeBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryKnowledgeBaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).QueryKnowledgeBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_QueryKnowledgeBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).QueryKnowledgeBase(ctx, req.(*QueryKnowledgeBaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_ListHouseholdAIMemories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHouseholdAIMemoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).ListHouseholdAIMemories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_ListHouseholdAIMemories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).ListHouseholdAIMemories(ctx, req.(*ListHouseholdAIMemoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_CreateHouseholdAIMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHouseholdAIMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).CreateHouseholdAIMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_CreateHouseholdAIMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).CreateHouseholdAIMemory(ctx, req.(*CreateHouseholdAIMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_GetKnowledgeIngestStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKnowledgeIngestStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).GetKnowledgeIngestStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_GetKnowledgeIngestStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).GetKnowledgeIngestStatus(ctx, req.(*GetKnowledgeIngestStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeService_RetryKnowledgeDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryKnowledgeDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeServiceServer).RetryKnowledgeDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeService_RetryKnowledgeDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeServiceServer).RetryKnowledgeDocument(ctx, req.(*RetryKnowledgeDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KnowledgeService_ServiceDesc is the grpc.ServiceDesc for KnowledgeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KnowledgeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aicook.v1.KnowledgeService",
	HandlerType: (*KnowledgeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateKnowledgeBase",
			Handler:    _KnowledgeService_CreateKnowledgeBase_Handler,
		},
		{
			MethodName: "ListKnowledgeBases",
			Handler:    _KnowledgeService_ListKnowledgeBases_Handler,
		},
		{
			MethodName: "CreateKnowledgeDocument",
			Handler:    _KnowledgeService_CreateKnowledgeDocument_Handler,
		},
		{
			MethodName: "ListKnowledgeDocuments",
			Handler:    _KnowledgeService_ListKnowledgeDocuments_Handler,
		},
		{
			MethodName: "ReindexKnowledgeBase",
			Handler:    _KnowledgeService_ReindexKnowledgeBase_Handler,
		},
		{
			MethodName: "QueryKnowledgeBase",
			Handler:    _KnowledgeService_QueryKnowledgeBase_Handler,
		},
		{
			MethodName: "ListHouseholdAIMemories",
			Handler:    _KnowledgeService_ListHouseholdAIMemories_Handler,
		},
		{
			MethodName: "CreateHouseholdAIMemory",
			Handler:    _KnowledgeService_CreateHouseholdAIMemory_Handler,
		},
		{
			MethodName: "GetKnowledgeIngestStatus",
			Handler:    _KnowledgeService_GetKnowledgeIngestStatus_Handler,
		},
		{
			MethodName: "RetryKnowledgeDocument",
			Handler:    _KnowledgeService_RetryKnowledgeDocument_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/aicook/v1/knowledge.proto",
}
