// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: api/aicook/v1/media.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMediaServiceCompleteMediaUpload = "/aicook.v1.MediaService/CompleteMediaUpload"
const OperationMediaServicePrepareMediaUpload = "/aicook.v1.MediaService/PrepareMediaUpload"

type MediaServiceHTTPServer interface {
	CompleteMediaUpload(context.Context, *CompleteMediaUploadRequest) (*CompleteMediaUploadReply, error)
	PrepareMediaUpload(context.Context, *PrepareMediaUploadRequest) (*PrepareMediaUploadReply, error)
}

func RegisterMediaServiceHTTPServer(s *http.Server, srv MediaServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/media/uploads:prepare", _MediaService_PrepareMediaUpload0_HTTP_Handler(srv))
	r.POST("/api/v1/media/uploads/{asset_id}:complete", _MediaService_CompleteMediaUpload0_HTTP_Handler(srv))
}

func _MediaService_PrepareMediaUpload0_HTTP_Handler(srv MediaServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PrepareMediaUploadRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMediaServicePrepareMediaUpload)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.PrepareMediaUpload(ctx, req.(*PrepareMediaUploadRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PrepareMediaUploadReply)
		return ctx.Result(200, reply)
	}
}

func _MediaService_CompleteMediaUpload0_HTTP_Handler(srv MediaServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CompleteMediaUploadRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMediaServiceCompleteMediaUpload)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CompleteMediaUpload(ctx, req.(*CompleteMediaUploadRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CompleteMediaUploadReply)
		return ctx.Result(200, reply)
	}
}

type MediaServiceHTTPClient interface {
	CompleteMediaUpload(ctx context.Context, req *CompleteMediaUploadRequest, opts ...http.CallOption) (rsp *CompleteMediaUploadReply, err error)
	PrepareMediaUpload(ctx context.Context, req *PrepareMediaUploadRequest, opts ...http.CallOption) (rsp *PrepareMediaUploadReply, err error)
}

type MediaServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewMediaServiceHTTPClient(client *http.Client) MediaServiceHTTPClient {
	return &MediaServiceHTTPClientImpl{client}
}

func (c *MediaServiceHTTPClientImpl) CompleteMediaUpload(ctx context.Context, in *CompleteMediaUploadRequest, opts ...http.CallOption) (*CompleteMediaUploadReply, error) {
	var out CompleteMediaUploadReply
	pattern := "/api/v1/media/uploads/{asset_id}:complete"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMediaServiceCompleteMediaUpload))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MediaServiceHTTPClientImpl) PrepareMediaUpload(ctx context.Context, in *PrepareMediaUploadRequest, opts ...http.CallOption) (*PrepareMediaUploadReply, error) {
	var out PrepareMediaUploadReply
	pattern := "/api/v1/media/uploads:prepare"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMediaServicePrepareMediaUpload))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
