// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/aicook/v1/recipe.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListRecipesRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Limit        int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Keyword      string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	KitchenTag   string                 `protobuf:"bytes,3,opt,name=kitchen_tag,json=kitchenTag,proto3" json:"kitchen_tag,omitempty"`
	ExcludeDraft bool                   `protobuf:"varint,4,opt,name=exclude_draft,json=excludeDraft,proto3" json:"exclude_draft,omitempty"`
	// Optional: "draft" | "published". When set, filters by status; takes precedence over exclude_draft.
	RecipeStatus  string `protobuf:"bytes,5,opt,name=recipe_status,json=recipeStatus,proto3" json:"recipe_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecipesRequest) Reset() {
	*x = ListRecipesRequest{}
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecipesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecipesRequest) ProtoMessage() {}

func (x *ListRecipesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecipesRequest.ProtoReflect.Descriptor instead.
func (*ListRecipesRequest) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_recipe_proto_rawDescGZIP(), []int{0}
}

func (x *ListRecipesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRecipesRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListRecipesRequest) GetKitchenTag() string {
	if x != nil {
		return x.KitchenTag
	}
	return ""
}

func (x *ListRecipesRequest) GetExcludeDraft() bool {
	if x != nil {
		return x.ExcludeDraft
	}
	return false
}

func (x *ListRecipesRequest) GetRecipeStatus() string {
	if x != nil {
		return x.RecipeStatus
	}
	return ""
}

type ListRecipesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipes       []*Recipe              `protobuf:"bytes,1,rep,name=recipes,proto3" json:"recipes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecipesReply) Reset() {
	*x = ListRecipesReply{}
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecipesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecipesReply) ProtoMessage() {}

func (x *ListRecipesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecipesReply.ProtoReflect.Descriptor instead.
func (*ListRecipesReply) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_recipe_proto_rawDescGZIP(), []int{1}
}

func (x *ListRecipesReply) GetRecipes() []*Recipe {
	if x != nil {
		return x.Recipes
	}
	return nil
}

type GetRecipeDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecipeDetailRequest) Reset() {
	*x = GetRecipeDetailRequest{}
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecipeDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecipeDetailRequest) ProtoMessage() {}

func (x *GetRecipeDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecipeDetailRequest.ProtoReflect.Descriptor instead.
func (*GetRecipeDetailRequest) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_recipe_proto_rawDescGZIP(), []int{2}
}

func (x *GetRecipeDetailRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRecipeDetailReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        *RecipeDetail          `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecipeDetailReply) Reset() {
	*x = GetRecipeDetailReply{}
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecipeDetailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecipeDetailReply) ProtoMessage() {}

func (x *GetRecipeDetailReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecipeDetailReply.ProtoReflect.Descriptor instead.
func (*GetRecipeDetailReply) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_recipe_proto_rawDescGZIP(), []int{3}
}

func (x *GetRecipeDetailReply) GetDetail() *RecipeDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type CreateRecipeDraftIngredient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupName     string                 `protobuf:"bytes,1,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AmountText    string                 `protobuf:"bytes,3,opt,name=amount_text,json=amountText,proto3" json:"amount_text,omitempty"`
	Preparation   string                 `protobuf:"bytes,4,opt,name=preparation,proto3" json:"preparation,omitempty"`
	Remark        string                 `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecipeDraftIngredient) Reset() {
	*x = CreateRecipeDraftIngredient{}
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecipeDraftIngredient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecipeDraftIngredient) ProtoMessage() {}

func (x *CreateRecipeDraftIngredient) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecipeDraftIngredient.ProtoReflect.Descriptor instead.
func (*CreateRecipeDraftIngredient) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_recipe_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRecipeDraftIngredient) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *CreateRecipeDraftIngredient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRecipeDraftIngredient) GetAmountText() string {
	if x != nil {
		return x.AmountText
	}
	return ""
}

func (x *CreateRecipeDraftIngredient) GetPreparation() string {
	if x != nil {
		return x.Preparation
	}
	return ""
}

func (x *CreateRecipeDraftIngredient) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type CreateRecipeDraftStep struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Title          string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	StepType       string                 `protobuf:"bytes,3,opt,name=step_type,json=stepType,proto3" json:"step_type,omitempty"`
	NeedTimer      bool                   `protobuf:"varint,4,opt,name=need_timer,json=needTimer,proto3" json:"need_timer,omitempty"`
	TimerSeconds   int32                  `protobuf:"varint,5,opt,name=timer_seconds,json=timerSeconds,proto3" json:"timer_seconds,omitempty"`
	TimerAnimation string                 `protobuf:"bytes,6,opt,name=timer_animation,json=timerAnimation,proto3" json:"timer_animation,omitempty"`
	EndCondition   string                 `protobuf:"bytes,7,opt,name=end_condition,json=endCondition,proto3" json:"end_condition,omitempty"`
	HeatLevel      string                 `protobuf:"bytes,8,opt,name=heat_level,json=heatLevel,proto3" json:"heat_level,omitempty"`
	SafetyTips     string                 `protobuf:"bytes,9,opt,name=safety_tips,json=safetyTips,proto3" json:"safety_tips,omitempty"`
	AiHint         string                 `protobuf:"bytes,10,opt,name=ai_hint,json=aiHint,proto3" json:"ai_hint,omitempty"`
	MediaUrl       string                 `protobuf:"bytes,11,opt,name=media_url,json=mediaUrl,proto3" json:"media_url,omitempty"`
	MediaUrls      []string               `protobuf:"bytes,12,rep,name=media_urls,json=mediaUrls,proto3" json:"media_urls,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateRecipeDraftStep) Reset() {
	*x = CreateRecipeDraftStep{}
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecipeDraftStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecipeDraftStep) ProtoMessage() {}

func (x *CreateRecipeDraftStep) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecipeDraftStep.ProtoReflect.Descriptor instead.
func (*CreateRecipeDraftStep) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_recipe_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRecipeDraftStep) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateRecipeDraftStep) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRecipeDraftStep) GetStepType() string {
	if x != nil {
		return x.StepType
	}
	return ""
}

func (x *CreateRecipeDraftStep) GetNeedTimer() bool {
	if x != nil {
		return x.NeedTimer
	}
	return false
}

func (x *CreateRecipeDraftStep) GetTimerSeconds() int32 {
	if x != nil {
		return x.TimerSeconds
	}
	return 0
}

func (x *CreateRecipeDraftStep) GetTimerAnimation() string {
	if x != nil {
		return x.TimerAnimation
	}
	return ""
}

func (x *CreateRecipeDraftStep) GetEndCondition() string {
	if x != nil {
		return x.EndCondition
	}
	return ""
}

func (x *CreateRecipeDraftStep) GetHeatLevel() string {
	if x != nil {
		return x.HeatLevel
	}
	return ""
}

func (x *CreateRecipeDraftStep) GetSafetyTips() string {
	if x != nil {
		return x.SafetyTips
	}
	return ""
}

func (x *CreateRecipeDraftStep) GetAiHint() string {
	if x != nil {
		return x.AiHint
	}
	return ""
}

func (x *CreateRecipeDraftStep) GetMediaUrl() string {
	if x != nil {
		return x.MediaUrl
	}
	return ""
}

func (x *CreateRecipeDraftStep) GetMediaUrls() []string {
	if x != nil {
		return x.MediaUrls
	}
	return nil
}

type CreateRecipeDraftRequest struct {
	state            protoimpl.MessageState         `protogen:"open.v1"`
	Title            string                         `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Summary          string                         `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	CoverImageUrl    string                         `protobuf:"bytes,3,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
	Category         string                         `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	TotalMinutes     int32                          `protobuf:"varint,5,opt,name=total_minutes,json=totalMinutes,proto3" json:"total_minutes,omitempty"`
	Difficulty       int32                          `protobuf:"varint,6,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tools            []string                       `protobuf:"bytes,7,rep,name=tools,proto3" json:"tools,omitempty"`
	ScenarioTags     []string                       `protobuf:"bytes,8,rep,name=scenario_tags,json=scenarioTags,proto3" json:"scenario_tags,omitempty"`
	FlavorTags       []string                       `protobuf:"bytes,9,rep,name=flavor_tags,json=flavorTags,proto3" json:"flavor_tags,omitempty"`
	Ingredients      []*CreateRecipeDraftIngredient `protobuf:"bytes,10,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	Steps            []*CreateRecipeDraftStep       `protobuf:"bytes,11,rep,name=steps,proto3" json:"steps,omitempty"`
	GalleryImageUrls []string                       `protobuf:"bytes,12,rep,name=gallery_image_urls,json=galleryImageUrls,proto3" json:"gallery_image_urls,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateRecipeDraftRequest) Reset() {
	*x = CreateRecipeDraftRequest{}
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecipeDraftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecipeDraftRequest) ProtoMessage() {}

func (x *CreateRecipeDraftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecipeDraftRequest.ProtoReflect.Descriptor instead.
func (*CreateRecipeDraftRequest) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_recipe_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRecipeDraftRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateRecipeDraftRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *CreateRecipeDraftRequest) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *CreateRecipeDraftRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateRecipeDraftRequest) GetTotalMinutes() int32 {
	if x != nil {
		return x.TotalMinutes
	}
	return 0
}

func (x *CreateRecipeDraftRequest) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *CreateRecipeDraftRequest) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *CreateRecipeDraftRequest) GetScenarioTags() []string {
	if x != nil {
		return x.ScenarioTags
	}
	return nil
}

func (x *CreateRecipeDraftRequest) GetFlavorTags() []string {
	if x != nil {
		return x.FlavorTags
	}
	return nil
}

func (x *CreateRecipeDraftRequest) GetIngredients() []*CreateRecipeDraftIngredient {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

func (x *CreateRecipeDraftRequest) GetSteps() []*CreateRecipeDraftStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *CreateRecipeDraftRequest) GetGalleryImageUrls() []string {
	if x != nil {
		return x.GalleryImageUrls
	}
	return nil
}

type CreateRecipeDraftReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        *RecipeDetail          `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRecipeDraftReply) Reset() {
	*x = CreateRecipeDraftReply{}
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRecipeDraftReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecipeDraftReply) ProtoMessage() {}

func (x *CreateRecipeDraftReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecipeDraftReply.ProtoReflect.Descriptor instead.
func (*CreateRecipeDraftReply) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_recipe_proto_rawDescGZIP(), []int{7}
}

func (x *CreateRecipeDraftReply) GetDetail() *RecipeDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type UpdateRecipeRequest struct {
	state            protoimpl.MessageState         `protogen:"open.v1"`
	Id               int64                          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title            string                         `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Summary          string                         `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	CoverImageUrl    string                         `protobuf:"bytes,4,opt,name=cover_image_url,json=coverImageUrl,proto3" json:"cover_image_url,omitempty"`
	GalleryImageUrls []string                       `protobuf:"bytes,5,rep,name=gallery_image_urls,json=galleryImageUrls,proto3" json:"gallery_image_urls,omitempty"`
	Category         string                         `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Status           string                         `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	TotalMinutes     int32                          `protobuf:"varint,8,opt,name=total_minutes,json=totalMinutes,proto3" json:"total_minutes,omitempty"`
	Difficulty       int32                          `protobuf:"varint,9,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tools            []string                       `protobuf:"bytes,10,rep,name=tools,proto3" json:"tools,omitempty"`
	ScenarioTags     []string                       `protobuf:"bytes,11,rep,name=scenario_tags,json=scenarioTags,proto3" json:"scenario_tags,omitempty"`
	FlavorTags       []string                       `protobuf:"bytes,12,rep,name=flavor_tags,json=flavorTags,proto3" json:"flavor_tags,omitempty"`
	Metadata         *structpb.Struct               `protobuf:"bytes,13,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Ingredients      []*CreateRecipeDraftIngredient `protobuf:"bytes,14,rep,name=ingredients,proto3" json:"ingredients,omitempty"`
	Steps            []*CreateRecipeDraftStep       `protobuf:"bytes,15,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateRecipeRequest) Reset() {
	*x = UpdateRecipeRequest{}
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecipeRequest) ProtoMessage() {}

func (x *UpdateRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecipeRequest.ProtoReflect.Descriptor instead.
func (*UpdateRecipeRequest) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_recipe_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRecipeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRecipeRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateRecipeRequest) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *UpdateRecipeRequest) GetCoverImageUrl() string {
	if x != nil {
		return x.CoverImageUrl
	}
	return ""
}

func (x *UpdateRecipeRequest) GetGalleryImageUrls() []string {
	if x != nil {
		return x.GalleryImageUrls
	}
	return nil
}

func (x *UpdateRecipeRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateRecipeRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateRecipeRequest) GetTotalMinutes() int32 {
	if x != nil {
		return x.TotalMinutes
	}
	return 0
}

func (x *UpdateRecipeRequest) GetDifficulty() int32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *UpdateRecipeRequest) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *UpdateRecipeRequest) GetScenarioTags() []string {
	if x != nil {
		return x.ScenarioTags
	}
	return nil
}

func (x *UpdateRecipeRequest) GetFlavorTags() []string {
	if x != nil {
		return x.FlavorTags
	}
	return nil
}

func (x *UpdateRecipeRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateRecipeRequest) GetIngredients() []*CreateRecipeDraftIngredient {
	if x != nil {
		return x.Ingredients
	}
	return nil
}

func (x *UpdateRecipeRequest) GetSteps() []*CreateRecipeDraftStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

type UpdateRecipeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Detail        *RecipeDetail          `protobuf:"bytes,1,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRecipeReply) Reset() {
	*x = UpdateRecipeReply{}
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRecipeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRecipeReply) ProtoMessage() {}

func (x *UpdateRecipeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRecipeReply.ProtoReflect.Descriptor instead.
func (*UpdateRecipeReply) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_recipe_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateRecipeReply) GetDetail() *RecipeDetail {
	if x != nil {
		return x.Detail
	}
	return nil
}

type DeleteRecipeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecipeRequest) Reset() {
	*x = DeleteRecipeRequest{}
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecipeRequest) ProtoMessage() {}

func (x *DeleteRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecipeRequest.ProtoReflect.Descriptor instead.
func (*DeleteRecipeRequest) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_recipe_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteRecipeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteRecipeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRecipeReply) Reset() {
	*x = DeleteRecipeReply{}
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecipeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecipeReply) ProtoMessage() {}

func (x *DeleteRecipeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecipeReply.ProtoReflect.Descriptor instead.
func (*DeleteRecipeReply) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_recipe_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteRecipeReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type TodayRecipeReason struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kind 例如 "meal_plan" / "preference" / "popular" / "recently_cooked"，前端可用于展示徽章。
	Kind          string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Label         string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodayRecipeReason) Reset() {
	*x = TodayRecipeReason{}
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodayRecipeReason) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodayRecipeReason) ProtoMessage() {}

func (x *TodayRecipeReason) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodayRecipeReason.ProtoReflect.Descriptor instead.
func (*TodayRecipeReason) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_recipe_proto_rawDescGZIP(), []int{12}
}

func (x *TodayRecipeReason) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *TodayRecipeReason) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type TodayRecipe struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Recipe *Recipe                `protobuf:"bytes,1,opt,name=recipe,proto3" json:"recipe,omitempty"`
	Score  float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	// reasons 为该菜谱被推荐的多条命中理由，按权重降序排列。
	Reasons       []*TodayRecipeReason `protobuf:"bytes,3,rep,name=reasons,proto3" json:"reasons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TodayRecipe) Reset() {
	*x = TodayRecipe{}
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TodayRecipe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodayRecipe) ProtoMessage() {}

func (x *TodayRecipe) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodayRecipe.ProtoReflect.Descriptor instead.
func (*TodayRecipe) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_recipe_proto_rawDescGZIP(), []int{13}
}

func (x *TodayRecipe) GetRecipe() *Recipe {
	if x != nil {
		return x.Recipe
	}
	return nil
}

func (x *TodayRecipe) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *TodayRecipe) GetReasons() []*TodayRecipeReason {
	if x != nil {
		return x.Reasons
	}
	return nil
}

type ListTodayRecipesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTodayRecipesRequest) Reset() {
	*x = ListTodayRecipesRequest{}
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodayRecipesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodayRecipesRequest) ProtoMessage() {}

func (x *ListTodayRecipesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTodayRecipesRequest.ProtoReflect.Descriptor instead.
func (*ListTodayRecipesRequest) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_recipe_proto_rawDescGZIP(), []int{14}
}

func (x *ListTodayRecipesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListTodayRecipesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*TodayRecipe         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTodayRecipesReply) Reset() {
	*x = ListTodayRecipesReply{}
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodayRecipesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodayRecipesReply) ProtoMessage() {}

func (x *ListTodayRecipesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTodayRecipesReply.ProtoReflect.Descriptor instead.
func (*ListTodayRecipesReply) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_recipe_proto_rawDescGZIP(), []int{15}
}

func (x *ListTodayRecipesReply) GetItems() []*TodayRecipe {
	if x != nil {
		return x.Items
	}
	return nil
}

type AddRecipeFavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipeId      int64                  `protobuf:"varint,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRecipeFavoriteRequest) Reset() {
	*x = AddRecipeFavoriteRequest{}
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRecipeFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRecipeFavoriteRequest) ProtoMessage() {}

func (x *AddRecipeFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRecipeFavoriteRequest.ProtoReflect.Descriptor instead.
func (*AddRecipeFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_recipe_proto_rawDescGZIP(), []int{16}
}

func (x *AddRecipeFavoriteRequest) GetRecipeId() int64 {
	if x != nil {
		return x.RecipeId
	}
	return 0
}

type AddRecipeFavoriteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipe        *Recipe                `protobuf:"bytes,1,opt,name=recipe,proto3" json:"recipe,omitempty"`
	Favored       bool                   `protobuf:"varint,2,opt,name=favored,proto3" json:"favored,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRecipeFavoriteReply) Reset() {
	*x = AddRecipeFavoriteReply{}
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRecipeFavoriteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRecipeFavoriteReply) ProtoMessage() {}

func (x *AddRecipeFavoriteReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRecipeFavoriteReply.ProtoReflect.Descriptor instead.
func (*AddRecipeFavoriteReply) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_recipe_proto_rawDescGZIP(), []int{17}
}

func (x *AddRecipeFavoriteReply) GetRecipe() *Recipe {
	if x != nil {
		return x.Recipe
	}
	return nil
}

func (x *AddRecipeFavoriteReply) GetFavored() bool {
	if x != nil {
		return x.Favored
	}
	return false
}

type RemoveRecipeFavoriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecipeId      int64                  `protobuf:"varint,1,opt,name=recipe_id,json=recipeId,proto3" json:"recipe_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRecipeFavoriteRequest) Reset() {
	*x = RemoveRecipeFavoriteRequest{}
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRecipeFavoriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRecipeFavoriteRequest) ProtoMessage() {}

func (x *RemoveRecipeFavoriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRecipeFavoriteRequest.ProtoReflect.Descriptor instead.
func (*RemoveRecipeFavoriteRequest) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_recipe_proto_rawDescGZIP(), []int{18}
}

func (x *RemoveRecipeFavoriteRequest) GetRecipeId() int64 {
	if x != nil {
		return x.RecipeId
	}
	return 0
}

type RemoveRecipeFavoriteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRecipeFavoriteReply) Reset() {
	*x = RemoveRecipeFavoriteReply{}
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRecipeFavoriteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRecipeFavoriteReply) ProtoMessage() {}

func (x *RemoveRecipeFavoriteReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRecipeFavoriteReply.ProtoReflect.Descriptor instead.
func (*RemoveRecipeFavoriteReply) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_recipe_proto_rawDescGZIP(), []int{19}
}

func (x *RemoveRecipeFavoriteReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ListMyFavoritesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Limit int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// 上一页最后一项 id，下一页从此向前翻
	BeforeId      int64 `protobuf:"varint,2,opt,name=before_id,json=beforeId,proto3" json:"before_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyFavoritesRequest) Reset() {
	*x = ListMyFavoritesRequest{}
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyFavoritesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyFavoritesRequest) ProtoMessage() {}

func (x *ListMyFavoritesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyFavoritesRequest.ProtoReflect.Descriptor instead.
func (*ListMyFavoritesRequest) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_recipe_proto_rawDescGZIP(), []int{20}
}

func (x *ListMyFavoritesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMyFavoritesRequest) GetBeforeId() int64 {
	if x != nil {
		return x.BeforeId
	}
	return 0
}

type ListMyFavoritesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipes       []*Recipe              `protobuf:"bytes,1,rep,name=recipes,proto3" json:"recipes,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyFavoritesReply) Reset() {
	*x = ListMyFavoritesReply{}
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyFavoritesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyFavoritesReply) ProtoMessage() {}

func (x *ListMyFavoritesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_recipe_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyFavoritesReply.ProtoReflect.Descriptor instead.
func (*ListMyFavoritesReply) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_recipe_proto_rawDescGZIP(), []int{21}
}

func (x *ListMyFavoritesReply) GetRecipes() []*Recipe {
	if x != nil {
		return x.Recipes
	}
	return nil
}

func (x *ListMyFavoritesReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_api_aicook_v1_recipe_proto protoreflect.FileDescriptor

const file_api_aicook_v1_recipe_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/aicook/v1/recipe.proto\x12\taicook.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1aapi/aicook/v1/common.proto\"\xaf\x01\n" +
	"\x12ListRecipesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12\x1f\n" +
	"\vkitchen_tag\x18\x03 \x01(\tR\n" +
	"kitchenTag\x12#\n" +
	"\rexclude_draft\x18\x04 \x01(\bR\fexcludeDraft\x12#\n" +
	"\rrecipe_status\x18\x05 \x01(\tR\frecipeStatus\"?\n" +
	"\x10ListRecipesReply\x12+\n" +
	"\arecipes\x18\x01 \x03(\v2\x11.aicook.v1.RecipeR\arecipes\"(\n" +
	"\x16GetRecipeDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"G\n" +
	"\x14GetRecipeDetailReply\x12/\n" +
	"\x06detail\x18\x01 \x01(\v2\x17.aicook.v1.RecipeDetailR\x06detail\"\xab\x01\n" +
	"\x1bCreateRecipeDraftIngredient\x12\x1d\n" +
	"\n" +
	"group_name\x18\x01 \x01(\tR\tgroupName\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vamount_text\x18\x03 \x01(\tR\n" +
	"amountText\x12 \n" +
	"\vpreparation\x18\x04 \x01(\tR\vpreparation\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\"\x93\x03\n" +
	"\x15CreateRecipeDraftStep\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\tstep_type\x18\x03 \x01(\tR\bstepType\x12\x1d\n" +
	"\n" +
	"need_timer\x18\x04 \x01(\bR\tneedTimer\x12#\n" +
	"\rtimer_seconds\x18\x05 \x01(\x05R\ftimerSeconds\x12'\n" +
	"\x0ftimer_animation\x18\x06 \x01(\tR\x0etimerAnimation\x12#\n" +
	"\rend_condition\x18\a \x01(\tR\fendCondition\x12\x1d\n" +
	"\n" +
	"heat_level\x18\b \x01(\tR\theatLevel\x12\x1f\n" +
	"\vsafety_tips\x18\t \x01(\tR\n" +
	"safetyTips\x12\x17\n" +
	"\aai_hint\x18\n" +
	" \x01(\tR\x06aiHint\x12\x1b\n" +
	"\tmedia_url\x18\v \x01(\tR\bmediaUrl\x12\x1d\n" +
	"\n" +
	"media_urls\x18\f \x03(\tR\tmediaUrls\"\xdf\x03\n" +
	"\x18CreateRecipeDraftRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x12&\n" +
	"\x0fcover_image_url\x18\x03 \x01(\tR\rcoverImageUrl\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12#\n" +
	"\rtotal_minutes\x18\x05 \x01(\x05R\ftotalMinutes\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x06 \x01(\x05R\n" +
	"difficulty\x12\x14\n" +
	"\x05tools\x18\a \x03(\tR\x05tools\x12#\n" +
	"\rscenario_tags\x18\b \x03(\tR\fscenarioTags\x12\x1f\n" +
	"\vflavor_tags\x18\t \x03(\tR\n" +
	"flavorTags\x12H\n" +
	"\vingredients\x18\n" +
	" \x03(\v2&.aicook.v1.CreateRecipeDraftIngredientR\vingredients\x126\n" +
	"\x05steps\x18\v \x03(\v2 .aicook.v1.CreateRecipeDraftStepR\x05steps\x12,\n" +
	"\x12gallery_image_urls\x18\f \x03(\tR\x10galleryImageUrls\"I\n" +
	"\x16CreateRecipeDraftReply\x12/\n" +
	"\x06detail\x18\x01 \x01(\v2\x17.aicook.v1.RecipeDetailR\x06detail\"\xb7\x04\n" +
	"\x13UpdateRecipeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x12&\n" +
	"\x0fcover_image_url\x18\x04 \x01(\tR\rcoverImageUrl\x12,\n" +
	"\x12gallery_image_urls\x18\x05 \x03(\tR\x10galleryImageUrls\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12#\n" +
	"\rtotal_minutes\x18\b \x01(\x05R\ftotalMinutes\x12\x1e\n" +
	"\n" +
	"difficulty\x18\t \x01(\x05R\n" +
	"difficulty\x12\x14\n" +
	"\x05tools\x18\n" +
	" \x03(\tR\x05tools\x12#\n" +
	"\rscenario_tags\x18\v \x03(\tR\fscenarioTags\x12\x1f\n" +
	"\vflavor_tags\x18\f \x03(\tR\n" +
	"flavorTags\x123\n" +
	"\bmetadata\x18\r \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12H\n" +
	"\vingredients\x18\x0e \x03(\v2&.aicook.v1.CreateRecipeDraftIngredientR\vingredients\x126\n" +
	"\x05steps\x18\x0f \x03(\v2 .aicook.v1.CreateRecipeDraftStepR\x05steps\"D\n" +
	"\x11UpdateRecipeReply\x12/\n" +
	"\x06detail\x18\x01 \x01(\v2\x17.aicook.v1.RecipeDetailR\x06detail\"%\n" +
	"\x13DeleteRecipeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"#\n" +
	"\x11DeleteRecipeReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"=\n" +
	"\x11TodayRecipeReason\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"\x86\x01\n" +
	"\vTodayRecipe\x12)\n" +
	"\x06recipe\x18\x01 \x01(\v2\x11.aicook.v1.RecipeR\x06recipe\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x126\n" +
	"\areasons\x18\x03 \x03(\v2\x1c.aicook.v1.TodayRecipeReasonR\areasons\"/\n" +
	"\x17ListTodayRecipesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"E\n" +
	"\x15ListTodayRecipesReply\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.aicook.v1.TodayRecipeR\x05items\"7\n" +
	"\x18AddRecipeFavoriteRequest\x12\x1b\n" +
	"\trecipe_id\x18\x01 \x01(\x03R\brecipeId\"]\n" +
	"\x16AddRecipeFavoriteReply\x12)\n" +
	"\x06recipe\x18\x01 \x01(\v2\x11.aicook.v1.RecipeR\x06recipe\x12\x18\n" +
	"\afavored\x18\x02 \x01(\bR\afavored\":\n" +
	"\x1bRemoveRecipeFavoriteRequest\x12\x1b\n" +
	"\trecipe_id\x18\x01 \x01(\x03R\brecipeId\"+\n" +
	"\x19RemoveRecipeFavoriteReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"K\n" +
	"\x16ListMyFavoritesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x1b\n" +
	"\tbefore_id\x18\x02 \x01(\x03R\bbeforeId\"Y\n" +
	"\x14ListMyFavoritesReply\x12+\n" +
	"\arecipes\x18\x01 \x03(\v2\x11.aicook.v1.RecipeR\arecipes\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xd9\b\n" +
	"\rRecipeService\x12b\n" +
	"\vListRecipes\x12\x1d.aicook.v1.ListRecipesRequest\x1a\x1b.aicook.v1.ListRecipesReply\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/recipes\x12w\n" +
	"\x10ListTodayRecipes\x12\".aicook.v1.ListTodayRecipesRequest\x1a .aicook.v1.ListTodayRecipesReply\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/recipes/today\x12x\n" +
	"\x0fListMyFavorites\x12!.aicook.v1.ListMyFavoritesRequest\x1a\x1f.aicook.v1.ListMyFavoritesReply\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/recipes/favorites\x12}\n" +
	"\x11CreateRecipeDraft\x12#.aicook.v1.CreateRecipeDraftRequest\x1a!.aicook.v1.CreateRecipeDraftReply\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/recipes:draft\x12\x8c\x01\n" +
	"\x11AddRecipeFavorite\x12#.aicook.v1.AddRecipeFavoriteRequest\x1a!.aicook.v1.AddRecipeFavoriteReply\"/\x82\xd3\xe4\x93\x02):\x01*\"$/api/v1/recipes/{recipe_id}/favorite\x12\x92\x01\n" +
	"\x14RemoveRecipeFavorite\x12&.aicook.v1.RemoveRecipeFavoriteRequest\x1a$.aicook.v1.RemoveRecipeFavoriteReply\",\x82\xd3\xe4\x93\x02&*$/api/v1/recipes/{recipe_id}/favorite\x12s\n" +
	"\x0fGetRecipeDetail\x12!.aicook.v1.GetRecipeDetailRequest\x1a\x1f.aicook.v1.GetRecipeDetailReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/recipes/{id}\x12m\n" +
	"\fUpdateRecipe\x12\x1e.aicook.v1.UpdateRecipeRequest\x1a\x1c.aicook.v1.UpdateRecipeReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\x1a\x14/api/v1/recipes/{id}\x12j\n" +
	"\fDeleteRecipe\x12\x1e.aicook.v1.DeleteRecipeRequest\x1a\x1c.aicook.v1.DeleteRecipeReply\"\x1c\x82\xd3\xe4\x93\x02\x16*\x14/api/v1/recipes/{id}B7Z5github.com/chengjiang/aicook/backend/api/aicook/v1;v1b\x06proto3"

var (
	file_api_aicook_v1_recipe_proto_rawDescOnce sync.Once
	file_api_aicook_v1_recipe_proto_rawDescData []byte
)

func file_api_aicook_v1_recipe_proto_rawDescGZIP() []byte {
	file_api_aicook_v1_recipe_proto_rawDescOnce.Do(func() {
		file_api_aicook_v1_recipe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_aicook_v1_recipe_proto_rawDesc), len(file_api_aicook_v1_recipe_proto_rawDesc)))
	})
	return file_api_aicook_v1_recipe_proto_rawDescData
}

var file_api_aicook_v1_recipe_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_api_aicook_v1_recipe_proto_goTypes = []any{
	(*ListRecipesRequest)(nil),          // 0: aicook.v1.ListRecipesRequest
	(*ListRecipesReply)(nil),            // 1: aicook.v1.ListRecipesReply
	(*GetRecipeDetailRequest)(nil),      // 2: aicook.v1.GetRecipeDetailRequest
	(*GetRecipeDetailReply)(nil),        // 3: aicook.v1.GetRecipeDetailReply
	(*CreateRecipeDraftIngredient)(nil), // 4: aicook.v1.CreateRecipeDraftIngredient
	(*CreateRecipeDraftStep)(nil),       // 5: aicook.v1.CreateRecipeDraftStep
	(*CreateRecipeDraftRequest)(nil),    // 6: aicook.v1.CreateRecipeDraftRequest
	(*CreateRecipeDraftReply)(nil),      // 7: aicook.v1.CreateRecipeDraftReply
	(*UpdateRecipeRequest)(nil),         // 8: aicook.v1.UpdateRecipeRequest
	(*UpdateRecipeReply)(nil),           // 9: aicook.v1.UpdateRecipeReply
	(*DeleteRecipeRequest)(nil),         // 10: aicook.v1.DeleteRecipeRequest
	(*DeleteRecipeReply)(nil),           // 11: aicook.v1.DeleteRecipeReply
	(*TodayRecipeReason)(nil),           // 12: aicook.v1.TodayRecipeReason
	(*TodayRecipe)(nil),                 // 13: aicook.v1.TodayRecipe
	(*ListTodayRecipesRequest)(nil),     // 14: aicook.v1.ListTodayRecipesRequest
	(*ListTodayRecipesReply)(nil),       // 15: aicook.v1.ListTodayRecipesReply
	(*AddRecipeFavoriteRequest)(nil),    // 16: aicook.v1.AddRecipeFavoriteRequest
	(*AddRecipeFavoriteReply)(nil),      // 17: aicook.v1.AddRecipeFavoriteReply
	(*RemoveRecipeFavoriteRequest)(nil), // 18: aicook.v1.RemoveRecipeFavoriteRequest
	(*RemoveRecipeFavoriteReply)(nil),   // 19: aicook.v1.RemoveRecipeFavoriteReply
	(*ListMyFavoritesRequest)(nil),      // 20: aicook.v1.ListMyFavoritesRequest
	(*ListMyFavoritesReply)(nil),        // 21: aicook.v1.ListMyFavoritesReply
	(*Recipe)(nil),                      // 22: aicook.v1.Recipe
	(*RecipeDetail)(nil),                // 23: aicook.v1.RecipeDetail
	(*structpb.Struct)(nil),             // 24: google.protobuf.Struct
}
var file_api_aicook_v1_recipe_proto_depIdxs = []int32{
	22, // 0: aicook.v1.ListRecipesReply.recipes:type_name -> aicook.v1.Recipe
	23, // 1: aicook.v1.GetRecipeDetailReply.detail:type_name -> aicook.v1.RecipeDetail
	4,  // 2: aicook.v1.CreateRecipeDraftRequest.ingredients:type_name -> aicook.v1.CreateRecipeDraftIngredient
	5,  // 3: aicook.v1.CreateRecipeDraftRequest.steps:type_name -> aicook.v1.CreateRecipeDraftStep
	23, // 4: aicook.v1.CreateRecipeDraftReply.detail:type_name -> aicook.v1.RecipeDetail
	24, // 5: aicook.v1.UpdateRecipeRequest.metadata:type_name -> google.protobuf.Struct
	4,  // 6: aicook.v1.UpdateRecipeRequest.ingredients:type_name -> aicook.v1.CreateRecipeDraftIngredient
	5,  // 7: aicook.v1.UpdateRecipeRequest.steps:type_name -> aicook.v1.CreateRecipeDraftStep
	23, // 8: aicook.v1.UpdateRecipeReply.detail:type_name -> aicook.v1.RecipeDetail
	22, // 9: aicook.v1.TodayRecipe.recipe:type_name -> aicook.v1.Recipe
	12, // 10: aicook.v1.TodayRecipe.reasons:type_name -> aicook.v1.TodayRecipeReason
	13, // 11: aicook.v1.ListTodayRecipesReply.items:type_name -> aicook.v1.TodayRecipe
	22, // 12: aicook.v1.AddRecipeFavoriteReply.recipe:type_name -> aicook.v1.Recipe
	22, // 13: aicook.v1.ListMyFavoritesReply.recipes:type_name -> aicook.v1.Recipe
	0,  // 14: aicook.v1.RecipeService.ListRecipes:input_type -> aicook.v1.ListRecipesRequest
	14, // 15: aicook.v1.RecipeService.ListTodayRecipes:input_type -> aicook.v1.ListTodayRecipesRequest
	20, // 16: aicook.v1.RecipeService.ListMyFavorites:input_type -> aicook.v1.ListMyFavoritesRequest
	6,  // 17: aicook.v1.RecipeService.CreateRecipeDraft:input_type -> aicook.v1.CreateRecipeDraftRequest
	16, // 18: aicook.v1.RecipeService.AddRecipeFavorite:input_type -> aicook.v1.AddRecipeFavoriteRequest
	18, // 19: aicook.v1.RecipeService.RemoveRecipeFavorite:input_type -> aicook.v1.RemoveRecipeFavoriteRequest
	2,  // 20: aicook.v1.RecipeService.GetRecipeDetail:input_type -> aicook.v1.GetRecipeDetailRequest
	8,  // 21: aicook.v1.RecipeService.UpdateRecipe:input_type -> aicook.v1.UpdateRecipeRequest
	10, // 22: aicook.v1.RecipeService.DeleteRecipe:input_type -> aicook.v1.DeleteRecipeRequest
	1,  // 23: aicook.v1.RecipeService.ListRecipes:output_type -> aicook.v1.ListRecipesReply
	15, // 24: aicook.v1.RecipeService.ListTodayRecipes:output_type -> aicook.v1.ListTodayRecipesReply
	21, // 25: aicook.v1.RecipeService.ListMyFavorites:output_type -> aicook.v1.ListMyFavoritesReply
	7,  // 26: aicook.v1.RecipeService.CreateRecipeDraft:output_type -> aicook.v1.CreateRecipeDraftReply
	17, // 27: aicook.v1.RecipeService.AddRecipeFavorite:output_type -> aicook.v1.AddRecipeFavoriteReply
	19, // 28: aicook.v1.RecipeService.RemoveRecipeFavorite:output_type -> aicook.v1.RemoveRecipeFavoriteReply
	3,  // 29: aicook.v1.RecipeService.GetRecipeDetail:output_type -> aicook.v1.GetRecipeDetailReply
	9,  // 30: aicook.v1.RecipeService.UpdateRecipe:output_type -> aicook.v1.UpdateRecipeReply
	11, // 31: aicook.v1.RecipeService.DeleteRecipe:output_type -> aicook.v1.DeleteRecipeReply
	23, // [23:32] is the sub-list for method output_type
	14, // [14:23] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_aicook_v1_recipe_proto_init() }
func file_api_aicook_v1_recipe_proto_init() {
	if File_api_aicook_v1_recipe_proto != nil {
		return
	}
	file_api_aicook_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_aicook_v1_recipe_proto_rawDesc), len(file_api_aicook_v1_recipe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_aicook_v1_recipe_proto_goTypes,
		DependencyIndexes: file_api_aicook_v1_recipe_proto_depIdxs,
		MessageInfos:      file_api_aicook_v1_recipe_proto_msgTypes,
	}.Build()
	File_api_aicook_v1_recipe_proto = out.File
	file_api_aicook_v1_recipe_proto_goTypes = nil
	file_api_aicook_v1_recipe_proto_depIdxs = nil
}
