// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/aicook/v1/voice.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetId       int64                  `protobuf:"varint,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeRequest) Reset() {
	*x = TranscribeRequest{}
	mi := &file_api_aicook_v1_voice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeRequest) ProtoMessage() {}

func (x *TranscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_voice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeRequest.ProtoReflect.Descriptor instead.
func (*TranscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_voice_proto_rawDescGZIP(), []int{0}
}

func (x *TranscribeRequest) GetAssetId() int64 {
	if x != nil {
		return x.AssetId
	}
	return 0
}

type SpeechSegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartMs       int64                  `protobuf:"varint,1,opt,name=start_ms,json=startMs,proto3" json:"start_ms,omitempty"`
	EndMs         int64                  `protobuf:"varint,2,opt,name=end_ms,json=endMs,proto3" json:"end_ms,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeechSegment) Reset() {
	*x = SpeechSegment{}
	mi := &file_api_aicook_v1_voice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeechSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeechSegment) ProtoMessage() {}

func (x *SpeechSegment) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_voice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeechSegment.ProtoReflect.Descriptor instead.
func (*SpeechSegment) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_voice_proto_rawDescGZIP(), []int{1}
}

func (x *SpeechSegment) GetStartMs() int64 {
	if x != nil {
		return x.StartMs
	}
	return 0
}

func (x *SpeechSegment) GetEndMs() int64 {
	if x != nil {
		return x.EndMs
	}
	return 0
}

func (x *SpeechSegment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SpeechSegment) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type TranscribeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Segments      []*SpeechSegment       `protobuf:"bytes,3,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeReply) Reset() {
	*x = TranscribeReply{}
	mi := &file_api_aicook_v1_voice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeReply) ProtoMessage() {}

func (x *TranscribeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_aicook_v1_voice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeReply.ProtoReflect.Descriptor instead.
func (*TranscribeReply) Descriptor() ([]byte, []int) {
	return file_api_aicook_v1_voice_proto_rawDescGZIP(), []int{2}
}

func (x *TranscribeReply) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranscribeReply) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *TranscribeReply) GetSegments() []*SpeechSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

var File_api_aicook_v1_voice_proto protoreflect.FileDescriptor

const file_api_aicook_v1_voice_proto_rawDesc = "" +
	"\n" +
	"\x19api/aicook/v1/voice.proto\x12\taicook.v1\x1a\x1cgoogle/api/annotations.proto\".\n" +
	"\x11TranscribeRequest\x12\x19\n" +
	"\basset_id\x18\x01 \x01(\x03R\aassetId\"k\n" +
	"\rSpeechSegment\x12\x19\n" +
	"\bstart_ms\x18\x01 \x01(\x03R\astartMs\x12\x15\n" +
	"\x06end_ms\x18\x02 \x01(\x03R\x05endMs\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\"{\n" +
	"\x0fTranscribeReply\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\x124\n" +
	"\bsegments\x18\x03 \x03(\v2\x18.aicook.v1.SpeechSegmentR\bsegments2\x7f\n" +
	"\fVoiceService\x12o\n" +
	"\n" +
	"Transcribe\x12\x1c.aicook.v1.TranscribeRequest\x1a\x1a.aicook.v1.TranscribeReply\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/media/transcriptionsB7Z5github.com/chengjiang/aicook/backend/api/aicook/v1;v1b\x06proto3"

var (
	file_api_aicook_v1_voice_proto_rawDescOnce sync.Once
	file_api_aicook_v1_voice_proto_rawDescData []byte
)

func file_api_aicook_v1_voice_proto_rawDescGZIP() []byte {
	file_api_aicook_v1_voice_proto_rawDescOnce.Do(func() {
		file_api_aicook_v1_voice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_aicook_v1_voice_proto_rawDesc), len(file_api_aicook_v1_voice_proto_rawDesc)))
	})
	return file_api_aicook_v1_voice_proto_rawDescData
}

var file_api_aicook_v1_voice_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_aicook_v1_voice_proto_goTypes = []any{
	(*TranscribeRequest)(nil), // 0: aicook.v1.TranscribeRequest
	(*SpeechSegment)(nil),     // 1: aicook.v1.SpeechSegment
	(*TranscribeReply)(nil),   // 2: aicook.v1.TranscribeReply
}
var file_api_aicook_v1_voice_proto_depIdxs = []int32{
	1, // 0: aicook.v1.TranscribeReply.segments:type_name -> aicook.v1.SpeechSegment
	0, // 1: aicook.v1.VoiceService.Transcribe:input_type -> aicook.v1.TranscribeRequest
	2, // 2: aicook.v1.VoiceService.Transcribe:output_type -> aicook.v1.TranscribeReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_aicook_v1_voice_proto_init() }
func file_api_aicook_v1_voice_proto_init() {
	if File_api_aicook_v1_voice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_aicook_v1_voice_proto_rawDesc), len(file_api_aicook_v1_voice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_aicook_v1_voice_proto_goTypes,
		DependencyIndexes: file_api_aicook_v1_voice_proto_depIdxs,
		MessageInfos:      file_api_aicook_v1_voice_proto_msgTypes,
	}.Build()
	File_api_aicook_v1_voice_proto = out.File
	file_api_aicook_v1_voice_proto_goTypes = nil
	file_api_aicook_v1_voice_proto_depIdxs = nil
}
