// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/chengjiang/aicook/backend/internal/auth"
	"github.com/chengjiang/aicook/backend/internal/biz"
	"github.com/chengjiang/aicook/backend/internal/conf"
	"github.com/chengjiang/aicook/backend/internal/data"
	"github.com/chengjiang/aicook/backend/internal/server"
	"github.com/chengjiang/aicook/backend/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

func initApp(cfg *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	db, cleanup, err := data.NewDB(cfg)
	if err != nil {
		return nil, nil, err
	}
	authRepo := data.NewAuthRepo(db)
	authAuthRepo := auth.NewAuthRepo()
	authUsecase := biz.NewAuthUsecase(authRepo, authAuthRepo)
	authService := service.NewAuthService(authUsecase)
	householdRepo := data.NewHouseholdRepo(db)
	householdUsecase := biz.NewHouseholdUsecase(householdRepo)
	householdService := service.NewHouseholdService(householdUsecase)
	recipeRepo := data.NewRecipeRepo(db)
	recipeUsecase := biz.NewRecipeUsecase(recipeRepo)
	recipeService := service.NewRecipeService(recipeUsecase)
	mediaRepo := data.NewMediaRepo(db)
	objectStorage, cleanup2, err := data.NewObjectStorage(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	mediaUsecase := biz.NewMediaUsecase(mediaRepo, objectStorage, cfg)
	mediaService := service.NewMediaService(mediaUsecase)
	client := data.NewInferenceClient(cfg)
	voiceUsecase := biz.NewVoiceUsecase(mediaRepo, objectStorage, client)
	voiceService := service.NewVoiceService(voiceUsecase)
	importRepo := data.NewImportRepo(db)
	runtime := data.NewAIRuntime(cfg)
	importUsecase := biz.NewImportUsecase(importRepo, mediaRepo, recipeRepo, objectStorage, client, runtime)
	importService := service.NewImportService(importUsecase)
	knowledgeRepo := data.NewKnowledgeRepo(db)
	knowledgeUsecase := biz.NewKnowledgeUsecase(knowledgeRepo, mediaRepo, objectStorage, cfg, runtime)
	knowledgeService := service.NewKnowledgeService(knowledgeUsecase)
	aiRepo := data.NewAIRepo(db)
	aiUsecase := biz.NewAIUsecase(aiRepo, runtime)
	aiService := service.NewAIService(aiUsecase)
	httpServer := server.NewHTTPServer(cfg, authService, householdService, recipeService, mediaService, voiceService, importService, knowledgeService, aiService)
	grpcServer := server.NewGRPCServer(cfg, authService, householdService, recipeService, mediaService, voiceService, importService, knowledgeService, aiService)
	app := server.NewApp(cfg, logger, httpServer, grpcServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
